### ISSUE TITLE
Merge repositories and statistics pages

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#107]

**Comment by AMDmi3** [comment]
Otoh, not sure if this is a good idea. There's no place for links in the statistics table, while repository list may be extended with even more links and even some numbers.

**Comment by AMDmi3** [comment]
Its not really needed. Actually, I don't even see a usecase for repositories page as it is now, e.g. a set of links to all/outdated/unique/... package lists for all repositories. Plain repository list would be redundant as well, as it duplicates statistics. Instead, we should split current `statistics` page into `repositories` and `graphs`.

**Comment by davidak** [comment]
>we should split current statistics page into repositories and graphs

:+1:

We could have the `repositories` statistics on the Repositories page and `graphs`, some numbers and a link to Repositories page on the current Statistics page. I miss the number of Repositories on the site.
