### ISSUE TITLE
Add quarterly repositories for FreeBSD and PkgSrc

### ISSUE THREAD

**Issue by jbeich** [repology/repology#156]
FreeBSD releases (since 10.2) default to a package set that's updated once a quarter with a few security/bug fixes in-between. Only one quarterly branch is supported at any time. PkgSrc does something similar.

Would be nice to compare their versions against Debian Stable or Testing.

**Comment by AMDmi3** [comment]
For this I need upstream to generate INDEX files for corresponding branches.

**Comment by AMDmi3** [comment]
I've added pkgsrc quarterly repo, FreeBSD still lacks downloadable INDEX for quartely branch.

**Comment by AMDmi3** [comment]
Closing: pkgsrc quartely support was added, and FreeBSD quartely support cannot be added until upstream publishes INDEX for a quartely branch.
