### ISSUE TITLE
Add more per-maintainer information

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#159]
- Repositories
- Categories

**Comment by alexmyczko** [comment]
Debian supports
QA page: https://qa.debian.org/developer.php?login=gurkan%40phys.ethz.ch
after the = use the maintainer email address

Submitted bug reports
https://bugs.debian.org/cgi-bin/pkgreport.cgi?maint=gurkan%40phys.ethz.ch

Policy is your friend. Trust the Policy. Love the Policy. Obey the Policy.
https://piuparts.debian.org/sid/maintainer/g/gurkan%40phys.ethz.ch.html

Lintian reports
https://lintian.debian.org/maintainer/gurkan@phys.ethz.ch.html

And build logs
https://buildd.debian.org/status/package.php?p=gurkan%40phys.ethz.ch&comaint=yes
