### ISSUE TITLE
Introduce metapackage flavors/branches

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#170]
Imagine there are following packages in a single repository

- libfoo 2.1
- libfoo1 1.0
- mingw32-libfoo 2.0
- mingw-w64-libfoo 2.0

What we want is to merge all these into libfoo. Because it's libfoo and a single version domain. We don't want to treat libfoo 1.0 as outdated because we have latest version in the same repository. But we do want to treat mingw*libfoo as outdated because there's newer version. So we introduce flavors, e.g. ```default``` and ```mingw``` and for domains in which there are a package with latest version we don't treat other packages as outdated.

**Comment by mojca** [comment]
I see this problem differently. I would probably introduce something like a "branch". For example, MacPorts provides at least python 2.7, 3.4, 3.5, 3.6, all at the same time. Or gcc 4.7, 4.8, 4.9, 5, 6, 7, all of them being available. What we want to make sure is that whenever a package manager provides a specific version of a packages (say, python 3.4), that it provides the latest version of that one (3.4.6). Another package manager might provide just python2 and python3 in which case you would want 2.7.13 and 3.6.1 as the latest ones. I guess I would group these versions by branches (2, 3, 2.7, 3.4, 3.5, 3.6) and potentially allow specifying subbranches (that is: declare somewhere that 3.6 is a branch of 3?).

You could still introduce flavours if needed, but I cannot see how they would solve the problem with versioning. How would you declare a flavour in case of pure gcc / python which is not part of anything else? I would still want to know if my python 3.5 is outdated.

**Comment by AMDmi3** [comment]
> I see this problem differently. I would probably introduce something like a "branch".

We already support this by using separate metapackages for different branches. There's [python2](https://repology.org/metapackage/python2) and [python3](https://repology.org/metapackage/python3), for instance. These are mainly handled in [rules.d/45.splitmergever.yaml](https://github.com/repology/repology/blob/master/rules.d/45.splitmergever.yaml). I try to not split metapackages as long as it's not really necessary (e.g. split is OK if there is an interface incompatibility, such as between python 2 and 3; but not for python 3.5 and 3.6 while the latter is a compatible drop-in replacement for the former).

The one feature we lack is generating multiple metapackages for package though (#163) (e.g. make `python-2.7` package belong to both `python` and `python2`).

> You could still introduce flavours if needed, but I cannot see how they would solve the problem with versioning

It's a property orthogonal to branches, so it's needed in any case.

It's not explicit on the site and in the code, but there are actually two kinds of outdated packages: really-outdated ones (which require updating) and legacy (which do not, as they are preserved versions for e.g. compatibility or migration). While these both are rendered in red, when building "outdated for repository" or "outdated for maintainer" metapackage lists we look at whether there's a newest version of a metapackage in a repo. If there is, we ignore outdated packages there, assuming these are preserved legacy versions. Here's an example:

```
repo1:
    curl
        7.54.0 ← latest version available
repo2:
    curl ← not shown in outdated metapackage list...
        7.53.0 ← ...even though there's outdated version...
        7.54.0 ← ...because there is also a latest version in this repo
repo3:
    curl ← shown in outdated metapackage list, because all versions in this repo are outdated
        7.52.0 ← outdated
        7.53.0 ← outdated
```

Now we also have `mingw32-curl` and `compat32-curl`. Since these both are the very same curl, it makes sense to merge them into curl metapackage. However because of the mentioned logic, an outdated `mingw32-curl` will be treated outdated or legacy depending on whether there's latest `curl` in the repo.

flavors are supposed to fix that, in a way that legacy logic will only work within a single flavor - that is, `mingw32-curl` (`curl` with `mingw32` flavor) will be considered outdated as long as there's no latest `mingw32-curl` package in the same repository.

We also need to render `legacy` packages with different color. This was already requested in #213.
