### ISSUE TITLE
Add homebrew support

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#198]
Homebrew support turns out to be possible. Though they don't (always) have versions in their formulas as other packages do, they extract these from download urls, and only define if that doesn't work, so after processing versions _are_ available. Unfortunately, brew is not portable and we can't run in on FreeBSD we use to get processed info. On (MacOS) machine which is able to run brew, getting data is as easy as ```brew update && brew info --json=v1 --all```.

Homebrew leader, @MikeMcQuaid, is [defiantly unhelpful](http://discourse.brew.sh/t/regular-formula-info-dump-in-machine-readable-format/687) with this, so we wait for reply on https://github.com/koraktor/braumeister.org/issues/45 from @koraktor, maintainer of braumeister.org (online browser for Homebrew).

**Comment by AMDmi3** [comment]
PS. The code for homebrew support is there since 858e5a2c3a44bcc33e8e70f69bf2bef81e853dad, all is needed is a downloadable regularly updated json dump of homebrew.

**Comment by MikeMcQuaid** [comment]
> Homebrew leader, @MikeMcQuaid, is defiantly unhelpful with this, so we wait for reply on koraktor/braumeister.org#45 from @koraktor, maintainer of braumeister.org (online browser for Homebrew).

You asked me if our project would do additional work to help yours, I declined and you tell me it's easy. You then @mention me here to email me a rude message.  Do you think that makes me more or less likely to want to help you in future and do you think that makes maintainers of Homebrew more or less like to burn out?

**Comment by AMDmi3** [comment]
Rude is when you shut people looking for cooperation up by closing the topic and preventing additional discussion, when you know that while making a dump is easy for brew users on MacOSX, it's not possible at all for others as brew is not portable. No, I don't think that you'll help when you start with such an attitude, I'm just keeping the record of repology feature status.

**Comment by MikeMcQuaid** [comment]
> when you know that while making a dump is easy for brew users on MacOSX

It's easy to run a command as a once-off, it's not easy to maintain a server that provides this as a service that you can consume.

> it's not possible at all for others as brew is not portable

It is, actually.

> No, I don't think that you'll help when you start with such an attitude, I'm just keeping the record of repology feature status.

It was not a given that I would never help you with answering your questions in future. I'm no longer willing to do that any more either, though.

Good luck with the project (genuinely). It seems like it has potential but if you want other projects to help you you should reconsider how you ask for it.

**Comment by AMDmi3** [comment]
Well, we have to postpone this until there's cooperation from homebrew community then.

**Comment by tkelman** [comment]
Couldn't you run this on Travis CI? They offer osx builds, and you can set up cron builds to run daily and update the json output.

**Comment by AMDmi3** [comment]
🤔I'd prefer upstream cooperation, but it sounds like an interesting idea, shall investigate.

**Comment by AMDmi3** [comment]
It works fine. Homebrew support will be deployed on Monday.

**Comment by MikeMcQuaid** [comment]
> all is needed is a downloadable regularly updated json dump of homebrew.

@AMDmi3 I stand by my previous comments that this was not easy to build the infrastructure for this but: this is now implemented: https://formulae.brew.sh/docs/api/ (and more specifically: https://formulae.brew.sh/api/formula.json). Hopefully that's useful to you folks.

**Comment by AMDmi3** [comment]
Cool, thanks a lot! I'll check it out in a week.

**Comment by AMDmi3** [comment]
@MikeMcQuaid works perfectly, I've switched to it, thank you again! With this, homebrew data in repology will be updated with less delay too.

By the chance, isn't there a similar endpoint for casks? This was requested (#310), but I didn't find a way even to get a json dump for them.

**Comment by MikeMcQuaid** [comment]
@AMDmi3 Unfortunately there's no Cask JSON or endpoint yet: https://github.com/Homebrew/formulae.brew.sh/issues/13. I would like to see that happen in future, though.

**Comment by AMDmi3** [comment]
Good, I'll follow it too then.
