### ISSUE TITLE
Link check for redis homepage

### ISSUE THREAD

**Issue by audriusk** [repology/repology#211]
As can be seen in https://repology.org/metapackage/redis/information, link check for `https://redis.io/` fails with 404 response. But this only seems to be the case when issuing HEAD request:
```bash
$ curl -sIL https://redis.io/ | head -n1
HTTP/1.1 404 Not Found
```
When sending GET request, 200 response is returned:
```bash
$ curl -siL https://redis.io/ | head -n1
HTTP/1.1 200 OK
```

**Comment by AMDmi3** [comment]
Repology does not need homepage contents, and it doesn't want to use its own and checked websites' bandwidth by issuing GET requests needlessly. Well behaving sites should handle HEAD requests properly. You could contact `redis.io` admins and ask them to fix HEAD requests on their site.

**Comment by audriusk** [comment]
OK, I'll try contacting `redis.io` admins about this.

**Comment by AMDmi3** [comment]
Otoh, there are likely a lot of such errors, and we probably don't want for force maintainers to fix them all. I've added a fallback to GET to link checker.
