### ISSUE TITLE
 use gentoo suffix

### ISSUE THREAD

**Issue by blshkv** [repology/repology#217]
There is a problem with the following package:
https://repology.org/metapackages/outdated-in-repo/gentoo_ovl_pentoo/?search=hyenae

We have released 0.36_p1 version which is "patch" release of 0.36-1 (we cannot use hyphen here), see the following URL for more details:
https://devmanual.gentoo.org/ebuild-writing/file-format/

However, it is still listed as "0.36". Please parse gentoo suffixes as well.

Thank you.

**Comment by blshkv** [comment]
There is similar problem with https://repology.org/metapackage/rtl8812au/versions
I have just bumped "rtl8812au-4.3.14_p20170211.ebuild" which is patch release of 4.3.14.

**Comment by blshkv** [comment]
and https://repology.org/metapackage/unicornscan/versions
Gentoo has "0.4.7_p2" so it is not outdated

**Comment by AMDmi3** [comment]
Hmm, I was cutting off `_.*` from ebuild version, which doesn't seem correct, and a lot of useful alpha/beta/rc suffixes were lost. Perhaps I though it was related to revision number and not upstream version... I'm fixing this.

However, this will not fix hyenae as `0.36_p1` is still lower than `0.36-1`. Since upstream version is `0.36-1` and you can't use hyphens, you should've used `0.36_1` or `0.36.1` instead. Adding a letter which was not there is incorrect and cannot be handled properly by repology.

**Comment by AMDmi3** [comment]
For rtl8812au, I've added version ignore for `201[56]*` which are clearly incorrect. But it's hard with this package as different distros use different version schemas which cannot be compared directly. This could be solved with version transofmation rules which I have in plans. Or with additional version ignores which are already available.

unicornscan is the same as hyenae - it will work correctly as long as version is not fiddled with by adding letters which should not be there.

**Comment by blshkv** [comment]
Thanks. Could you also add a special meanings for prefixes, I.e.:
<version> is lower than <version>_p
And it is higher for the rest. 
That would solve everything

**Comment by AMDmi3** [comment]
If by "everything" you mean [hyenae](https://repology.org/metapackage/hyenae) and [unicornscan](https://repology.org/metapackage/unicornscan), no it won't, as even if you change ordering of `0.4.7.p2` against `0.4.7` these both will remain lesser than < `0.4.7-2` (which is the same as `0.4.7.2`). Same for `0.36_p1`, it'll remain lesser than `0.36-1` (which is the same as `0.36.1`) in any case.

But you're right in a way that it's reasonable to treat `p` as `patch` and not `pre`. It's already `1.0.pre1 < 1.0 < 1.0.patch1`, but `1.0.p1` currently equals to `1.0.pre1` and not `1.0.patch1`. I'll gather some statistics on how `p` is used and probably fix that, so reopening.

**Comment by blshkv** [comment]
I was under impression that ```0.4.7-2``` or ```0.4.7_2``` has a special meaning of "patch" release. Ok, nevermind. Let's go ahead and normalize both formats to ```0.4.7.2```.  Patch release would be something that linux distros add on the top of it I guess.

**Comment by AMDmi3** [comment]
Closing this, `p` handling will be tracked in repology/libversion#4
