### ISSUE TITLE
Guix: do not consider "maintainers" value

### ISSUE THREAD

**Issue by EmilePouget** [repology/repology#219]
In GNU Guix we do not follow the orthodox package maintainers role for contributors.
Therefore there is, and will probably never be, a field indicating responsible name+email for a package.
Any data generated from this is bound to stick to 0 forever.

**Comment by AMDmi3** [comment]
It's OK, repology already does not consider maintainers for repos where there's no such concept or where maintainers cannot be parsed yet.
