### ISSUE TITLE
Maintainers page: do not render valid email addresses

### ISSUE THREAD

**Issue by EmilePouget** [repology/repology#220]
In my opinion pages like these: https://repology.org/maintainer/a-burghardt%40gmx.de
are an open invitation for spam. In case the upstream project made efforts to protect their contributors
and maintainers against this, you would render these methods useless.

From the privacy/security point of view it becomes a huge collection of email addresses as the project grows.
I have no immediate solution, but there should be a method which does not reveal the email address and mailto: links unless something has been solved/achieved. Leaving out: capchas by google and other civilrights incompatible technologies and companies.

**Comment by AMDmi3** [comment]
Any public address is an "invitation for spam", despite on whether you try to obfuscate it or not, and the mere fact it is so easy for repology to parse these just proves that obfuscation is useless. Most repositories do not obfuscate maintainer emails, and are the very same "huge collections of email addresses", largest of which is GitHub, and no one is complaining. Being of no use, obfuscation makes life harder for legitimate parties such as package users and fellow maintainers. Repology strives to improve collaboration between maintainers, users and software authors, and for that an easy way to contact a person is crucial. So no, repology will not hide emails.

**Comment by EmilePouget** [comment]
So a case of "wontfix because others are doing it aswell"?

Okay then.

**Comment by AMDmi3** [comment]
No, wontfix because there is no problem.

**Comment by brobr** [comment]
>Repology strives to improve collaboration between maintainers, users and software authors 

Well, I just send an email about this, I am opting out of this collaboration.
 'Repology' does not need to act on maintainer's behalf on what they want to have shared in public. 

Nobody has been asked to be on this site nor any opt-out mechanism has been put in place.  According to recent eu-legislation, this is not correct.

This attitude will force maintainers not to publish their email addresses in any form when they are getting handed out like this.  And your site runs the risk of being reported for breaking privacy laws, which defies the reason for its existence... then there will be a problem
