### ISSUE TITLE
ignore obsolete packages from MacPorts

### ISSUE THREAD

**Issue by mojca** [repology/repology#235]
The list of MacPorts packages contains obsolete ports marked by
```
PortGroup obsolete 1.0
```
like for example `p5.22-any-name`.

Those ports should not be listed. I guess that [portindex2json.tcl](https://github.com/repology/repology/blob/master/helpers/portindex2json/portindex2json.tcl) could be fixed to filter those out.

@jmroot

**Comment by AMDmi3** [comment]
PortIndex I use for repology doesn't contain PortGroup. It also doesn't contain p5.22-any-name, maybe obsolete ports are already filtered out there?

**Comment by AMDmi3** [comment]
There are ports with `replaced_by` field though, should I maybe drop these?

**Comment by mojca** [comment]
Maybe I should have written `p5.22-foo` to make it clearer :)

Try `p5.22-wx` for example or see

https://repology.org/metapackage/perl:wx/versions

Figuring this out might not be 100% straightforward. This is the code that checks for the PortGroup on our build infrastructure:

https://github.com/macports/mpbb/blob/master/mpbb-list-subports
https://github.com/macports/mpbb/blob/master/tools/portgroups.tcl

It would probably help if we would extend MacPorts a bit to make this information easier to extract.

Yes `replaced_by` should cover most cases. (There might be obsolete ports without replacements, but we usually delete those.)

Adding @ryandesign as well.

**Comment by AMDmi3** [comment]
@jmroot btw, I've improved [portindex2json.tcl](https://github.com/repology/repology/blob/master/helpers/portindex2json/portindex2json.tcl) a bit, may submit a PR to https://github.com/macports/macports-contrib or you could just merge it
- made it take file to use as first argument
- made it always use utf-8 for I/O

**Comment by AMDmi3** [comment]
So I'm now dropping ports with replaced_by (will be in effect on https://repology.org in about 2 hours).

**Comment by ryandesign** [comment]
Yes `replaced_by` is the correct MacPorts base feature to look at; don't try to determine if the `obsolete-1.0` portgroup is being used. The portgroup is incidental. Ports could not include that portgroup, but reimplement its functionality. One day in the future, MacPorts base might implement its functionality and then the portgroup would be unnecessary.
