### ISSUE TITLE
Introduce alternative names for packages

### ISSUE THREAD

**Issue by mojca** [repology/repology#236]
When a MacPorts `Portfile` contains subports, a single file may provide multiple packages. An additional variables is probably needed to point to the right sources of the package.

Example: `p5.24-wx` comes from `p5-wx`.

**Comment by AMDmi3** [comment]
Yes, the same problem plagues other repos which allow port name (usually a directory in a tree) and package name (usually generated with prefixes/suffixes added) to be different, see also #103.

This haven't been fixed yet as I haven't decided the best way to implement it. There are essentially two solutions:
- just add an additional field to the package, say `altname`
- add a way to store dictionary with generic data in the package

The former one seems sufficient for now and I don't want to overengineer, so I'll probably go that way and switch to the latter if that's required.

For information, `altname` could be used for
- FreeBSD, pkgsrc, openbsd, dports repos to store port origin (essentially a path in a ports tree such as `www/firefox`) which is not related to package name (which could be `Firefox`, for instance) and used to produce correct links to FreeBSD ports
- macports, for the reason stated in this issue
- f-droid, where it will store java class (e.g. `name.boyle.chris.sgtpuzzles`) and as well will use it to for proper links to f-droid packages

**Comment by timofonic** [comment]
@AMDmi3  Do you think the current approach is good enough? What about Gentoo with different releases and the -9999 version that goes to VCS repos? What about unofficial repositories?

Any hopes about f-droid and Google Play?

**Comment by AMDmi3** [comment]
> Do you think the current approach is good enough?

Approach to what exactly?

> What about Gentoo with different releases and the -9999 version that goes to VCS repos?

9999 is ignored as it cannot be compared in any meaningful way. I can't see how it can be done better.

> What about unofficial repositories?

Which ones, and what about them?

> Any hopes about f-droid

F-Droid is supported, but there's not much use, as there isn't much intersection with desktop repos, and it's index is incomplete.

> and Google Play?

This is in no way a free software package repository.

**Comment by timofonic** [comment]
@AMDmi3 Do you think the current approach is good enough?

- What about packages like the ones in Gentoo and Exherbo? Are -9999 packages (no idea how they are in Exherbo, I like to try it) tracked too?

- What about f-droid.org plus unofficial repos? What about Google Play? What about other Android stores like the Amazon one and others?

- What about these [language package managers](https://neurocline.github.io/papers/survey-of-programming-language-packaging-systems.html) ? For example: npm, cargo, cabal, pip, CTAN, CPAN, RubyGems, jpm, maven, NuGet,goget/goinstall, Conan, cpm, ghp, luarocks, etc

**Comment by timofonic** [comment]
Google Play package versions could be compared, there are sites and tools for it. It could be useful to see if f-froid packages aren't updated but only Google Play ones, something more common than it should.

Sorry for repeating, I did think the message not got sent.

Unofficial repos: There's a bunch on Gentoo ([overlays](https://overlays.gentoo.org)) and [Archlinux unofficial repos](https://wiki.archlinux.org/index.php/Unofficial_user_repositories). And maybe you know Exherbo repoS are more distributed than the rest :)
