### ISSUE TITLE
Remove Ubuntu 12.04 LTS, EOL

### ISSUE THREAD

**Issue by jbicha** [repology/repology#237]
Ubuntu 12.04 LTS has reached End of Life, so feel free to remove it.

https://lists.ubuntu.com/archives/ubuntu-announce/2017-April/000221.html

**Comment by AMDmi3** [comment]
I know, but I'm hesitant. It's still widely used in Travis CI and many other places, and it's nice to show how outdated it actually is.

**Comment by AMDmi3** [comment]
Let's not remove it since it's still widely used.
