### ISSUE TITLE
Ubuntu stable version numbers do not include updates

### ISSUE THREAD

**Issue by jbicha** [repology/repology#238]
Ubuntu should currently show 2.16.1 for all versions of webkit2gtk

https://repology.org/metapackage/webkit2gtk/versions
https://launchpad.net/ubuntu/+source/webkit2gtk

I think you should use -release and -updates (-security should be copied to -updates so you don't have to worry about -security here).

**Comment by AMDmi3** [comment]
I currently take `{name}` from [here](http://ftp.ubuntu.com/ubuntu/dists/). Do I understand correctly that I should also take `{name}-updates`?

**Comment by jbicha** [comment]
Yes. -updates are enabled by default although not automatically installed by default (unlike security which is).

Some packages don't get updates so you need to look at both, but `{name}-updates` should always be newer than `{name}` when it does exist.

**Comment by jbicha** [comment]
https://launchpad.net/ubuntu/+source/mutter is a test case for a package that was updated in a couple releases but not in others.

**Comment by AMDmi3** [comment]
Got it. I also guess Debian needs the same change.
