### ISSUE TITLE
Selected erroneous latest version number claims

### ISSUE THREAD

**Issue by ryandesign** [repology/repology#240]
I've was just made aware of repology. Apologies if some of these issues have already been reported elsewhere; I skimmed the issue titles but might have missed something.

The [list of MacPorts ports I maintain that are supposedly out of date](https://repology.org/metapackages/outdated-by-maintainer/ryandesign%40macports.org/) looks very useful. I'll have to spend some time checking those. MacPorts has its own feature for finding new versions of upstream software, but it relies on us specifying which web site to look at for that information and sometimes that can be out of date.

I do see some erroneous claims on that page though. Picking a few:

* [x] It claims the latest bzip2 version is 1.0.6.0.1 while we have 1.0.6. In fact, 1.0.6 is the latest; 1.0.6.0.1 is a nonexistent version of this software.
* [x] It claims the latest cairo is 1.15.4 while we have 1.14.8. 1.15.4 is a development version which we have in cairo-devel, alongside the stable version in cairo.
* [x] It claims the latest icu-le-hb is 1.0.3.3 while we have 1.0.3. Again, there is no such version of this project as 1.0.3.3; 1.0.3 is the latest.
* [x] It claims the latest libiconv is 8 while we have 1.15. I'm not sure where version number 8 comes from. Maybe a library version number? 1.15 is the latest version of the libiconv software package that exists.
* [x] It claims the latest magic is 8.1.158 while we have 8.0.127. In fact the latest development version of magic is 8.1.164 and we have that in magic-devel. The latest stable version is 8.0.217 which we have in magic.
* [x] It claims the latest php56:excel is 1.8.0 while we have 1.0.2. You must be thinking of [this PHPExcel project](https://github.com/PHPOffice/PHPExcel) whose latest version is 1.8.1. But our port is of [this php_excel project](https://github.com/iliaal/php_excel) whose latest version is 1.0.2.
* [x] It claims the latest synfigstudio is 1.3.3 while we have 1.2.0. 1.3.x is the development series; we follow the stable series of which the latest version is 1.2.0.
* [x] It claims the latest tidy is 20110307 while we have 5.4.0. We are using a modern [fork of tidy](https://github.com/htacg/tidy-html5) whose latest version is 5.4.0.
* [x] It claims the latest wine is 2.7.1 but says we have 2.7. We have 2.7 in wine-devel, which is the latest development version, and 2.6 in wine, which is the latest stable version. No version 2.7.1 exists.

**Comment by AMDmi3** [comment]
(magic 8.1 is now stable, 8.2 is devel)
