### ISSUE TITLE
Add Fink support

### ISSUE THREAD

**Issue by l2dy** [repology/repology#243]
[Fink](http://www.finkproject.org/) has a list of all packages: http://pdb.finkproject.org/pdb/browse.php

**Comment by AMDmi3** [comment]
Looks doable. With nochildren flag.

**Comment by AMDmi3** [comment]
Rather, https://github.com/fink/fink-distributions should be parsed - it has more info and it's the only way to deal with package types (e.g. `wget`, `wget-idn`, `wget-gnutls`, `wget-gnutls-idn`). However it still looks polluted with unclean naming (e.g. `bullet2.85-shlibs`), using shared lib version in name etc.

**Comment by AMDmi3** [comment]
There's no usable data for fink.
- pdb contains too little info and is polluted with package name suffixes it won't be easy to normalize
- repository uses weird format which requires recursive parsing and uses complex substitutions (like `%type-pkg[perl]`) I'm not going to reimplement 

See https://repology.org/addrepo for information of what is needed to add support for a repository.
