### ISSUE TITLE
MinGW packages

### ISSUE THREAD

**Issue by mojca** [repology/repology#248]
The [MinGW packages](https://repology.org/metapackages/all/?search=mingw) are currently a bit of a mess, with each distribution providing its own package names.

There are two "different" projects, MinGW and MinGW-w64. And package are different:
- the compiler (gcc) which should be at some fixed version of gcc (compared to gcc versions)
- binutils (which should be compared to binutils versions)
- mingw-w64 itself
- potentially other libraries for use when cross-compiling

In case of MacPorts we have five packages that derive from mingw-w64 for example:
* mingw-w64 @5.0.2 (meta port)
* i686-w64-mingw32-crt @5.0.2
* i686-w64-mingw32-headers @5.0.2
* x86_64-w64-mingw32-crt @5.0.2
* x86_64-w64-mingw32-headers @5.0.2

plus binutils, gcc, ... as well as the old MinGW package.

**Comment by AMDmi3** [comment]
> The MinGW packages are currently a bit of a mess

True.

> There are two "different" projects, MinGW and MinGW-w64

I don't have a clear understanding of difference between these yet and thus I don't know whether these could/should be merged or not.

Either way, we need to:
- merge toolchain parts (gcc, binutils, gdb) into either
  - their originals (gcc, binutils, gdb)
  - a distinct set of mingw packages
  - a two distinct sets of packages for mingw and mingw-w64
- one or to metapackages for the library (crt/runtime/headers) correspondingly
- merge all libraries with their original metapackages (mingw-w64-boost -> boost), but we need flavors (#170) for that first

**Comment by AMDmi3** [comment]
Moved to https://github.com/repology/repology-rules/issues/10
