### ISSUE TITLE
Arch package link broken

### ISSUE THREAD

**Issue by l2dy** [repology/repology#255]
In https://repology.org/metapackage/bash-completion/versions,
https://git.archlinux.org/svntogit/extra.git/tree/trunk?h=packages/bash-completion should be https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/bash-completion

**Comment by AMDmi3** [comment]
God, subrepositories do not correspond to git repo names there. There's no apparent way to fix that for now.
