### ISSUE TITLE
Support MSYS2

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#262]
See https://github.com/repology/repology/issues/1#issuecomment-309509599.

Support is in the repo, but it's not complete and disabled.

We parse http://repo.msys2.org/msys/x86_64/msys.db.tar.gz which contain processed packages database, but we can't reliably derive information on _source_ packages from there (we need that to filter out *-devel and other subpackages). There are %BASE% and %NAME% fields, but we can't rely on them as they are not necessarily related. The best way would be to parse PKGBUILDS directly, but we don't have shell parser (#166) for this yet.

**Comment by AMDmi3** [comment]
@Alexpux you might be interested.

**Comment by Alexpux** [comment]
@AMDmi3 thanks for info

**Comment by dg0yt** [comment]
Great job!

**Comment by AMDmi3** [comment]
@Alexpux you might be interested as well: msys2 repositories are now supported by repology:

https://repology.org/metapackages/?inrepo=msys2_mingw
https://repology.org/metapackages/?inrepo=msys2_msys2
