### ISSUE TITLE
Merge webkit metapackages

### ISSUE THREAD

**Issue by jbicha** [repology/repology#268]
Test Case
=======
I'd like to see what version of the latest [webkitgtk](https://webkitgtk.org/) is offered in different distros. But webkitgtk packaging is particularly unique in its naming.

- [libwebkit-gtk](https://dev.solus-project.com/source/libwebkit-gtk/)  - Solus (not yet in repology)
- [webkit2gtk](https://repology.org/metapackage/webkit2gtk/versions) -  Arch Linux and Debian
- [webkit2gtk3](https://repology.org/metapackage/webkit2gtk3/versions) - OpenSUSE
- [webkitgtk4](https://repology.org/metapackage/webkitgtk4/versions) - Fedora

I'd like to see those all linked together or matched so that it's easy to see. Otherwise, it requires manually figuring out the source package names for all the different distros and loading those pages manually.

I'm proposing adding a bit of metadata so that Repology understands that all those different source packages are packaging the same source.

**Comment by AMDmi3** [comment]
Repology does that from the start, see rules.d directory in the repo. There are no rules for webkit yet (although I've already sern requests to merge it) because I'm too confused by the number of webkit packages

https://repology.org/metapackages/all/?search=webkit

so I'd be grateful for some insight here: are all these webkit*gtk* a single project (some repos just using outdated versions), or are there multiple branches developed in parallel, or are there multiple projects from different authors? As result, into how many metapackages should webkit stuff be merged?

**Comment by pink-mist** [comment]
It's very confusing indeed. As far as I understand it, there are two different APIs for **version 1** and **version 2** of webkitgtk, and while **version 1** has been deprecated, a lot of software still uses it, so having a different package for it is still useful.

 * **Version 1** is usually just named ```webkitgtk``` (or ```libwebkit-gtk```) without a version between webkit and gtk, and
* **version 2** is usually named ```webkit2gtk```

Then the version for ```gtk``` can also be specified, for example the SlackBuilds.org repository has these: ```webkitgtk```, ```webkitgtk3```, and ```webkit2gtk```, where the first two are for **version 1**, differing in which version of gtk they're built for (they're built for ```gtk 2``` and ```gtk 3``` respectively) and the last one is for **version 2**.

**Comment by jbicha** [comment]
@AMDmi3 all of the ones I specified in my original comment represent the same library.

We're trying to get rid of the old version of the library. Arch has already dropped it, Fedora is dropping it for 27 late this year and Debian and Ubuntu will follow. The old library hasn't been updated in years so it's not that interesting. :smile:

**Comment by AMDmi3** [comment]
Naming patterns are so varying and unreliable that I'd prefer not to bother with them. We can start by merging them all into a single metapackage. Aren't there any version patterns/ranges which could be used to split into webkit 1/2 then?

**Comment by pink-mist** [comment]
I'm working on a PR to do that right now =) And I **believe** that 2.4.11 is the latest one with **version 1** API, but I'm uncertain if that's where the switch happened.
