### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#269]
@tkelman:
> Cygwin: http://mirrors.mit.edu/cygwin/x86_64/setup.ini, http://mirrors.mit.edu/cygwin/x86/setup.ini

**Comment by AMDmi3** [comment]
With these files, there's no way to filter out subpackages, e.g. to drop ```aalib-debuginfo``` and ```aalib-devel``` and only leave ```alib```.

**Comment by tkelman** [comment]
There's also https://cygwin.com/packages/package_list.html and https://cygwin.com/cgi-bin2/package-grep.cgi, they're a bit slow and maybe not as flexible as you'd need.

**Comment by AMDmi3** [comment]
The same problem - no way to filter out subpackages.

**Comment by tkelman** [comment]
Actually from the ini file you could unique the `source` fields, and only list the first or shortest of binary packages that come from the same source value.

**Comment by AMDmi3** [comment]
That would erroneously drop _real_ separate packages are built from the same source, as with libQt*4.

**Comment by tkelman** [comment]
> There should be a repo with original "source" packages - do you know where it is located? Maybe we could parse that instead.

Didn't notice this edit. Could you clarify what you mean here? There's also https://cygwin.com/cygwin-pkg-maint which lists things by maintainer, but I haven't tried comparing to see how it matches in completeness.

**Comment by tkelman** [comment]
The directory listing of http://mirrors.mit.edu/cygwin/x86_64/release/ might also be what you want?

Note there are lots of mirrors, the MIT one has been fast and reliable for my purposes but depending where you run things you might want to choose differently.

**Comment by AMDmi3** [comment]
> might also be what you want?

It doesn't contain versions.

**Comment by jon-turney** [comment]
I've started generating a json datasource (http://cygwin.com/packages/packages.json.xz), which should contain sufficent information to drive this, and had a stab at adding a parser for it.
