### ISSUE TITLE
CSP (Content-Security-Policy) header on repology.org doesn't allow loading fonts

### ISSUE THREAD

**Issue by antonv6** [repology/repology#281]
Here's the current header value:
```
Content-Security-Policy: default-src 'none'; style-src 'self'; script-src 'self'; img-src 'self'
```
It prevents chromium from loading 3 font files: glyphicons-halflings-regular.{woff2,woff,ttf} (presumably requested by bootstrap.css) with the following message:

> Refused to load the font 'https://repology.org/fonts/glyphicons-halflings-regular.woff2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

I'm not sure if you use glyphicons anywhere, maybe you don't need these font files at all, but the CSP violations are there nevertheless.

**Comment by AMDmi3** [comment]
Fixed, thank you! Fonts are not currently used, but I've fixed the header.
