### ISSUE TITLE
Totalling bug on repository summary page

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#288]
The Metapackages/Outdated column is not being calculated correctly.
A snapshot of ravenports:
Metapackages/Outdated shows "53".
Yet if you click on the hyperlink, the listed packages total 49.
Presumably the difference of 4 is explained by the presence of 4 "ignored" ports in Ravenports.

Thus the theory is Metapackages/Outdated column needs to discard "ignored" sum while calculating the total.

**Comment by AMDmi3** [comment]
It doesn't count ignored ports. There's small discrepancy because of how statistics are calculated and how versions are shown.

**Comment by jrmarino** [comment]
Alright, I should not have speculated and just stuck with the facts, which are:

The total shows 53, but only 49 are on the expanded list.  The total should accurately reflect the list total.

I'll leave the cause and fix up to you and restrict myself to reporting the issue.

**Comment by AMDmi3** [comment]
Fixed
