### ISSUE TITLE
Support for 'problems' in API output

### ISSUE THREAD

**Issue by mjeveritt** [repology/repology#293]
It would be really useful to get an output of 'problems' with packages in the maintainer and repository output listings via the API for QA purposes.
The standard URLs for such queries are:
* https://repology.org/repository/gentoo/problems
* https://repology.org/maintainer/mgorny%40gentoo.org/problems

I am attaching a patch to partially implement this for the by-maintainer filter, but I'm not sufficiently sure about the database aspects to pick the appropriate data tables/queries for this purpose.

I would also query whether, for the purposes of future expansion, for APIv1.1 or APIv2 it would be possible to make the API queries the same general format as the HTML queries? From the looks of the code, this -should- be fairly trivial, but am not sure of any difficulties if this has already been tried.

**Comment by mjeveritt** [comment]
```
diff --git a/repology-app.py b/repology-app.py
index 1908d8e..600c207 100755
--- a/repology-app.py
+++ b/repology-app.py
@@ -1152,6 +1152,12 @@ def api_v1_metapackages_outdated_by_maintainer(maintainer, bound=None):
     return api_v1_metapackages_generic(bound, MaintainerOutdatedQueryFilter(maintainer))
 
 
+@app.route('/api/v1/metapackages/problems-by-maintainer/<maintainer>/')
+@app.route('/api/v1/metapackages/problems-by-maintainer/<maintainer>/<bound>/')
+def api_v1_metapackages_problems_by_maintainer(maintainer, bound=None):
+    return api_v1_metapackages_generic(bound, MaintainerProblemsQueryFilter(maintainer))
+
+
 if __name__ == '__main__':
     if app.config['PROFILE']:
         app.wsgi_app = ProfilerMiddleware(app.wsgi_app, restrictions=[30])
diff --git a/repology/database.py b/repology/database.py
index e261f6b..f2fe5aa 100755
--- a/repology/database.py
+++ b/repology/database.py
@@ -82,6 +82,7 @@ class MetapackageRequest:
         # maintainer (maintainer_metapackages)
         self.maintainer = None
         self.maintainer_outdated = False
+        self.maintainer_problems = False
 
         # num families (metapackage_repocounts)
         self.morefamilies = None
@@ -131,6 +132,12 @@ class MetapackageRequest:
         self.maintainer = maintainer
         self.maintainer_outdated = True
 
+    def ProblemsForMaintainer(self, maintainer):
+        if self.maintainer:
+            raise RuntimeError('duplicate maintainer condition')
+        self.maintainer = maintainer
+        self.maintainer_problems = True
+
     def InRepo(self, repo):
         if self.repos and repo not in self.repos:
             raise RuntimeError('duplicate repository condition')
diff --git a/repology/queryfilters.py b/repology/queryfilters.py
index 606d0a4..a23ae84 100755
--- a/repology/queryfilters.py
+++ b/repology/queryfilters.py
@@ -144,6 +144,25 @@ class MaintainerOutdatedQueryFilter(QueryFilter):
         req.OutdatedForMaintainer(self.maintainer)
 
 
+class MaintainerProblemsQueryFilter(QueryFilter):
+    def __init__(self, maintainer):
+        self.maintainer = maintainer
+
+    ## FIXME START ########################
+    def GetTable(self):
+        return 'problems'
+
+    def GetWhere(self):
+        return '{table}.maintainer=%s and {table}.num_packages_outdated > 0'
+       ## FIXME END ##########################
+
+    def GetWhereArgs(self):
+        return [self.maintainer]
+
+    def ApplyToRequest(self, req):
+        req.ProblemsForMaintainer(self.maintainer)
+
+
 class InRepoQueryFilter(QueryFilter):
     def __init__(self, repo):
         self.repo = repo
```

**Comment by AMDmi3** [comment]
Done, thanks for suggestion! See [API documentation page](https://repology.org/api/v1).

Note that problem description is stored as plain text as it's stored internally for now, which may be not very convenient. Though the plans (#196) are to make it more flexible.

> I would also query whether, for the purposes of future expansion, for APIv1.1 or APIv2 it would be possible to make the API queries the same general format as the HTML queries?

What do you mean by general format? Cause it's not really general: only a set of fixed views (in-repo/not-in-repo/outdated-in-repo) is supported, and API supports everything which WWW does apart for fulltext search. The plans are to actually make it general, e.g. support an arbitrary set of mainainer/repo/category filters.

**Comment by mjeveritt** [comment]
Thanks for implementing this - it will be most useful!

>> I would also query whether, for the purposes of future expansion, for APIv1.1 or APIv2 it would be possible to make the API queries the same general format as the HTML queries?

> What do you mean by general format? Cause it's not really general: only a set of fixed views (in-repo/not-in-repo/outdated-in-repo) is supported, and API supports everything which WWW does apart for fulltext search. The plans are to actually make it general, e.g. support an arbitrary set of mainainer/repo/category filters.

I believe I was thinking of the URI construction .. there are some subtle differences in syntax between the HTML output and the JSON API format, which would make it slightly easier to match up the web output to script parsing!

**Comment by AMDmi3** [comment]
> subtle differences

Which are?
