### ISSUE TITLE
ravenports: new php extension ports aren't matching with existing metapackages

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#294]
see: https://repology.org/metapackages/unique-in-repo/ravenports/

All new php71 extension ports are currently considered "unique" despite having identical names as FreeBSD ports collection.

**Comment by jrmarino** [comment]
I guess the most effective approach in the future would be to create pull requests with rule updates that would just be approved for merge?  

Is anybody doing that yet and is that what you prefer?

**Comment by AMDmi3** [comment]
> I guess the most effective approach in the future would be to create pull requests with rule updates that would just be approved for merge?

Yes, as log as they are simple and correct, e.g. don't require a lot of iterations to fix.
