### ISSUE TITLE
Comprehensive analysis of aspell done, report on issues and recommended fixes

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#295]
The aspell project is kind of a mess.  Some of this mess is causing errors in Repology.
After importing aspell packages and using Repology to detect errors, these are the ones left over that need some manual fixes (affects all platforms).

1) **Change in version scheme,  ports with lower version numbers are actually the latest version:**

aspell-el: 0.08 is newer than 0.50-3, needs rule
ref: https://ftp.gnu.org/gnu/aspell/dict/el

aspell-ca: three versions defined: 0.50.2, 2.1.5.1 (newest), 20040130.1 (needs rule)
ref: https://ftp.gnu.org/gnu/aspell/dict/ca

aspell-fo: three version defined 0.50.2, 0.51.0, 0.2.16.1 (newest)  (rule: 0.2 > 0.51)
ref: https://ftp.gnu.org/gnu/aspell/dict/fo

2) **Bogus version, taking on main "aspell" version instead of dictionary version ("0.50" or "0.60")**

aspell-be: only one version defined: 0.01
ref: https://ftp.gnu.org/gnu/aspell/dict/be
versions to ignore: "0.60", "0.50.0" [mageia/rosa]

aspell-br: two versions defined: 0.50.1 and 0.50.2
ref: https://ftp.gnu.org/gnu/aspell/dict/br
versions to ignore: "0.60.2" [mageia/rosa]

aspell-fi: only one version defined: 0.7.0
ref: https://ftp.gnu.org/gnu/aspell/dict/fi
versions to ignore: "0.60" [mageia/rosa/PCLinuxOS]

aspell-fr: only one version defined: 0.50.3
ref: http://gnu.mirror.iweb.com/aspell/dict/fr/
versions to ignore: "0.60" [mageia/gentoo/PCLinuxOS]

aspell-sl: only one version defined: 0.50
ref: https://ftp.gnu.org/gnu/aspell/dict/sl
versions to ignore: "0.60" (ubuntu/debian)
A search for independently maintained SL aspell produced nothing

aspell-sr: only one version defined: 0.02
ref: http://gnu.mirror.iweb.com/aspell/dict/sr/
versions to ignore: "0.60" (gentoo/rosa)

aspell-te: only one version defined: 0.01.2
ref: https://ftp.gnu.org/gnu/aspell/dict/te
versions to ignore: "0.60" (rosa)

aspell-tet: only one version defined: 0.1.1
ref: https://ftp.gnu.org/gnu/aspell/dict/tet
versions to ignore "0.50" [mageia/rosa/PCLinuxOS/ALTsys]

3) **generically bogus version requiring ignore**

aspell-ca: three versions defined: 0.50.2, 2.1.5.1 (newest), 20040130.1
https://ftp.gnu.org/gnu/aspell/dict/ca
version to ignore: "20090721" [mageia/rosa] (possibly this version was released and removed by GNU based on directory timestamp)
Note aspell-ca is listed above as well, so it has two problems

aspell-qu: only one version defined: 0.02
ref: https://ftp.gnu.org/gnu/aspell/dict/qu/
version to ignore "20040424.1" [mageia/gentoo/PCLinuxOS/ALT Sisyphus]
Note: 20040424 is earlier that defined release date (8/26/04)

aspell-ru: two versions defined: 0.50, 0.99f7.0
ref: https://ftp.gnu.org/gnu/aspell/dict/ru
version to ignore "0.99.15.7.1" [openindiana]
Note: appears to be 0.99f7 converted to a different form

4) **Hebrew**

aspell-he: only nixos has version 1.1 listed (rest have 1.0)
Looking at the nixos github site, it possible accidently merged hspell (a separate spell checker) with aspell.
It doesn't appear compatible.
officially three versions are define: 0.8.0, 0.9.0, 1.0.0
Ref: http://gnu.mirror.iweb.com/aspell/dict/he/

**Comment by jrmarino** [comment]
oops, I forgot aspell-ru, will report from the website

**Comment by AMDmi3** [comment]
Is it done now?

**Comment by jrmarino** [comment]
everything except the hebrew (aspell-he)
my notes suggest version 1.1 should either be ignored or merged with "hspell" package.  It's just 
nixpkgs stable with the differing version.
--

**Comment by jrmarino** [comment]
I don't know why, but nixos entry to aspell-he disappeared, so it looks like there's nothing to be done for aspell-he (meaning you can close the issue)
