### ISSUE TITLE
hunspell-en, ignore ALT Sisyphus	

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#298]
ref: https://repology.org/metapackage/hunspell-en/versions

Every other repo uses YYYY.MM.DD version format, so the (ancient?!) ALT Sisyphus version 20060207 makes them all look outdated.

As an aside, it would be wonderful to be able to flag stuff like this on the website (as a shortcut to having to upen an "issue" here)

**Comment by jrmarino** [comment]
similar case with https://repology.org/metapackage/hunspell-es/versions
Older versions used 0.20081215, not 20081215 like ALT Sisyphus does.
In any case, the actually current version 2.2 (https://github.com/sbosio/rla-es/releases/)

In general, ALT Sysphus is a bad actor.  It's frequently on the list of rogue versioners.

**Comment by jrmarino** [comment]
hunspell-it: https://repology.org/metapackage/hunspell-it/versions
This time it's openindiana that needs suppression (also the case for hunspell-es above)

**Comment by AMDmi3** [comment]
> As an aside, it would be wonderful to be able to flag stuff like this on the website

It is possible for a long time, I've mentioned that multiple times.

**Comment by jrmarino** [comment]
> It is possible for a long time, I've mentioned that multiple times.

Yes, I see the "report" button now.  The report form looks good.  I'll definitely consider this option on a per-package basis.
