### ISSUE TITLE
Generate cross-platform Dockerfiles / Package name matching

### ISSUE THREAD

**Issue by roscopecoltran** [repology/repology#304]
Hi,

Hope you are all well !

**Requirement:**
I was wondering if there is a way to query a CLI or web services, built-in repology, to find for package name, all the version/package labels and get the results in JSON format.

**Goal:**
Automate the conversion of some existing Dockerfiles (Ubuntu/Debian) to Alpine based containers, mainly to reduce the size of images.

**Refs:**
- Small util for matching Alpine packages by filenames in pkg tree: https://github.com/roscopecoltran/apk-file

Cheers,
Richard

**Comment by AMDmi3** [comment]
Doesn't https://repology.org/api/v1 suit your needs?

**Comment by roscopecoltran** [comment]
awesome :-) 

Thanks a lot !
