### ISSUE TITLE
capability of identifying and handling "dev" versions needed

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#309]
Repology has a conceptual hole regarding dev versions.  For example, alpha/beta/rc/prerelease versions, or the odd-version scheme of gnome.

Rather than ignoring these versions (the logical approach with the current capabilities of repology), it may be better to have a "development" category, and allow rules to identify some releases as dev releases.

These dev releases would show as different color and they would not be considered in the "latest version" calculation.   Perhaps repology could have a switch (cookie) that considers them or not, but off by default.

My instinct says most users want dev versions filtered out, but I can see valid use cases where they would be wanted (e.g. by other maintainers of dev versions and general awareness reasons).  For this reason, keep them, but treat them differently.

**Comment by AMDmi3** [comment]
This is planned in #170.

**Comment by AMDmi3** [comment]
Done
