### ISSUE TITLE
Add homebrew-cask

### ISSUE THREAD

**Issue by kingthorin** [repology/repology#310]
It would be great if homebrew-cask was included as a repo:
https://caskroom.github.io/
https://github.com/caskroom/homebrew-cask

**Comment by AMDmi3** [comment]
I've already played with it, and there seem to be no analogue of `brew info --json=v1 --all`. At least `brew cask info --json=v1 --all` does not work: `Error: invalid option: --json=v1`

**Comment by kingthorin** [comment]
I'll see if I can dig something up. I'm not a Mac user but I do know a project I'm involved in is distributed via cask.

**Comment by kingthorin** [comment]
According to https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#searching-for-casks

`brew cask search` should produce `<list of all available Casks>`

**Comment by AMDmi3** [comment]
Names are not useful without versions

**Comment by kingthorin** [comment]
Ok. Will keep hunting. It's a bit harder to dig up details when I don't have access to a Mac to try stuff myself :)

**Comment by AMDmi3** [comment]
Homebrew have plans on implementing metadata API endpoint for casks: Homebrew/formulae.brew.sh#13, let's keep an eye on this.

**Comment by luzpaz** [comment]
ref: https://github.com/repology/repology/issues/310#issuecomment-394820873

> The Homebrew/brew side has been implemented in [Homebrew/brew#4410](https://github.com/Homebrew/brew/pull/4410)

**Comment by AMDmi3** [comment]
Nice, is there an API endpoint for it?

**Comment by luzpaz** [comment]
> Nice, but as far as I can see there's no API endpoint yet.

Yea, it doesn't seem like there is one yet. Looking forward to this.

**Comment by luzpaz** [comment]
New activity going on in the upstream ticket (https://github.com/Homebrew/formulae.brew.sh/issues/13)

**Comment by AMDmi3** [comment]
Closing this as there's nothing to do on Repology side yet.

**Comment by luzpaz** [comment]
> Closing this as there's nothing to do on Repology side *yet*.

@AMDmi3 is there a ticket that is still open that is tracking this issue still? (so i can subscribe to it)

**Comment by AMDmi3** [comment]
No

**Comment by luzpaz** [comment]
https://formulae.brew.sh/analytics/

**Comment by kingthorin** [comment]
> Closing this as there's nothing to do on Repology side yet.

I'm confused, people are obviously interested in this, there's obvious upstream activity (on the days/weeks scale) but because there's nothing for Repology to do yet (after years) it's being closed?

**Comment by AMDmi3** [comment]
Not helpful

**Comment by AMDmi3** [comment]
> I'm confused, people are obviously interested in this, there's obvious upstream activity (on the days/weeks scale) but because there's nothing for Repology to do yet (after years) it's being closed?

Yes, I'm not going to pile up inactive tickets. As soon as there's anything usable from upstream, a ticket can be (re)opened.

**Comment by kingthorin** [comment]
Ok fair enough, the timing just seemed strange, but I can understand your position.

**Comment by luzpaz** [comment]
@AMDmi3 what is needed then ?

**Comment by AMDmi3** [comment]
Package names and versions.

**Comment by kingthorin** [comment]
Does this fill the requirement(s)?
https://formulae.brew.sh/api/formula.json
https://formulae.brew.sh/api/cask/owasp-zap.json

**Comment by AMDmi3** [comment]
The former is the list of normal brew formulae, it's already used for Homebrew repository and has nothing to do with casks. The latter is the info on single cask, while Repology needs all of them in a single file.

**Comment by kingthorin** [comment]
So this is whats needed?
https://formulae.brew.sh/api/cask.json

**Comment by AMDmi3** [comment]
Looks close. But it lacks usable package names, like ones in the left column of https://formulae.brew.sh/cask/

**Comment by kingthorin** [comment]
Ok thanks @AMDmi3

**Comment by luzpaz** [comment]
@AMDmi3 Please checkout 
https://github.com/Homebrew/homebrew-cask/issues/65978 and https://github.com/Homebrew/brew/pull/6289

**Comment by AMDmi3** [comment]
Please ping me when it's live.

**Comment by luzpaz** [comment]
@AMDmi3 it should be live in https://formulae.brew.sh/api/formula.json (see the `token` name with the application name as the value)

**Comment by kingthorin** [comment]
> @AMDmi3 it should be live in https://formulae.brew.sh/api/formula.json (see the `token` name with the application name as the value)

Sadly there only seems to be 15 occurrences of `token` in that json and most of those in description type strings.

**Comment by reitermarkus** [comment]
https://formulae.brew.sh/api/cask.json is the URL for casks.

**Comment by kingthorin** [comment]
That makes more sense, ~3500 occurrences of `token` in that which does appear to be the field name for the package names.

**Comment by luzpaz** [comment]
oops, my bad, i didn't link the right link

**Comment by AMDmi3** [comment]
Also I forgot to ask, what are comma-separated versions there? As in

```
      "token" : "clion",
      "version" : "2019.1.4,191.7479.33",
```

**Comment by reitermarkus** [comment]
We use the version to generate the download URLs, so they sometimes contain the version and other stuff like the build number.

**Comment by AMDmi3** [comment]
Oh, I should've looked inside the cask source. This is pretty cool actually, I haven't seen feature like that in other repos, while it conveniently allows to separate official version from less meaningful build numbers and stuff. However it looks like it needs to be used in more casks.

FYI the format is good now. I'm currently working on rules which would eliminate clashes with other repos and allow enabling casks on the site.

- As with other repos with non-crossplatform and/or non-opensource software, I'm just removing packages with name clashes for now.
- Likewise, packages unique to casks are hidden from the search.
- I've had to ignore versions with `-` in them, all cases I've seen so far are build numbers not present in other repos. It would be nice if comma feature could be used for these. Is it possible?
- Apart from that there are one or two cases of incorrect versions and a bunch of cases with different version schema for macos (some could be also fixed by comma), also ignored.

Otherwise it looks good, I think I'll deploy it this week.

**Comment by kingthorin** [comment]
Thanks for sticking with us on this @Amdmi3. I think it’ll be a great addition.

**Comment by reitermarkus** [comment]
> It would be nice if comma feature could be used for these.

It's not a “comma feature”, the comma is just one of the separators we use. If, e.g., the URL already contains a `-` the cask is easier to maintain if the version also already contains the `-`.

**Comment by reitermarkus** [comment]
Also see https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md for details.

**Comment by AMDmi3** [comment]
Oh, so it's even more flexible. Anyway, expect inaccurate results as long as the build numbers cannot be split from the official versions.

**Comment by AMDmi3** [comment]
It's live.

**Comment by TheLastProject** [comment]
I don't know if comments of this type are appreciated here but I just wanted to say it seems to work great, thank you!
