### ISSUE TITLE
How add more repositories for AzPainter?

### ISSUE THREAD

**Issue by Symbian9** [repology/repology#314]
I know some additional repositories for AzPainter, that not yet listed on Repology page

* https://repology.org/metapackage/azpainter/versions

So, how add them on this page?

REFERENCE:
* https://github.com/Symbian9/azpainter/issues/4
* https://www.linux.org.ru/forum/multimedia/13223232

**Comment by AMDmi3** [comment]
Regarding SliTaz and Void, these are not supported yet (see #166). Regarding others, Repology does not track neither standalone packages nor personal repositories, only official ones. As AzPainter packages are added to more official repos, they will show up in Repology.
