### ISSUE TITLE
KaOS

### ISSUE THREAD

**Issue by ShalokShalom** [repology/repology#323]
How to add these three repositories?:

https://github.com/KaOSx/apps
https://github.com/KaOSx/core
https://github.com/KaOSx/main

**Comment by AMDmi3** [comment]
If there is regularly updated machine readable compilation of data (package name, version, desc, url, license, downloads) somewhere, it may be used right away. Otherwise, this will have to wait for #166.

**Comment by ShalokShalom** [comment]
Does this work? http://kaosx.tk/packages/

**Comment by AMDmi3** [comment]
Maybe, though it seem to be outdated and info is incomplete (only names and versions).

**Comment by ShalokShalom** [comment]
What did you see outdated? The rest of the information is in the PKGBUILD, which is also available via the Github link, that i send you before. 

Plus, i see all the mentioned information here as well: http://kaosx.tk/packages/index.php?act=show&subdir=apps&sortby=name&file=0ad-a22-1-x86_64.pkg.tar.xz

**Comment by AMDmi3** [comment]
> What did you see outdated?

Some package I've randomly checked was of older version than in the repo, not sure what it was. But judjung by dates on the site, packages seem to be updated timely, maybe there's just some lag.

> The rest of the information is in the PKGBUILD, which is also available via the Github link, that i send you before.

As I've said before, it cannot be parsed as of now.

> Plus, i see all the mentioned information here as well

It's not practical to scrape whole site on each update.

Anyway it seems viable. The code is ready, I'll just add some rules and deploy this.

**Comment by ShalokShalom** [comment]
the name of the maintainer is demm (demm@kaosx.us)

**Comment by ShalokShalom** [comment]
Some packages use another version semantic, see 0ad and Blender: 
https://repology.org/metapackages/outdated-by-maintainer/demm%40kaosx.us/

**Comment by ShalokShalom** [comment]
Thanks a lot for this service, its quite nice to see on one view, which packages are up-to-date and which oens not. ^.^

**Comment by AMDmi3** [comment]
> 0ad, 0ad-data

Version transformations (#14) should help with that, so all version patterns could be converted to the same format.

> Android-tools, Dolphin-Emu

There are fake versions in other distros which should be ignored. I'm on that.

> Blender

That one is mangled in KaOS itself. Repology does not tolerate that, and converting letter into number doesn't seem to be fixable with regexp, so I suggest to fix versioning in the repo. It was mentioned in our IRC talk that pacman doesn't like letters, but using `2.78.c` like arch does should be OK.
