### ISSUE TITLE
Add OBS Support

### ISSUE THREAD

**Issue by wonko21** [repology/repology#329]
The Open Build Service [1] is a great tool to package for many different distributions.
The pulic instance at build.opensuse.org not only holds all the package builds for opensuse but there are tons of projects/private repos there with a myriad of packages.
maybe the search at software.opensuse.org or its source [2] can be used to gather the package information. alternatively the mirrorbrain could be convinced to push metadate to repology.

[1] http://openbuildservice.org/
[2] https://github.com/openSUSE/software-o-o

**Comment by AMDmi3** [comment]
The repology policy is to stick with official repositories, which have at least minimal quality policies, review procedures and do not depend on a single maintainer. Though if there are OBS repositories which meet these requirements they may be considered.
