### ISSUE TITLE
Gentoo needs more package splits

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#33]
Need to be split: btf (dev-java and sci-libs)

Actually, a lot more:

```
find gentoo.git -type d -maxdepth 2 -mindepth 2 |
   egrep -v 'dev-(perl|python|haskell)' |
   awk -F/ '{print $NF}' |
   sort | uniq -d
```

ace acl ada amap analog apel atlas attica auctex baloo balsa barcode bbdb bfm binclock bluedevil bson btf build c-support calc calendar cdcover cdrtools charm checkpassword coffee-script color crystal csv daemontools dash dictionary dirdiff docker dolphin ebuild-mode ecb eject elib emacs ess exo fam fcgi ffmpeg fuse gambit gdl git glade glu gnupg gnuplot gom gpgme grip gsasl haskell-mode highline icecream igrep info jack jal jama jde jpeg json kactivities kde-gtk-config kdeplasma-addons kdesu kfilemetadata kglobalaccel khotkeys kinfocenter kmenuedit knewstuff krunner kscreen kstart ksysguard kwin kwrited languagetool launchy lemon libelf libffi libgudev libiconv libintl libkscreen libnet libusb locale lookup lzma magic mailcrypt mailx man mars mash mavros mc mediawiki mew milou mime-types mldonkey mmix mmm-mode modutils mongo mpack mpc msgpack muse mysql nagios nemesis ninja nitrogen notification-daemon nut ocaml openmsx otter pam par pcl pdv picard pkgconfig planner plasma-mediacenter plasma-nm plasma-workspace pmake pms polkit-kde-agent polyglot powerdevil psgml psi python-mode rails re2 redis reduce riece ruby rubygems screen session shadow signify silo ski skkserv slim slurm smack sml-mode snappy spice spin splat splice sqlite3 ssh surf systemsettings szip teco texinfo tf time tokyocabinet tornado tree uclibc udev vc vm w3m xclip xslide xsp yacc zenburn zenirc

**Comment by alexws54tk** [comment]
Предлагаю разрулить это в ручную.
По крайней мере КДЕшные пакеты находятся в нескольких категориях в связи с наличием КДЕ4 и КДЕ Плазма 5.

И ещё. Почему перл, питон и хаскель исключены, а, например, джава нет? Вот `virtual` точно надо исключать. Категории не просто так же в Генте появились.

**Comment by AMDmi3** [comment]
> Предлагаю разрулить это в ручную.

Of course. There's no other way known.

> И ещё. Почему перл, питон и хаскель исключены, а, например, джава нет?

They are not excluded, they are mapped into ```perl:*```, ```python:*``` and ```haskell:*``` as there are apparent patters for perl/python/haskell modules in all repos like ```dev-perl/*```, ```p5-*``` or ```lib*-perl```. This is not the case for java, also standalone java libraries are not that common as they tend to just bundle jars.

> Вот virtual точно надо исключать. Категории не просто так же в Генте появились.

Nice catch.

**Comment by alexws54tk** [comment]
I can try to undertake Gentoo «support». But at me it is rather bad with the Python.

**Comment by AMDmi3** [comment]
No probs, this is my very first Python project either.

**Comment by jonasstein** [comment]
What do you want to get with the find? Do you need a list with all packages? Or all ebuilds?

**Comment by AMDmi3** [comment]
A list of packages. It's shown in the issue.

**Comment by AMDmi3** [comment]
Moved to https://github.com/repology/repology-rules/issues/11
