### ISSUE TITLE
Add support for UnitedRPMs

### ISSUE THREAD

**Issue by kuboosoft** [repology/repology#330]
[UnitedRPMs](https://unitedrpms.github.io) is a young project with rich packages for Fedora, if repology can adds [unitedrpms](https://github.com/UnitedRPMs), the people can find [updates and new packages](https://unitedrpms.sourceforge.io/x86_64/repoview/) for all... Thanks.

**Comment by kuboosoft** [comment]
Thanks @AMDmi3 !!

**Comment by luzpaz** [comment]
How does repology unlist unmaintained UnitedRPM packages ?
See https://github.com/UnitedRPMs/issues/issues/26

Ex. [flameshot](https://repology.org/metapackage/flameshot/versions) has been unmaintained and removed from the repository AFAICT. Why is it still showing up in repology ?

**Comment by AMDmi3** [comment]
It's not in unitedrpms fedora 29, is it? Or should it disapppear from older versions too? Anyway, repology just conveys data it gets from the repos. If the package is there, it's shown. If it's not it's not.
