### ISSUE TITLE
Low-contrast text (devel/legacy versions) is difficult to read

### ISSUE THREAD

**Issue by l2dy** [repology/repology#336]

**Comment by AMDmi3** [comment]
You've probably meant devel/newest?

The idea was that the difference between these is not important enough to make it clearly visible. In order to make the colors more distinguishable I'll probably need to move unique into blue HUE.

**Comment by l2dy** [comment]
No, I meant that devel and legacy versions are displayed as white text with white background, making them difficult to read.

**Comment by AMDmi3** [comment]
Hm, have you refreshed properly? The page should reference static/repology.v3.css, and the named file should contain version-devel and version-legacy classes. However, this should never happen anyway.

**Comment by l2dy** [comment]
Clearing the cache fixed it.

**Comment by l2dy** [comment]
It still references https://repology.org/static/repology.v2.css though.

**Comment by AMDmi3** [comment]
Oops, I must've forgotten to reload the backend to pick up updated templates. Should be fixed globally now.
