### ISSUE TITLE
[poll] need opinions on ignored versions handling

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#338]
I'm interested in people opinion on handling of ignored versions in case when they are in between devel and stable branches. Here's an example: `2.2alpha1` (latest devel), `2.1.20170101` (ignored), `2.1` (newest stable). The question is what class should be assigned to `2.1.20170101`. Possible options are:

* Legacy. Like it's a continuation of devel branch
* Ignored. "Out of sight, out of mind" unambigous solution.
* Outdated. The idea here is that random snapshot is obsoleted by official newer alpha. I like that it does encourage garbage collecting snapshots, but I don't like that it uses some custom non-transparent logic, and it also misbehaves for case of far apart branches, e.g. `3.0beta2` should not really obsolete `2.0.20170101`. To fix it, additional version comparison machinery is needed.

**Comment by AMDmi3** [comment]
On the second thought,

* `2.2beta1` - `2.1.20170101` - `2.1`
* `3.0beta1` - `2.1.20170101` - `2.1`

are essentially different cases for both legacy and outdated cases. In the second case there's no way we can reliably assume the snapshot is a continuation of devel branch. Seems like we should go with ignored class. Opinions are still grestly appreciated.

**Comment by jrmarino** [comment]
i vote for "ignored" (in the case there are actual releases).  
In the case there are no releases being made, and the dates represent post-last-release commits, then it could be considered "dev".

**Comment by AMDmi3** [comment]
Ok, we're going "ignored" way. Actually, I still don't have a real life example for this (e.g. ignored versions between non-ignored ones).
