### ISSUE TITLE
Add Solus support

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#341]
See https://github.com/repology/repology/issues/1#issuecomment-331580296

**Comment by AMDmi3** [comment]
@ikeydoherty any news from Solus?

**Comment by AMDmi3** [comment]
@ikeydoherty any progress?

**Comment by CrackedCrafterz** [comment]
yeah that would be great

**Comment by AMDmi3** [comment]
Here's an elaborate documentation of what Repology expects: https://repology.org/addrepo.
Closing this issue, as there's nothing to do on Repology side until engaged parties publish data in suitable format.
