### ISSUE TITLE
kdiff3-qt

### ISSUE THREAD

**Issue by Symbian9** [repology/repology#344]
Why `kdiff3-qt` shown only in AUR repositary?
* [![Packaging status](https://repology.org/badge/vertical-allrepos/kdiff3-qt.svg)](https://repology.org/metapackage/kdiff3-qt)

It already presented in many other distros!

* https://packages.debian.org/search?keywords=kdiff3-qt
* https://packages.ubuntu.com/search?keywords=kdiff3-qt
* https://www.rpmfind.net/linux/rpm2html/search.php?query=kdiff3-qt
* (and many other distro has it)

**Comment by AMDmi3** [comment]
Because it is `kdiff3`, not `kdiff3-qt`. Merged AUR package as well.

**Comment by Symbian9** [comment]
> Because it is kdiff3 , not kdiff3-qt

But `kdiff3` and `kdiff3-qt` are two digfferent packages!
* https://packages.ubuntu.com/xenial/kdiff3
* https://packages.ubuntu.com/xenial/kdiff3-qt

**Comment by AMDmi3** [comment]
Repology does not care of package variants (-qt, -gtk2, -gtk3, -static etc.) and subpackages (-doc, -manpages, -dbginfo, -dev). It's the same project, that's all what is relevant. FYI, on debian/ubuntu `kdiff3` and `kdiff3-qt` both come form the single source package [kdiff3](https://packages.debian.org/unstable/source/kdiff3).
