### ISSUE TITLE
xorg driver, new rule proposal

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#354]
Hi Dmitry,
currently my xorg drivers have similar names to others, e.g.
```
xorg-xf86-input-keyboard
xorg-xf86-input-mouse
xorg-xf86-input-synaptics
xorg-xf86-video-scfb
xorg-xf86-video-vesa
```
I don't like these names and want to drop "xf86", to change them to:
```
xorg-input-keyboard
xorg-input-mouse
xorg-input-synaptics
xorg-video-scfb
xorg-video-vesa
```
Inspecting 82.global-xorgdrv.yaml, it seems (through inspection) that the current rule would not transform such a change.  Can we tweak that rule (probably adding "|xorg" in the name pattern) to handle this name change before I make it?

**Comment by jrmarino** [comment]
however, I could live with replacing xf86 with driver, e.g.
```
xorg-driver-input-keyboard
xorg-driver-input-mouse
xorg-driver-input-synaptics
xorg-driver-video-scfb
xorg-driver-video-vesa
```
Maybe I should do that instead since the rule already exists for that.

**Comment by jrmarino** [comment]
sorry, that rule is "x11-driver", not "xorg-driver".
I think I'd like to change the request to accept "xorg-driver" prefix.  that seems most logical to me.

**Comment by jrmarino** [comment]
maybe it's best to accept both "xorg-" and "xorg-driver-" prefixes.
The repology package is actually "xorg:input-keyboard" so it makes sense that "xorg-" would be supported.

**Comment by AMDmi3** [comment]
Is this sufficient?

**Comment by jrmarino** [comment]
yes, thank you!
