### ISSUE TITLE
freebsd/dports systematic hunspell mismatch (rules needed)

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#358]
FreeBSD Ports has two styles for hunspell naming:
   1. XX-hunspell (where XX is a language code)
   2. [language]/hunspell (e.g. polish/hunspell)

The hunspell ports of type 1 show as "unique" ports (e.g. https://repology.org/metapackages/in-repo/dports/?search=hunspell).   There should be a rule to transform XX-hunspell to "hunspell-XX" to match existing packages.

The hunspell ports of type 2 don't seem to show at all.  They would need individual rules I guess (e.g. english, german, french, polish, vietnamese, etc, etc).

I thought the same case would exist for aspell, but that seems okay. (https://repology.org/metapackages/in-repo/dports/?search=aspell)

**Comment by AMDmi3** [comment]
Moved to https://github.com/repology/repology-rules/issues/9
