### ISSUE TITLE
Add flathub/flatpak support

### ISSUE THREAD

**Issue by bluefox16** [repology/repology#363]
[Flathub](https://flathub.org) looks like it will become a major [flatpak](http://flatpak.org/) repository (flatpak even links to flathub on it's web page).

This will be usefull as it will be possible to compare the version in the distribution to the version in flathub and then decide what to install.

There are also repositories for kde and gnome, but these seem less important now.

**Comment by AMDmi3** [comment]
Not sure if I want to touch flatpack with a ten foot pole, as it is makes a mockery of packaging. Also their source format doesn't even have application name and version clearly defined, and their repository format is some binary I see no way of reading.

**Comment by bluefox16** [comment]
Thanks for replying 

> Not sure if I want to touch flatpack with a ten foot pole, as it is makes a mockery of packaging. 

Is it a specific problem with flatpak? I saw you made a commit to add snap that was disabled. Which is what i thought would be the next thing to ask (It would be very nice to search for a package both on flatpak and on snap).

I agree that nix is probably a better cross distro package manager at the moment, Although It does not have any sandboxing integrated as far as i know, But flatpak does use the exact versions of libraries the developer intended (which some Developers consider an advantage). And I hope in the future more sophisticated dependency management will be added to it (snap only recently added support for "base snaps", which are some sort of dependencies). Also Red hat is supporting this format and although i don’t have any statistics to back it up my impression is it is catching on more then snap.

> their source format doesn't even have application name and version clearly defined

The name of the app is defined as the last segment of the address, e.g com.company.App see [here](http://docs.flatpak.org/en/latest/introduction.html#identifiers) , I also checked it is this way on flathub.

The version is indeed not defined, looks like in some cases it is used like a channel in snap(e.g beta/stable) and in some case it is an actual version. I can make a feature request that the version will be added (which is good for flatpak in general, in case someone will want to pin to a specific version)

> their repository format is some binary I see no way of reading.

It’s possible to get the list of apps from the command line, there is also libflatpak that can probably be used.

**Comment by AMDmi3** [comment]
> Is it a specific problem with flatpak?

No, snap is basically the same thing. Adding it was probably just an experiment, it was never enabled and I don't remember testing it.

> But flatpak does use the exact versions of libraries the developer intended (which some Developers consider an advantage).

I consider it a permanent security problem at least, and the whole thing ineffective and meaningless idea, as long as we have conventional packaging. Except for proprietary software packaging, and that is what I also don't want to see in repology.

> It’s possible to get the list of apps from the command line, there is also libflatpak that can probably be used.

There are already some external libraries used for specific uncommon formats and it's enough maintenance burden. I'd prefer to not

**Comment by pedrolcl** [comment]
> I consider it a permanent security problem at least, and the whole thing ineffective and meaningless idea, as long as we have conventional packaging. Except for proprietary software packaging, and that is what I also don't want to see in repology.

I am a free software developer, and a repology.org user. When looking to the repology.org results for my projects, it is clear that the conventional packaging has demonstrated to be ineffective and frustrating for both the users and the developers. I hate app stores, but flatpak/appimage and other formats are here to patch a defect that plagues free software, and I welcome them.

**Comment by dotlambda** [comment]
While I agree with @AMDmi3's stance that Flatpak is a flawed packaging solution and a security risk, I would value seeing what versions of the packages I maintain are on Flathub, especially given that they are usually uploaded by upstream developers. It would help with keeping packages up to date and therefore with one of the problems developers like @pedrolcl have with conventional packaging.

**Comment by AMDmi3** [comment]
Repeating myself, neither of 3 major blob distribution systems publish usable package metadata. Flatpak, judging from the recipe format, does not even have any notion of project and dependency versions. Having usable data is a prerequisite for any further discussion.
