### ISSUE TITLE
[feature request] Kali linux packages

### ISSUE THREAD

**Issue by samueloph** [repology/repology#369]
That would make it easier to visualize the differences between kali and debian.

If i get time, i will prepare a PR for this, but please feel free to do it before me.

**Comment by blshkv** [comment]
I raised a similar request in the issue https://github.com/repology/repology/issues/213

We can make it more generic, distro independant request.

**Comment by AMDmi3** [comment]
There seem to be a lot of distributions: http://http.kali.org/kali/dists/, which ones are worth adding?

**Comment by samueloph** [comment]
@AMDmi3 the kali-rolling is the one we would want to track, it's the main/only release on default installations. The other ones may be used for development purposes, i'm not so close to Kali linux dev so i can't be sure.

**Comment by AMDmi3** [comment]
Ok, this is in progress.

**Comment by AMDmi3** [comment]
I've added `kali-rolling` for now. Other repos may be useful as well, I'm awaiting feedback from Kali devs.

- `kali-rolling-only` - it seems like unlike `kali-rolling` it should contain Kali specific packages without packages from Debian, so it may be useful for Kali devs as well. However this repo is empty.
- `kali-dev`, `kali-dev-only` - these are unstable, but are still useful for both repology (as a source of fresh package versions) and probably Kali devs
- `kali-experimental` - this only contained 1 package, not sure if this is useful
