### ISSUE TITLE
Also track the most important ppas.

### ISSUE THREAD

**Issue by KOLANICH** [repology/repology#388]
Some software (especially drivers) for Ubuntu has the latest (usually nightly ones) versions not in the main repo but in ppas. I guess they should be also tracked.

**Comment by AMDmi3** [comment]
A list of most important ppas would be really useful.

**Comment by KOLANICH** [comment]
I guess at least
paulo-miguel-dias/mesa
oibaf/graphics-drivers
commendsarnex/winedri3

**Comment by AMDmi3** [comment]
Sorry, none of these are useful to repology - they they contain too little packages, versions are often mangled with git date garbage, some are even outdated. Besides, PPA usage should be discouraged.
