### ISSUE TITLE
Consider using scancode for package license scan

### ISSUE THREAD

**Issue by pombredanne** [repology/repology#389]
Dmitry:
I am the maintainer of the [scancode-toolkit](https://github.com/nexB/scancode-toolkit) which is a reasonably decent license scanner used for instance by in openshift [analytics](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/e850ced830512b7a8f1592568994fb31b0209a0d/f8a_worker/workers/license.py#L2),  to cleanup licenses in the [kernel](https://marc.info/?l=linux-kernel&m=150963579219623&w=2), by the [Eclipse foundation](https://bugs.eclipse.org/bugs/show_bug.cgi?id=499950#c12) and Here [maps](https://github.com/heremaps/oss-review-toolkit/blob/429e2e4c2cab694debd240e4ec75b0a8b3157854/scanner/src/main/kotlin/scanners/ScanCode.kt)

While browsing the Fossology history I saw you were helping there a [bit](https://github.com/fossology/fossology/commits?author=AMDmi3) so I assume may be wrongly that you have some interest in license detection. 

So I thought you might be interested by a modern, Python-based alternative to Fossology for repology.
I'd be happy to help!

--
Philippe

**Comment by AMDmi3** [comment]
That activity was not related to repology. Since I'm also FreeBSD ports collection developer I've used nomos license scanner from fossology to help me fill license information all over ports collection. Repology itself does not work with any souce code so it can't make use of such scanner. But I'll check it out for my FreeBSD work, thank you for suggestion!

**Comment by pombredanne** [comment]
ack. ping me if you need any help there. And id' be happy to help with the FreeBSD port (which should be most recompiling a few native libraries and .so for well known, portable libraries)

**Comment by pombredanne** [comment]
FWIW, scancode is supposed to be more accurate and more actively maintained than nomos. At least based on my comparisons and looking at the git logs.
