### ISSUE TITLE
Add crates.io

### ISSUE THREAD

**Issue by aleksander** [repology/repology#390]
Add repo for Rust programming language packages located at crates.io

**Comment by AMDmi3** [comment]
Looks doable by iterating through `https://crates.io/api/v1/crates?page=1&per_page=100&sort=alpha` 
- 100 is the maximum allowable number of entries to retrieve
- it conveniently outputs json
- it also outputs a total number of packages so we know how many pages to fetch (though we can also look for empty output)
- data usable:
  - name
  - version
  - description (may be long)
  - homepage (`homepage` and `repository` fields)

@alexcrichton, @carols10cents crates.io guys, is it OK for repology.org to retrieving all crates.io packages by packs of 100 hourly?

**Comment by alexcrichton** [comment]
Certainly!

**Comment by AMDmi3** [comment]
Done
