### ISSUE TITLE
still not possible to list only "ignored' packages in a repo?

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#405]
Previously it wasn't possible to get a list of a repo's "ignored' packages.
I had assumed with the advance search upgrade, this could now be done, but I can't seem to figure out how to do it.

A) Is it possible to see which 9 packages of Ravenports are "ignored"?
B) if not, can this be added as a feature request for searching?

**Comment by AMDmi3** [comment]
This is not possible yet. This is not hard to implement technically, however there are two ways to do this, by listing metapackages which have at least one ignored package in a specific repository, or by listing metapackage which only have ignored packages in specific repo.

The first approach would be useless for e.g. Gentoo, which have igored `9999` versions for a majority of metapackages. The latter would miss some metapackages which have older valid versions.

The correct solution seem to require introducing multiple types of `ignored` packages, such as
- ones which deliberately track upstream master/trunk (require no attention)
- fake versions (need fixing)
- snapshot versions (may or may not need fixing)
- random versions where upstream does not have clear versioning scheme

For the purpose of this issue we only need to differentiate the first class.

**Comment by AMDmi3** [comment]
There's now problematic condition for search. That lists `ignored`, `incorrect` and `untrusted` packages.
