### ISSUE TITLE
blackarch linux: version abuse

### ISSUE THREAD

**Issue by blshkv** [repology/repology#408]
blackarch linux came up with their own unreleased officially version numbering.

Here is few examples:

https://github.com/BlackArch/blackarch/blob/master/packages/dnsrecon/PKGBUILD
pkgname='dnsrecon'
pkgver=0.8.12

https://github.com/BlackArch/blackarch/blob/master/packages/smtp-fuzz/PKGBUILD
pkgname='smtp-fuzz'
pkgver='1.0'

https://github.com/BlackArch/blackarch/blob/master/packages/snmpenum/PKGBUILD
pkgname='snmpenum'
pkgver='1.7'

may be others.

**Comment by AMDmi3** [comment]
Only the first entry is valid, while smtp-fuzz and snmpenum do not have versions at all and there's nothing could be done for them other than ignoring all versions. Fixing dnsrecon requires some prior work.

**Comment by blshkv** [comment]
I can't find dnsrecon tar ball. Let's see what upstream has to say. I file a request here:
https://github.com/darkoperator/dnsrecon/issues/73
