### ISSUE TITLE
priority of _p and _pre

### ISSUE THREAD

**Issue by blshkv** [repology/repology#410]
sorry, but I'm still confused and  think this is not fixed properly.

I would expect the following order:
_alpha -> _beta -> release -> _p (postpatch) _pre (pre-release, git)

https://repology.org/metapackages/?inrepo=gentoo_ovl_pentoo&outdated=1

However, this is not the case with libimobiledevice. It is listed as outdated but there is a newer _pre version:

1.2.1_pre20171208	1.2.0 1.2.0_p20170813 
vs
1.2.1git20171128.5

Could you clarify please?

**Comment by AMDmi3** [comment]
> I would expect the following order:
> _alpha -> _beta -> release -> _p (postpatch) _pre (pre-release, git)

`_p` is not `postpatch`. `_p` is essentially ambiguous, and may mean either `pre` (pre-release) and `patch` (post-release). It's treated as `pre` by default, while some metapackages do require it to be treated as `patch` (e.g. sudo). It's not supported yet, but it's doable.

You won't expect `pre` after release, it's always pre- as the name suggests.

Regarding `git`, it's essentially ambiguous as well, and unlike `p` it is **never** known where it's pre- or post- release, so it's always treated pre- by default. In fact, it should probably be always ignored.

**Comment by blshkv** [comment]
sorry, I wasn' clear in few aspects.

The official gentoo numerations is the following:
https://devmanual.gentoo.org/ebuild-writing/file-format/index.html

```
_alpha | Alpha release (earliest)
_beta | Beta release
_pre | Pre release
_rc | Release candidate
(no suffix) | Normal release
_p | Patch release
```
Please follow this logic, for gentoo (ebuild) packages.

In this particular case, 1.2.1 was NOT released yet, however it is specified in the ```configure.ac``` file.
So I have named is as ```1.2.1_pre<date_of_snapshot>```.
I presume is inline with Debian's ```1.2.1git<date_of_snapshot>```

**Comment by blshkv** [comment]
ok, let's close this bug in #345 favour's
