### ISSUE TITLE
ruby:mysql needs help

### ISSUE THREAD

**Issue by swills** [repology/repology#415]
The version in pkgsrc is a completely different code base than the one in other places:

https://repology.org/metapackage/ruby:mysql/versions

Also, this seems to mix up the "mysql" gem and the "mysql2" gem, which are 2 different things and have separate ports in FreeBSD.

**Comment by AMDmi3** [comment]
This reveals a big bug in the ruleset order - packages named `mysql[0-9]+` are first processed by mysql-related rules, and merged into `mysql`, and that include gentoo packages from ruby-dev category, which are esentially ruby gems. Then ruby rules come in action and add ruby: prefix, but mysql/mysql2 arr already messed up.

Careful reordering of rulesets is required here.

**Comment by AMDmi3** [comment]
As expected, this was fixed by ruleset refactoring along with a lot of other similar problems.
