### ISSUE TITLE
Not possible to embed image due to Access-Control-Allow-Origin missing header

### ISSUE THREAD

**Issue by samm-git** [repology/repology#417]
Hi. I am trying to use badges on the website (smartmontools.org) but found that i am not able to do this due to missing "Access-Control-Allow-Origin" header. 

Firefox silently not rendering image and Chrome warns 

> Access to Image at 'https://repology.org/badge/version-for-repo/altsisyphus/smartmontools.svg' from origin 'https://www.smartmontools.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.smartmontools.org' is therefore not allowed access.

Is it possible to add `Access-Control-Allow-Origin: *` to the web server headers for badges?

**Comment by AMDmi3** [comment]
Are you trying to use something which is not `<img>` to embed the badge?

**Comment by samm-git** [comment]
@AMDmi3 yes, using <img> tag. See https://www.smartmontools.org/wiki/Packages?version=71, img is in the top of the page. Could you please give me such site example, it is interesting for me to find the reason.

**Comment by samm-git** [comment]
@AMDmi3 found this. Wiki adds `crossorigin="anonymous"` by default. I can fix this but i think adding such header will still do a good job :)

**Comment by AMDmi3** [comment]
Probably yes, I think I'll add it to the whole site as there's no private info here yet. Could you please check if it works now with crossorigin attribute? Would also be nice if you make badges link back to repology :)

**Comment by samm-git** [comment]
Yes, will add link to Repology, for sure. Its been a lot of pain to maintain this page up to date, so your project will help significantly :)

Tested now with cross origin attribute, works as expected, thank you again!

**Comment by AMDmi3** [comment]
Great, thank you!
