### ISSUE TITLE
Something wrong with a calculate linux listing

### ISSUE THREAD

**Issue by samm-git** [repology/repology#418]
It seems that calculate linux support is not working as expected.

Smartmontools and gsmartcontrol calculate linux ports are not listed on repology  but are available on the web site, see:

- http://www.calculate-linux.org/packages/sys-apps/smartmontools 
- http://www.calculate-linux.org/packages/sys-apps/gsmartcontrol

**Comment by samm-git** [comment]
P.S. to not create another report - is it possible to create badges w/o text but with numbers only? Should be handy for my case where we listing > package per row

**Comment by AMDmi3** [comment]
> It seems that calculate linux support is not working as expected.

It is working as expected. Calculate uses gentoo portage with a small own overlay - repology only includes the latter and does not duplicate Gentoo repository.

> P.S. to not create another report

Please create separate issue - that's what they are for.

**Comment by samm-git** [comment]
Thank you for the explanation
