### ISSUE TITLE
Rubygems repo should be canonical

### ISSUE THREAD

**Issue by swills** [repology/repology#424]
Perhaps related to #415. The Rubygems repo should be considered canonical, nothing in other repos should ever be considered newer than anything in it. See:

https://repology.org/metapackages/?inrepo=rubygems&outdated=1

**Comment by AMDmi3** [comment]
No it shouldn't. Nothing makes it special.

**Comment by swills** [comment]
The vast majority of the things shown as "outdated" in Rubygems are incorrect. I can't find any that are right now that I look.

**Comment by AMDmi3** [comment]
I've just clicked a random metapackage, [ruby:htree](https://repology.org/metapackage/ruby:htree/versions), it's 0.7.0 in rubygems, while homepage mentions 0.8 and there's corresponding tag on github. Every metapage which is "incorrect" should be dealt with individually.
