### ISSUE TITLE
AUR packages incorrectly flagged as out of date

### ISSUE THREAD

**Issue by saildata** [repology/repology#426]
Many of the [AUR packages](https://repology.org/metapackages/?inrepo=aur&outdated=1) on repology are incorrectly flagged as out of date when they are actually [VCS](https://wiki.archlinux.org/index.php/VCS_package_guidelines) packages that follow the upstream source (e.g. GitHub) instead of AUR or other versioning.

These packages should be listed as up to date since any user installing from one of these packages is going to get the latest source from the source repository.

This is addressed specifically in the [Arch Wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#Foo_in_the_AUR_is_outdated.3B_what_do_I_do.3F) on the page discussing the AUR and guidelines:

**> Note: VCS packages are not considered out of date when the pkgver changes, so please do not flag them as the maintainer will merely unflag the package and ignore you. AUR maintainers should not commit mere pkgver bumps.**

Thanks for all the hard work on this project. Cheers --

**Comment by AMDmi3** [comment]
If there's no way to identify these packages there's nothing which can be done about this.

**Comment by saildata** [comment]
There is a very easy way to identify these packages. They usually have the name ending in `git`.
Also, there are very clear standards for the naming that determines what the last part of the package string will look like. 

![aur_versions](https://user-images.githubusercontent.com/11636184/34552957-5607167c-f0ea-11e7-9ac9-15b4e4a01a1d.png)
If you look through the AUR packages on your site, you'll see what I mean. I've included a screenshot here to show how **the very first package** on the outdated list is actually fine because it's a git package.

On your site, the package name also indicates that the package name is `2bwm-git`, while every other one on there is just `2bwm-git`. The version string at the end of the package gives away that it's a git version, which would allow you to really just copy the `sed` / `regex` from the Arch Wiki page for [VCS Guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function).

**Comment by AMDmi3** [comment]
"Usually" won't go, we need strict rules. In general, this can be solved after #420 is implemented. But I'd prefer to be sure that no `-(git|hg|svn)` package has commit hash/revision defined or there's a way to identify these.

**Comment by saildata** [comment]
> "Usually" won't go, we need strict rules. In general, this can be solved after #420 is implemented. 
  
I say *usually* because these names are generated by people, not computers. I can't predict if/when a person will deviate from an accepted naming convention. Usually any name that deviates is both rate and caught by the community fairly quickly. 
  
The VCS wiki page listed does mention that the "r" in the package name is very important for indicating revision. 
    
> But I'd prefer to be sure that no -(git|hg|svn) package has commit hash/revision defined or there's a way to identify these.
  
I mentioned this above, but in the Arch Wiki page for [VCS Guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines) the note, `Include the appropriate VCS tool in makedepends=() (cvs, subversion, git, ...).` so that anyone interested can do what you're trying to achieve: **identify these packages in a reliable way.** 

For example, the package [shaderc-git](https://aur.archlinux.org/packages/shaderc-git/) has:
- `git` in the last part of the name
- has `git` in the `makedepends()` function of the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=shaderc-git) for the project
- has `git *` in the `pkgver` (indicating that it is not a static version source)
All of these things can be identified from the predictable PKGBUILD URL `https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=` where `h=` is followed by the `pkgname`.

Hopefully you have more than enough information to parse these packages in a reliable way so that your site can present the most reliable and up to date information for your users. I know that the AUR is one of the most popular repositories of it's kind and that having the appropriate number of 'out of date' packages is a relevant metric to show as accurately as possible. (hence the reason for this issue/bug being posted here)
  
 I wish you and the project the best. Feel free to ask if you have any questions and I will keep an eye on updates so that I can recommend this project as a reliable source to others once this is updated. Cheers --

**Comment by AMDmi3** [comment]
Repology does not have access to makedepends(). Of what you've listed only package name suffix may be used. Hopefully that would be enough.

**Comment by saildata** [comment]
It appears to be in the [aur.yaml](https://github.com/repology/repology/blob/717a12e5cccc6d1a8e0e72ebdf395442d871155d/repos.d/arch/aur.yaml) file:

```yaml
    - desc: View PKGBUILD
      url: 'https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h={name}'
```
  
Using [mpv-build-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mpv-build-git) as an example:
```sh
pkgver() {
  cd mpv
  echo "$(git describe --long --tags | tr - .)"
}
```
  
The `pkgver()` function (field) can be parsed, looking for `git describe` or `git rev`. That would only cover git, which is by far the most popular (AFAIK) on the AUR, but there is also Subversion, Mercurial and Bazaar.

Finally, there is a fallback of using `date +%Y%m%d` as a version string.

**Comment by AMDmi3** [comment]
- We can't parse PKGBUILDS. These are way far from being machine readable format (see #166), besides there's no easy way to retrieve them since there seem to be a separate repo for each package.
- We can't rely on pkgver and depends this way since git may be used to describe version even if fixed tag or commit is fetched

**Comment by saildata** [comment]
Yes, there is a separate repo for each package.

I was hoping for more accurate information, especially around the "outdated" parameter, which will be unreliable for the AUR without this. 

Thanks for your help, and good luck with your project.

**Comment by AMDmi3** [comment]
No, this will be fixed. I'm just telling it's not as simple as it may look.

**Comment by saildata** [comment]
Right, I completely understand and apologize if it came across that way.

**Comment by AMDmi3** [comment]
AUR `(.*)-(cvs|svn|hg|darcs|bzr|git)` are now Rolling state, which makes them not a subject for version comparison, e.g. even if there's greater version available, they will stay Rolling.

**Comment by saildata** [comment]
Thanks for your work on this. It looks like a lot of them have been cleaned up, but doing a simple "control-f", to find "git", on the repology page, filtering for [outdated AUR packages](https://repology.org/metapackages/?inrepo=aur&outdated=1) has a few false positives.

The first one I saw was for the `amule-git` package. Looking over the [PKGBUILD file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=amule-git) on the AUR, it builds the latest, but you have flagged it as out of date, which is wrong.

**Comment by AMDmi3** [comment]
`amule-git` is not outdated, as can be seen on https://repology.org/metapackage/amule/versions page. `amule-daemon` is.

**Comment by saildata** [comment]
Ok, I understand. It's not outdated, but from the legend on the first page, it's "ignored". `version is ignored and excluded from comparison for some other reason (e.g. snapshots).` Maybe that wording should be updated (added explanation) since the git version will not be a snapshot, but the latest commit.

**Comment by AMDmi3** [comment]
It's not `ignored`, it's `rolling`.
