### ISSUE TITLE
Search Debtags from Repology

### ISSUE THREAD

**Issue by sjackman** [repology/repology#428]
Is it possible to search Debtags from Repology?
See https://debtags.debian.org
and https://wiki.debian.org/Debtags
e.g. https://repology.org/metapackages/?category=bioinformatics
and https://debtags.debian.org/search/?q=bioinformatics

**Comment by AMDmi3** [comment]
Unfortunately, no. Because it uses binary packages, while repology uses source packages. And repology lacks facilities for enriching packages with third party data.

**Comment by sjackman** [comment]
Okay. Thanks anyway, Dmitry. cc @ilovezfs

**Comment by ilovezfs** [comment]
It seems odd that Debtags doesn't also apply the tags to the corresponding source packages too.

**Comment by sjackman** [comment]
Would be useful, I agree. The tags are crowd-sourced from users. The source packages are maintained by developers. I guess there's a gap between the two systems. A debhelper (Debian developer) script could fetch the most recent tags and add them to the source package.

**Comment by sjackman** [comment]
@AMDmi3 My use case is that I'd like to discover all bioinformatics formulae in Homebrew.

**Comment by AMDmi3** [comment]
I can do a debian-> homebrew package name mapping manually for now if that would be helpful for you case. For the generic solution we'll need architectural changes I also plan to think over

**Comment by sjackman** [comment]
A Homebrew to Debian mapping would be useful. Thanks, Dmitry.

**Comment by AMDmi3** [comment]
https://pastebin.com/QGL2eBk6

3 columns:
- debian stable source package name
- repology metapackage name
- homebrew package name

note that Debian may map to Homebrew as many to many.

**Comment by sjackman** [comment]
Thanks, Dmitry.

**Comment by AMDmi3** [comment]
You're welcome. Is Debian _stable_ good enough?

For the note, #401 is related.

**Comment by sjackman** [comment]
Yes, Debian stable is good enough. Thanks.

**Comment by AMDmi3** [comment]
Nothing to do here.
