### ISSUE TITLE
Rule for you-get

### ISSUE THREAD

**Issue by sunpoet** [repology/repology#446]
Repology: https://repology.org/metapackage/you-get/versions
Upstream: https://you-get.org/
PyPI: https://pypi.python.org/pypi/you-get

0.4.1011 is the latest version.
2016.06.03 on Deepin seems to a different software (which is in sound category).

Thanks!

**Comment by AMDmi3** [comment]
Judging by the homepage it's the same software (https://repology.org/metapackage/you-get/packages), there's just some garbage used instead of official version.

**Comment by sunpoet** [comment]
Thanks!
