### ISSUE TITLE
Rule for python:leveldb

### ISSUE THREAD

**Issue by sunpoet** [repology/repology#447]
Repology: https://repology.org/metapackage/python:leveldb/versions
Upstream: https://pypi.python.org/pypi/leveldb

0.20 is the latest version.
0.193 (https://pypi.python.org/pypi/leveldb/0.193), 0svn44 and 0svn68 are bogus.

Thanks!

**Comment by sunpoet** [comment]
The new rule was added to ruby ruleset (rules.d/62.global-ruby.yaml), not python one (rules.d/70.global-python.yaml).

**Comment by AMDmi3** [comment]
Oops, thanks!

**Comment by sunpoet** [comment]
Thank you!
