### ISSUE TITLE
Rule needed for ruby:bcrypt-ruby

### ISSUE THREAD

**Issue by sunpoet** [repology/repology#449]
Repology: https://repology.org/metapackage/ruby:bcrypt-ruby/versions
Upstream: https://rubygems.org/gems/bcrypt-ruby

3.1.5 is the latest version.
3.1.11 on Funtoo and Gentoo is actually bcrypt (https://github.com/codahale/bcrypt-ruby 
 and https://rubygems.org/gems/bcrypt).

Thanks!

**Comment by AMDmi3** [comment]
Likely the same problem as in #415
