### ISSUE TITLE
Rule needed for ruby:cairo

### ISSUE THREAD

**Issue by sunpoet** [repology/repology#450]
Repology: https://repology.org/metapackage/ruby:cairo/versions
Upstream: https://rubygems.org/gems/cairo

1.5.11 is the latest version.
cairo-gobject on RubyGems has been added to the list and marked as the newest one.

Thanks!

**Comment by AMDmi3** [comment]
Likely the same problem as in #415

**Comment by AMDmi3** [comment]
As expected, this was fixed by ruleset refactoring along with a lot of other similar problems.
