### ISSUE TITLE
Cannot create directory 'testdata/arch.state/core/zlib-1:1.2.8-7' on Windows

### ISSUE THREAD

**Issue by AndreyMZ** [repology/repology#452]
Could you rename directory 'testdata/arch.state/core/zlib-1:1.2.8-7'? This name is not valid on Windows.
This prevents operating with this repository on Windows:
~~~
git.exe checkout -f --no-track -b upstream-master remotes/upstream/master --

fatal: cannot create directory at 'testdata/arch.state/core/zlib-1:1.2.8-7': Invalid argument
~~~

**Comment by AMDmi3** [comment]
Sorry, the test data should be the same it is in upstream repository. You could use git sparse checkout feature.
