### ISSUE TITLE
flagging freshcode.org mistakes also not viable

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#462]
Regarding freshcode tagging a commit v19.3 days before release (causing a false positive for wget), the report was rejected with a recommendation to fix upstream by "flagging" it.

With great difficulty, I finally managed to flag it.
As expected, there was no response.  Nothing changed.

The problem became "overcome by events" when v19.4 was released.  (and suddenly tarballs for both 19.3 and 19.4 appeared.  It's possible the main issue was upload-to-mirrors problem).

However, that's besides the point.
If freshcode is causing a problem, it's not viable to say "fix it upstream".  I tried it; it doesn't work.  Please don't continue to recommend interfacing with upstream data.   At least not with freshcode.  It seems mostly automated with few (one?) human involved.

**Comment by AMDmi3** [comment]
> As expected, there was no response. Nothing changed.

What did you expect to change? You were heard, but by the time you've submitted the flag wget 19.3 was released and the issue fixed itself. Besides, I was contacted by author of freshcode.club, and we've exchanged some ideas on how FCC can be improved.

Freshcode looks for new versions in upstream changelogs. I suggested to improve it by verifying a new versions against tags or releases which could usueally be done simply by grepping html page.

And again, reporting a new version before upstream is not a problem, but a great feature.

**Comment by jrmarino** [comment]
as I said, I expected in the very least, a response.
I never got one.  Even to say, "it's obe".
Plus the original problem of a phantom release getting reported was valid, so something was broken and needed to be fixed so it doesn't happen again.  Again, something worthy of a response.

My expectations are not unreasonable.   

And we will go opposed on this: 
Announcing a release before the authors of a project can do it themselves is a doucebag move.   Only a jerk (or set of jerks) think that is cool.  Somebody spends all the time and work on a release, only to have the honor of the release to be taken away, only without all the necessary notes that upstream would provide.  Maybe if you were the author of a widespread project and some tool kept announcing releases to the world before you were ready you'd have a different opinion on this "great feature".

**Comment by AMDmi3** [comment]
> Announcing a release before the authors of a project can do it themselves is a doucebag move

It's not announcing, it's notifying of an upcoming release. And the notification is based on a changelog entry created by the authors themselves.

>  Maybe if you were the author of a widespread project and some tool kept announcing releases to the world before you were ready you'd have a different opinion on this "great feature".

I could discuss that with an author of a widespread project.
