### ISSUE TITLE
Integrate the Scoop repository?

### ISSUE THREAD

**Issue by frou** [repology/repology#464]
Scoop is a package-manager/installer for Windows, that is more lightweight and focused on developer CLI tools than Chocolatey.

http://scoop.sh

Its packages are defined in JSON files here:
https://github.com/lukesampson/scoop/tree/master/bucket
https://github.com/lukesampson/scoop-extras

( cc @r15ch13 @lukesampson - Have you seen this great webapp? https://repology.org )

**Comment by AMDmi3** [comment]
Doable.

**Comment by frou** [comment]
Thank you @AMDmi3 , I appreciate it
