### ISSUE TITLE
Drop calling external utilities where possible

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#47]
wget -> python requests; gzip/bzip?

**Comment by alexws54tk** [comment]
Maybe [this](https://docs.python.org/3/library/archiving.html) info will help.

**Comment by AMDmi3** [comment]
I've already converted most of the code (mostly FileFetcher actually), the only place left is ArchDBFetcher which calls ```wget``` and ```tar```. Should rewrite that place to ```tarfile```.

**Comment by AMDmi3** [comment]
I've recently got rid of `wget`, however we still use `rsync`, `git` and `svn` (and most nasty macports' TCL script), and I don't think we can replace them. `tar` is also still used, transition to `tarfile` is tracked in #701.
