### ISSUE TITLE
Rule needed for perl:devel-leak

### ISSUE THREAD

**Issue by sunpoet** [repology/repology#483]
Repology: https://repology.org/metapackage/perl:devel-leak/versions
CPAN: http://search.cpan.org/dist/Devel-Leak/

0.03 is the latest version.
0.04 on pkgsrc is bogus.

**Comment by AMDmi3** [comment]
http://www.cpan.org/authors/id/S/SR/SREZIC/Devel-Leak-0.04.tar.gz
