### ISSUE TITLE
API question: how do I get the newest version of a metapackage?

### ISSUE THREAD

**Issue by ryantm** [repology/repology#489]
Hi!

Sorry if you don't use GitHub issues for questions, but I didn't see another contact method.

If I query for a metapackage, I get a list of all the repositories that package it and their version. Does the API provide a way to get the newest version for a particular metapackage? By "newest," I mean the one that repology.org colors green.

I've tried

```
wget "https://repology.org/api/v1/metapackage/2bwm?newest=on"
```

but it shows all the packages for that metapackage.

Thanks,
Ryan

**Comment by AMDmi3** [comment]
This is valid issue, package statuses should be exposed in API. As far as I remember there was some reasoning behind not doing so at start, maybe because there were just two statuses and the list of packages is sorted by version, but that's definitely no longer valid.

**Comment by AMDmi3** [comment]
Fixed.
