### ISSUE TITLE
HaikuPorts release branch before R1.

### ISSUE THREAD

**Issue by kallisti5** [repology/repology#493]
Hello! Haiku developer here.  Noticed repology was a *awesome* looking tool (which also points out how outdated some of our packages are :-))

We're still fumbling around trying to figure out how release branches will work, but i'll keep you updated via this ticket before R1 comes out on what the plans are.

**Comment by AMDmi3** [comment]
Thanks! Btw, I wanted to ask - are there going to be no more quarterly branches for HP? I've supported them before, but it seems that 2017Q4 was the last.

**Comment by AMDmi3** [comment]
Nothing is happening here, so closing.
