### ISSUE TITLE
Suggestion: tag packages installed by default in distros

### ISSUE THREAD

**Issue by waldyrious** [repology/repology#494]
A while ago I attempted to start a project called [unix-manifests](https://github.com/waldyrious/unix-manifests) where I'd collect the manifest files of various distros, with the goal of being able to query which packages are installed by default in which systems.

The effort kind of died off, but I still think the idea is worthwhile. The Repology project got me very excited because it already goes an incredibly long way toward collecting that kind of information. The idea would be to add support for marking (specific versions of) packages as included by default in (specific releases of) each distro associated to a given repository. This data could then enable end-use applications similar to http://fontfamily.io or http://caniuse.com.

Is this something desirable for Repology or should this idea be implemented as a separate project?

**Comment by AMDmi3** [comment]
Honestly I don't see any use for this information whatsoever, not to mention in Repology. How does a default set of packages matter if you can add any packages you may need at any moment? And that's what Repology is actually about.

Besides, implementation is also going to be really clumsy. We won't be able to support this data for all repositories anyway which makes it even less useful, and I particularly dislike partially working features. This will also require an additional set of parsers which increase maintainance burden with no apparent gain.

**Comment by waldyrious** [comment]
That's fair -- I opened this issue precisely to figure out whether this functionality would be considered in scope for this project, and it looks like you don't think it is, which I totally understand.

As for uses, I mentioned two existing projects that depend on this kind of information. "Safe" fonts across multiple systems is just one case, e.g. for websites that might want to implement a custom design without resorting to embedding fonts in the resources to be downloaded. Web authors can't depend on users installing fonts locally to have its design work out of the box. This is not merely an aesthetic issue, since including fonts to download impacts low-bandwidth users, and relying on incorrect assumptions about widely available fonts may make the interface unusable in some cases, due to different metrics.

Another use I can think of is for command-line instructions in Q&A sites like StackOverflow, installation/setup instructions in software projects' READMEs/wikis, examples in sites like CommandLineFu.com, tutorial blog posts, etc. It would be nice to be able to restrict the commands in such instructions to the "safe" subset that beginning users (who are the most likely to be looking for that kind of information) could run without tripping into additional issues due to those tools not being installed in their machines.

And of course, there could be many other users that simply don't occur to me at the moment. The point is that having the information available in a structured way would enable people to *come up* with such use cases that can't be predicted in advance.

But I'm not saying all this to convince you :) this is just for the record and because I clearly failed to convey the possible utility of this data in the first comment. Feel free to close this issue if you remain convinced that it's an orthogonal set of information to that intended to be collected in the Repology project.

**Comment by AMDmi3** [comment]
Well I don't think any of uses you've mentioned are related to default package sets - fontfamily.io is about font families and aliases, caniuse.com is about actual browser usage, and command line instructions should precisely be independent of installed package set.

I also don't think that relying on default package sets is a good idea for any possible use.

Well in any case it's not for Repology, but thanks for the idea.
