### ISSUE TITLE
zookeeper 3.4.11 is not a stable version according to upstream

### ISSUE THREAD

**Issue by ilovezfs** [repology/repology#495]
Please see https://issues.apache.org/jira/browse/ZOOKEEPER-2976?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16351507#comment-16351507

This now implies immediate action IMO, which is that 3.4.11 should be marked as ignore as upstream has intentionally not designated it as the latest stable, which continues to be 3.4.10.

**Comment by ilovezfs** [comment]
@AMDmi3 Thanks, Dmitry!

**Comment by ilovezfs** [comment]
@AMDmi3 are the effects on repology.org immediate? https://repology.org/metapackage/zookeeper/versions still looks the same post https://github.com/repology/repology/commit/62d0a7f4663cc9fa98f455c7482d7525315da7b5.

**Comment by AMDmi3** [comment]
No, it needs up to 4 hours to propagate, also I'm not sure I've deployed it. But it'll be in effect today.

**Comment by ilovezfs** [comment]
Ah, OK, cool. I thought maybe you had implemented instantaneous magic :crystal_ball: :)

**Comment by AMDmi3** [comment]
Unfortunately, not yet. But I have some ideas :)
