### ISSUE TITLE
Some more issues

### ISSUE THREAD

**Issue by jtojnar** [repology/repology#519]
* `system-config-printer` from OpenIndiana has wrong version
* `vala` 0.39 is development version (odd minor)
* `libgnome-games-support`  is devel (odd minor) and pre-release (patch ≥ 90)
* `gtksourceview2` [2.11.2](https://github.com/GNOME/gtksourceview/blame/gnome-3-0/NEWS#L104) is devel (it was the last non-pre-release version in 2.x)
* `gtksourceviewmm3` [3.21](https://github.com/GNOME/gtksourceviewmm/blob/a9f7365671823f6a8f8c318e75cc2979331575be/NEWS#L1) is also devel, though distributions are packaging it due to scarcity of stable releases
*  `goffice` 0.10.38 incorrectly marked as devel, not even sure why it is matched

**Comment by jtojnar** [comment]
* `gvfs` 1.35.91 is devel + pre-release
* `pango` 1.41 is devel
* `pangomm` 2.41 is devel

**Comment by AMDmi3** [comment]
goffice is devel because of wikidata (marked as beta there)
