### ISSUE TITLE
fio OpenIndiana Package source and Makefile link to the wrong place

### ISSUE THREAD

**Issue by sitsofe** [repology/repology#520]
Over on https://repology.org/metapackage/fio/packages the fio OpenIndiana packages box links to
* https://github.com/OpenIndiana/oi-userland/tree/oi/hipster/components/system/test/fio and
* https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/system/test/fio/Makefile

but both of those are 404. The correct links would be
* https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/sysutils/fio and
* https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/sysutils/fio/Makefile ...

**Comment by AMDmi3** [comment]
Yes, I've seen this problems. Turns out that OI package "paths" stored in metadata and paths in git repository are not the same thing, so we can't deduce URL from these. I'm disabling package links for OI, as there's no way to construct these paths with the data we have.
