### ISSUE TITLE
Nixpkgs `-unstable` normalization

### ISSUE THREAD

**Issue by jaens** [repology/repology#533]
Looks like nixpkgs could use a rule to strip the `-unstable` prefix from packages:
https://repology.org/metapackages/?search=-unstable&maintainer=&category=&inrepo=nix_unstable&notinrepo=&minspread=&maxspread=

**Comment by jaens** [comment]
Looks like this uses `ignore: true`, which I guess causes these packages to be hidden/removed? Some packages eg. `squashfuse` are available only in the `-unstable` form, so I guess ignoring them is not the best choice?

**Comment by AMDmi3** [comment]
No, it doesn't make them hidden/removed.

**Comment by jaens** [comment]
Ah, I see the `squashfuse` package for nixpkgs now, guess it took a while to update (looked for it immediately after this was merged...).

**Comment by AMDmi3** [comment]
It was there when I've checked it right after your post. It was never `remove`d, and `ignore` just excludes the version from comparison without hiding it, just making it not affect other versions status.
