### ISSUE TITLE
wikidata overload

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#556]
As an example:
https://repology.org/metapackage/npm/versions

There are over 100 wikidata entries for npm.  If this was a regular repository, there would be one entry: the latest version.

It seems to be that wikidata should have a filter/processor that limits to the latest entry.  
Am I alone in thinking that 100+ wikidata entries for a single package is unreasonable / unexpected?

**Comment by AMDmi3** [comment]
So what's the problem? Having information on more|most|all past versions is nice.

**Comment by jrmarino** [comment]
I don't find it nice, obviously.
One "problem" is consistency.  Every other repository shows one entry, and wikidata shows 100.  If anyone cared about past versions, they'd just go to wikidata.  You don't have to reproduce all of it's contents in repology.  It's completely redundant, and I'm still struggling to see a real-world use case.

I know you seem to have a love affair with wikidata, but from this user's vantage point, it's nothing but a PITA.  Note that the *rejected* json-glib report is now month old, and the problem caused by wiki-data still exists.  Nobody has fixed that regression.   The idea that repology users must contribute to wikidata failed.  I honestly couldn't fix wikidata's json-glib if I wanted to.  I have no idea what to change.

And for the record, I attempted to fix another wikidata entry to fix repology and it didn't work.  I changed something, but not the right thing (and the right thing was immutable).

I really wish you would soften your stance on wikidata.  It just sucks.

**Comment by AMDmi3** [comment]
> One "problem" is consistency.
> If anyone cared about past versions, they'd just go to wikidata.

You are missing both the point of _consistency_, which would be handling all sources equally and not throwing away useful data, and _aggregation_, which would be not having users go to the original source to get the data.

>  I have no idea what to change.

You have, I've pointed it out in https://github.com/repology/repology/issues/444#issuecomment-358350538. I'll say it again: https://www.wikidata.org/wiki/Q47270524 has invalid data on package names which should be fixed.

**Comment by jrmarino** [comment]
and the love affair continues.

wikidata has ruined repology.  I challenge you to find another user that actually uses it.
And since you're the one that is insisting on wikidata being the prime repository, you should take the responsibility to fix the bad wiki entries.  Since you obviously know what needs to be fixed, you should fix it (since you won't rightfully block it).

All I am going to do is count the months that json-glib is broken.  As each month clicks off, that only makes my point stronger.

**Comment by jrmarino** [comment]
I don't even understand your answer.  Obviously you treak wikidata differently, so that meets your definition of (in)consistency.  I don't get the reference to aggregation since I didn't talk about that.  It seems you are saying repology is now an aggregator??  very confused.
