### ISSUE TITLE
FLTK versions

### ISSUE THREAD

**Issue by kraileth** [repology/repology#569]
Repology currently shows FLTK version 2.0 as current and 1.x versions as outdated. This is incorrect.

FLTK has quite a history in being rather strange when it comes to versioning. Version 1.1.x superseded 1.0.x which is completely obsolete today. 1.1.10 was the last version of the 1.1.x branch and could be added as a legacy package (while it's officially unsupported, there's still quite a bit of software that uses it and as far as I know some developers for small or embedded devices prefer it over newer versions because it's so extremely light-weight).

Then 2.0 was started - but despite being highly anticipated by many it simply never happened. A developer once told me that it felt like that version was cursed. While an attempt to revive it was made later, there has never been an official release. Alpha versions were available, but that's it. According to Repology, PCLinuxOS offers FLTK 2.0.0. That's definitely wrong and most likely is an alpha release with an incurrect version number. A non-alpha 2.x FLTK version should be reported as a problem instead of a current package.

The 1.2 branch is irrelevant. For the 1.3 some features (like unicode support) of the never arrived 2.0 were ported back to the 1.10 API. Development has stopped but it is considered the stable branch with 1.3.4-2 being the most recent official release of FLTK.

3.x was an attempt to escape the rather poor versioning situation by taking 1.3 as a base and re-implementing the more modern API of 2.0 on it. This effort has unfortunately stalled.

Currently development is active on the 1.4 branch but it has not seen any release, yet.

**Comment by AMDmi3** [comment]
Thanks for detailed explanation, fixed as requested (1.1.10 legacy, 2.x ignored).
