### ISSUE TITLE
optional e-mail notification

### ISSUE THREAD

**Issue by davidak** [repology/repology#570]
As a maintainer i would like to receive e-mails when a package i maintain has a problem (like is out of date).

Could be an option in a profile i have on the site or just a page to sign up, like for a newsletter.

Maybe a RSS and Atom feed would also be useful for people that use them?

**Comment by AMDmi3** [comment]
I'd prefer to not mess with email in any way, at least on the current stage of development.
RSS feeds are planned (#31, #308) and we're slowly moving towards them by refactoring the backend towards incremental updates and implementing various history bits (#535).

**Comment by AMDmi3** [comment]
Feeds done
