### ISSUE TITLE
pkgsrc-2018Q1?

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#586]
The latest quarterly was released 5 april 2018: 
http://mail-index.netbsd.org/pkgsrc-users/2018/04/05/msg026461.html

1) If not already in work, pkgsrc-2018Q1 should be imported
2) What's the plan in general?  Last four quarterlies?  meaning pkgsrc-2017Q1 is going to be removed?

**Comment by AMDmi3** [comment]
I see no reason to remove old pkgsrc branches.

**Comment by jrmarino** [comment]
```
valid_till: 2018-08-01
```

4 months?
you mean 2019-04-01 ?

> I see no reason to remove old pkgsrc branches.

You remove lots of repositories when they get obsolete.  Why is pkgsrc special?  2017Q1 isn't updated anymore AFAIK.

**Comment by jrmarino** [comment]
maybe this is the official support policy:
https://www.perkin.org.uk/posts/pkgsrc-2014Q4-lts-signed-packages-and-more.html

**Comment by AMDmi3** [comment]
> 4 months?
> you mean 2019-04-01 ?

No, I've actually meant 2018-07-01 - 3 months, until the next quarterly branch. I haven't found any mentions on that it's supported for a year.

> maybe this is the official support policy:

Fixed expiry for 2017Q4.

**Comment by AMDmi3** [comment]
Thanks for clarifications, then the dates are correct.
