### ISSUE TITLE
Get newest/devel version from api/badge

### ISSUE THREAD

**Issue by concatime** [repology/repology#588]
Hi. Is it possible to get only the newest/devel version of a package without providing a repository? It would be really nice if there is an api and/or a badge for that.

**Comment by AMDmi3** [comment]
There's no badge for that yet, but sure I will do it. API already allows it, you just need to pick version with newest/devel status.

**Comment by concatime** [comment]
Can you please provide a link as an example? I was not able to find what you just described, at least not in repology.org/api nor in [`api.py`](//github.com/repology/repology/blob/master/repologyapp/views/api.py).
To be clear, what I want is something like this: If I request `https://repology.org/api/v1/metapackage/nginx/newest`, it would return `1.14.0`.

**Comment by AMDmi3** [comment]
That's overspecific, not sure if that needs to be in the API.

https://repology.org/api/v1/metapackage/nginx → iterate over packages and pick `version` with `status` = `newest` or `devel`. This allows you to pick the version the way you need, as there may be different notions of `newest`. Pick only `newest`, or both `newest` or `devel`, or give priority to either of them. Each may have more than one version (still compared equally), e.g. `1.0`, `1.0.0`, `1.0-0` etc.

**Comment by AMDmi3** [comment]
So how's this?

![](https://repology.org/badge/latest-versions/nginx.svg)

**Comment by concatime** [comment]
Sorry, I was busy this week. YES! That's awesome, thank you ;)
