### ISSUE TITLE
comparing time based version

### ISSUE THREAD

**Issue by davidak** [repology/repology#597]
The [version](https://repology.org/metapackage/bcachefs-tools/versions) in nixpkgs are actually newer than AUR, which was [last updated on 2017-09-06](https://aur.archlinux.org/packages/bcachefs-tools). Do you have that data and can use it to compare in such case?

![screenshot_2018-04-29_12-59-55](https://user-images.githubusercontent.com/91113/39405834-5255a1f6-4bad-11e8-8a3e-78fb94f17628.png)

Or should the metapackage be marked as one without release yet?

Also related the discussion in https://github.com/repology/repology/issues/345.

**Comment by AMDmi3** [comment]
No, there's no such data and it won't be useful anyway, as a repo may update to non-latest version. This one does not have an official versioning scheme and should be marked correspondingly.
