### ISSUE TITLE
Add support for Poky and meta-debian

### ISSUE THREAD

**Issue by guillemj** [repology/repology#603]
Recipes at:
poky: http://git.yoctoproject.org/cgit/cgit.cgi/poky
meta-debian: https://github.com/meta-debian/meta-debian/tree/master

**Comment by AMDmi3** [comment]
Need shell parser, so not usable anytime soon

**Comment by AMDmi3** [comment]
There will be no shell parser. I don't see any usable indexes and I hardly understand what these projects are about, so this doesn't seem suitable for Repology.

**Comment by septatrix** [comment]
There is an index provided by OpenEmbedded for most layers where one can download CSVs: https://layers.openembedded.org/layerindex/branch/master/layer/openembedded-core/. However, the url to upstream soucres, description etc. is not part of the CSV but instead can only be seen on the recipe page itself. I could open an issue upstream about providing JSONs additionaly which could contain that information if you are fine with the general idea of adding OpenEmbedded data.

Some of these layers are official layers by the OpenEmbedded project and some are by other people. This could be compared to Debian's main/contrib/PPA. Adding the sources for the official ones would make sense IMO.

**Comment by AMDmi3** [comment]
@septatrix Is this really related to poky / meta-debian?

**Comment by septatrix** [comment]
It is related to Poky but not meta-debian. Based on my understanding of the latter it is only a way to utilize debian packages inside the openembedded/yocto ecosystem when a native recipe is not available.

Poky is the reference distribution of the openembedded project and not a repository of its own. The underlying "repositories" or are the layers like openembedded-core which I linked above and which provide recipes from which the packages are build.

**Comment by AMDmi3** [comment]
Ok. Well, openembedded-core data looks mostly sane, but yes, it's incomplete - it would be nice to have all information which is available on the package page. Also not sure if supporting just openembedded-core would be enough, while I would prefer not to deal with hundreds of layers individually.
