### ISSUE TITLE
Add support for Cydia

### ISSUE THREAD

**Issue by guillemj** [repology/repology#605]
Recipes: http://svn.telesphoreo.org/trunk/data/

**Comment by AMDmi3** [comment]
What is this? What's its homepage? The repository doesn't seem to be directly usable as it contains source tarballs, a custom svn based fetcher would be needed. I'll gladly accept patches, but myself I don't see it's worth working on this now.

**Comment by AMDmi3** [comment]
It looks usable from the first glance, but need a way to download just a _medadata subdirectories without the distfiles.

**Comment by AMDmi3** [comment]
> but need a way to download just a _medadata subdirectories without the distfiles.

Which I currently don't see.
