### ISSUE TITLE
Invalid version for libmspack

### ISSUE THREAD

**Issue by kraileth** [repology/repology#606]
The Hyperbola repository claims to hold version 1.5 of libmspack and thus makes Repology think that's the current version. However the newest version currently available is 0.6alpa. The error very likely comes from the fact that the package cabextract is by the same author and offered on the same website - and cabextract had a released version 1.5.

**Comment by jrmarino** [comment]
This is better, but still not correct.
The current version really is "0.6alpha".  It's not an alpha version in the regular sense.  It's the name of the stable release.

https://www.cabextract.org.uk/libmspack/

please re-open / review.

**Comment by jrmarino** [comment]
To be clear, repology is showing "0.6" is the latest version, not "0.6alpha"
