### ISSUE TITLE
Wikidata missing packages

### ISSUE THREAD

**Issue by nemaniarjun** [repology/repology#614]
Can you help me understand how Wikidata data is scrapped and added to the pakages list?
For example how is it that [there is no `autopep8` in `wikidata` repository according to repology](https://repology.org/metapackage/autopep8/versions), but the [corresponding entity does exist in Wikidata.](https://www.wikidata.org/wiki/Q28941623)

**Comment by AMDmi3** [comment]
Repology requires `Arch package` (or `AUR package`) property to process Wikidata entries. It's needed for two purposes: first, it's a way to filter out cross-platform free software which can't be reliably done based on other properties (for instance, only `instance of` `software` is set for this one, which is too vague). Second, it's used to get package name. Entry label is not quite suitable for this purpose, as it contains human readable name which is usually different from how the package is named. And among `* package` properties, Arch is least ambiguous, and there's very high probability there's Arch or AUR package for any F/OSS project.

So if you set either (or better, all, which would also enrich Wikidata entry) `Arch package autopep8`, `Arch package python2-autopep8` `AUR package python-autopep8-git` for this entry, Repology will recognize it with the next update.

I have a couple of queries to find Wikidata entries with missing package data, see https://github.com/repology/repology/blob/master/repos.d/wikidata.yaml#L196, not sure if these will catch this case though.

**Comment by AMDmi3** [comment]
We have to choose one here, and I find Arch+AUR most suitable. Others may potentially be added as a fallback, but I see no reason to, as I haven't seen a case yet where Arch/AUR package could not be filled.

Complexity is an argument as well, as the more data SPARQL query collects the slower it is, and it may become too heavy for Wikidata to process eventually. I've already ran into query timeouts trying to get all available package data, you can see commented out lines:

https://github.com/repology/repology/blob/84f557be9c682c04c2f5e642eafb46b58d499237/repos.d/wikidata.yaml#L46-L51

**Comment by waldyrious** [comment]
Thanks for the explanation. That makes sense. I believe one fallback (two at most) would be a good middle ground, just to ensure the whole thing doesn't hinge on a single distro's ecosystem (no matter how large). I'd suggest Debian, but it's up to you :)

**Comment by AMDmi3** [comment]
Not sure what you mean by hinging on arch ecosystem. Repology will only be affected if Arch starts to remove packages massively for some reason, so they are removed from wikidata entries, so repology stops recognizing these entries. In that case we'll have to reconsider the primary source for names anyway. A fallback will only hide the problem, cause unwanted effects like wikidata entries suddenly changing names and make chosing the best alternative source harder.

**Comment by waldyrious** [comment]
I meant that all these repositories (arch, wikidata) are human-curated, so inevitably there will be gaps, especially in the connections between them, like the one pointed by the OP.

My hypothesis is that relying on arch alone for Repology's connection to Wikidata may produce false negatives that a fallback may help with.

Of course, we could keep adding fallbacks, but there'd be diminishing returns. I'm proposing that adding a single fallback would be likely be in the "more bang for the buck" side of that curve.

That said, I admit this is just a subjective assessment. I don't have stats to back this up, other than the anecdotal evidence above.

**Comment by waldyrious** [comment]
In any case, I don't feel too strongly about this; there are certainly alternative solutions other than fallbacks. For example, reports of missing entries in Wikidata including (1) potential matches and (2) instructions on how to make them effective, i.e. adding the Arch property, would satisfactorily address this issue IMO. Such a report could be included in https://repology.org/repository/wikidata/problems or produced as a separate page.

**Comment by AMDmi3** [comment]
I guess the issue may be closed.
