### ISSUE TITLE
Add Snap / snapcraft.io

### ISSUE THREAD

**Issue by philippgille** [repology/repology#627]
Snap is a new package manager by Canonical, preinstalled on Ubuntu 16.04 and newer and available for Ubuntu 14.04 and many other Linux distributions. It's becoming more popular and it would be nice to have it included in repology.

The Snap store is: https://snapcraft.io/store

Example package: https://snapcraft.io/serve  
(Pendant to the Chocolatey and Scoop packages here: https://repology.org/metapackage/serve/packages)

**Comment by sirredbeard** [comment]
You might want to take a look at [this thread](https://github.com/repology/repology/issues/363), I think you are going to get a similar response.

**Comment by AMDmi3** [comment]
I don't see usable data anywhere. And yes, I'd like to stay away from this as with flatpak.

**Comment by philippgille** [comment]
There's an API, documented here: https://dashboard.snapcraft.io/docs/api/snap.html
Or does that API not expose sufficient data in some way?

Repology is useful for app developers to check on package versions of their app without having to check each package repo one by one. Now with Flatpak and Snap becoming more popular, app developers have to go check those repos on their own again.

Are there technical reasons not to support those package formats or is it more of an ideological thing?

Would you support a PR from someone else for them?

**Comment by ulgens** [comment]
Any chance to update the resolution status to "Not planned"? The current status is misleading. Same for https://github.com/repology/repology-updater/issues/363
