### ISSUE TITLE
Make header optional for big badge

### ISSUE THREAD

**Issue by avylove** [repology/repology#629]
The "Packaging status" header for the big badge should be optional. It's not always desired as it may not go with the style of the the page the badge is included on. It also may not be relevant for sites in languages other than English.

**Comment by AMDmi3** [comment]
Done!

![Normal badge](https://repology.org/badge/vertical-allrepos/libversion.svg) ![Badge with custom header](https://repology.org/badge/vertical-allrepos/libversion.svg?header=Версии%20пакетов) ![Badge with no header](https://repology.org/badge/vertical-allrepos/libversion.svg?header=)
