### ISSUE TITLE
Add Codacy for continuous static code analysis and PR check

### ISSUE THREAD

**Issue by davidak** [repology/repology#635]
I evaluated Code Climate,  Scrutinizer, Codacy, Feram and Landscape for static code analysis of python code the last days.

The best was Codacy. It finds relevant issues with open source tools like PyLint, bandit and pep8.

Scrutinizer was also good. It uses also Pylint and some proprietary tool they developed.

Feram and Landscape are both broken, no response from support.

Code Climate finds only style issues in python code and was not helpful at all. So you might want to remove that.

Here is the check of our tool for example:
https://app.codacy.com/project/greenbone/ospd/dashboard
https://scrutinizer-ci.com/g/greenbone/gvm-tools/

Here you find my notes: https://hackmd.io/hBg_a63-RwSsNT2XB6XT_g

**Comment by AMDmi3** [comment]
Done
