### ISSUE TITLE
Sabayon packages would be a ncie addition

### ISSUE THREAD

**Issue by CarbonFixer** [repology/repology#65]
Binary Gentoo-based rolling-release distro that is somewhat popular. 
https://packages.sabayon.org/

**Comment by AMDmi3** [comment]
Does it package list differ from Gentoo significantly?

**Comment by CarbonFixer** [comment]
Never used upstream Gentoo so can't really say. I think there is a significant delay in updates to build and test the binary packages, which would be very relevant for repology.

**Comment by pink-mist** [comment]
https://repology.org/repository/sabayon exists now, so perhaps this should be closed?

**Comment by AMDmi3** [comment]
True
