### ISSUE TITLE
hp-ux repository

### ISSUE THREAD

**Issue by bll123** [repology/repology#653]
Here is an HP-UX package repository.

http://hpux.connect.org.uk/hppd/packages.html

**Comment by AMDmi3** [comment]
I see an empty package list.

**Comment by bll123** [comment]
Yeah, their search works, but they don't display the full list.

The category selection works, but you would have to drill down into each category.

http://hpux.connect.org.uk/hppd/categories.html

**Comment by AMDmi3** [comment]
No, the website is not usable. However I've found something which is on their ftp.

First, these ftp://hpux.connect.org.uk/depothelper/, but they only contain name/version pairs.
and next, these ftp://hpux.connect.org.uk/hpux/Development/Languages/DATABASE, but recursive retrieval will be required.

**Comment by AMDmi3** [comment]
Btw, #393.

**Comment by AMDmi3** [comment]
It turns out to be pretty good. Will add it today.
