### ISSUE TITLE
Windows package managers

### ISSUE THREAD

**Issue by Foadsf** [repology/repology#658]
I see that Chocolatey and Scoop are listed among the repositories, but there are more Package managers available for windows:

1. [Zero Install](https://0install.de/)
2. [Ketarin](https://ketarin.org/index.php)
3. [Npackd](https://npackd.appspot.com/)
4. [win-get](http://windows-get.sourceforge.net/)
5. [WAPT ](https://www.wapt.fr/en/)
6. [OneGet](https://github.com/OneGet/oneget) / [NuGet](https://www.nuget.org/)
7. [WPKG ](https://wpkg.org/)
8. [CoApp](http://coapp.org/index.html)
9. [Silent Install Helper](https://sourceforge.net/projects/sih/)

I was wondering if you could also consider adding them to the database.

**P.S.** relevant discussion [here ](https://www.reddit.com/r/windows/comments/8nq62b/freeopensource_package_managers_for_windows/)on Reddit.

**Comment by AMDmi3** [comment]
This is really interesting, thank you for this list. Will see which ones can be used

**Comment by Foadsf** [comment]
Does [vcpkg ](https://docs.microsoft.com/en-us/cpp/vcpkg) qualify as a repository?

**Comment by AMDmi3** [comment]
I find it impolite to suggest anything without even looking at the site.

**Comment by Foadsf** [comment]
@AMDmi3 I indeed took a look at their website and saw some methods for adding new packages/formulas ([here](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md)). I'm sorry if it bothered you in anyway.

**Comment by AMDmi3** [comment]
I've meant Repology, not their site. You would have seen then that it's already supported.

**Comment by AMDmi3** [comment]
Makes sense. Yes, please.

**Comment by Foadsf** [comment]
Following this issue, There is also [just-install](https://just-install.it/). I looked at the Reoplogy's list of repositories and it was not there. I'm not sure it is a repository though. According to the developer ([here](https://lorenzo.villani.me/2013/04/08/just-install-my-stuff/)) it is mean as an alternative to Chocolatey, Npackd and Ninite.

**Comment by AMDmi3** [comment]
:x: ~**just-install**~ links are broken (either bad certificate or 404).
:x: ~**win-get**~ last updated 2007
**WAPT** has some usable data at https://store.wapt.fr/wapt/ (https://store.wapt.fr/wapt/Packages specifically, which is a zip archive containing package data in format similar to Debian. About 300 packages. Seem to be kept up to date, but data is of low quality due to inconsistent package naming and using French in descriptions.
**npackd** actual repository data links: https://npackd.appspot.com/rep

**Comment by strafe** [comment]
@AMDmi3 just-install's new homepage is https://just-install.github.io

**Comment by AMDmi3** [comment]
just-install support is live (FYI @geek1011 @lvillani)
npackd support is live (though it's only partial, because repository widely uses incompatible package names and versions) (FYI @tim-lebedkov)

For CC'd people, [Repology](https://repology.org) is a service that compares package versions in 200+ repositories, estimates repository freshness, reports new releases and provides other useful information for package maintainers, and it now supports just-install and npackd.

**Comment by AMDmi3** [comment]
I guess that's all for this issue. Remaining repos do not look suitable for Repology.
- **Zero install** - more of a decentralized ecosystem of per-project feeds than a single repository
- **WAPT** - small, proprietary solution with incompatible data

**Comment by Foadsf** [comment]
Hi @AMDmi3 ,

I was wondering if [Win-builds](http://win-builds.org/doku.php) constitute a repository or not. From their main page:

> Win-builds is a large distribution of binary packages for Windows.

Also, I think the MinGW and MinGW-w64 repositories (the `mingw-get` package manager) might be different/independent from [MSYS2-mingw](https://repology.org/repository/msys2_mingw) one. Not sure though.

**Comment by AMDmi3** [comment]
> I was wondering if Win-builds constitute a repository or not

It does, but it does not provide metadata in usable format, is too small to be useful and had no updates since 2015.

**Comment by Foadsf** [comment]
@AMDmi3 how about the `mingw-get` repo? I think it is an independant repo from MSYS2 and Cygwin.

**Comment by AMDmi3** [comment]
No idea what this is. You could point me to the package lists.

**Comment by Foadsf** [comment]
@AMDmi3 please take a look at [this page](https://sourceforge.net/projects/mingw/files/Installer/mingw-get/catalogue/), especially the files `mingw32-package-list.xml`, `mingw32-contrib-package-list.xml`, and `msys-package-list.xml`. More details might be discussed [here](https://stackoverflow.com/q/60712613/4999991). The projects `mingw.org`, `http://mingw-w64.org`, MSYS2, and Cygwin are pretty much intertwined and there are a lot of overlaps, but they are more or less independent projects and have different repositories and different packages AFIK.

**Comment by AMDmi3** [comment]
I don't have intention to investigate this, analysis and/or patches are welcome. From a quick glance, mentioned sourceforge files are 2 and 4 years old respectively, so probably not worth spending time on.

**Comment by Foadsf** [comment]
Following this discussion [AppGet](https://appget.net/) and [winget](https://github.com/microsoft/winget-cli) worth investigating. The later is [already available](https://repology.org/repository/winget) in Repology.
