### ISSUE TITLE
 distro-agnostic package managers and software deployment systems

### ISSUE THREAD

**Issue by Foadsf** [repology/repology#661]
There are some distro-agnostic package managers and software deployment systems missing from the list of repositories:
- [Snappy ](https://en.wikipedia.org/wiki/Snappy_(package_manager))
- Flatpak #363 
- [DNF ](https://fedoraproject.org/wiki/DNF?rd=Dnf) (Maybe already listed, I see some Fedora repositories)
- [GNOME Software](https://en.wikipedia.org/wiki/GNOME_Software)
- AppImage using [AppImageHub](https://appimage.github.io/apps/)
- [Listaller](https://en.wikipedia.org/wiki/Listaller)+[Autopackage](https://en.wikipedia.org/wiki/Autopackage)
- PackageKit+pkcon 
- [ZYpp](https://en.wikipedia.org/wiki/ZYpp)
- AppStream
- [Orbital Apps](https://www.orbital-apps.com/)
- [Java Web Start](https://www.java.com/en/download/faq/java_webstart.xml) --> only for Java applications

**Comment by AMDmi3** [comment]
Package managers are irrelevant, flatpak and snap were already rejected, appimage and orbital apps are the same thing, while the latter also only contains 20 gravely outdated packages.

**Comment by Foadsf** [comment]
1. could you please point me towards the issue discussing snappy? I searched but couldn't find it.
2. what is wrong with AppImageHub?
3. How about the ZYpp and DNF? are they already listed?

**Comment by AMDmi3** [comment]
1. #363, #627
2. The same reasons
3. These are package managers, not repositories

**Comment by luzpaz** [comment]
What about appImages ? https://github.com/AppImage/
CC (@probonopd)

**Comment by probonopd** [comment]
It does say

> AppImage using AppImageHub

in the original post :+1:
