### ISSUE TITLE
The query "in AUR but not in FreeBSD" finds nyx that *exists* in FreeBSD

### ISSUE THREAD

**Issue by yurivict** [repology/repology#667]
![image](https://user-images.githubusercontent.com/271906/43678949-812d574c-97d1-11e8-9909-83ea29aad33f.png)

FreeBSD has the port for ```nyx```: ```security/nyx```, so ```nyx``` shouldn't be found.

**Comment by AMDmi3** [comment]
It's `python:nyx` in FreeBSD, so it counts as a different project. I'll merge them now.
