### ISSUE TITLE
The FreeBSD port security/py-obfsproxy-tor is the same as 'obfsproxy' in other systems

### ISSUE THREAD

**Issue by yurivict** [repology/repology#668]
```obfsproxy``` currently doesn't include the FreeBSD package.

```py-``` is a prefix, and ```-tor``` is a suffix. The other possible suffix is ```-lv2```. Comparison should be done with prefixes and suffixes removed.

**Comment by AMDmi3** [comment]
Next time please submit rule issues to [repology-rules](https://github.com/repology/repology-rules) repository.
