### ISSUE TITLE
xfce-desktop can't be found

### ISSUE THREAD

**Issue by yurivict** [repology/repology#678]
FreeBSD has such port: ```xfce4-desktop-4.12.4```, but searches for ```xfce4-desktop``` or ```xfce-desktop``` return nothing.

**Comment by AMDmi3** [comment]
https://repology.org/metapackage/xfdesktop/versions

**Comment by yurivict** [comment]
What this means is that it is available, but can't be easily found by its commonly used name.

**Comment by AMDmi3** [comment]
You can see by the link that `xfdesktop` is the commonly used name. But yes, we can probably fallback to search by package names if there are no or little results in normal search.
