### ISSUE TITLE
Use case: Finding commonly supported versions

### ISSUE THREAD

**Issue by joto** [repology/repology#697]
As a writer of Open Source software I often have the problem that I want to check whether a (potential) dependency of my software is available commonly and in what versions so that I don't introduce dependencies on build tools, libraries, etc. that are difficult to get for users. Repology is very helpful for that, but I still have to manually go through a long list of repositories for some package I am looking at and check what important distributions have which version.

It would be interesting to have some kind of view that could tell me: The newest common version supported by current distributions is x.y.z. Or something like it. I am not sure myself how to best show this. One important step would probably to have date ranges for all distributions, when were they released, when are they scheduled to be deprecated. Then I could say: Get me the largest version number of package X compatible with all distributions released 1 year ago or older. I also might not care about all distributions, but only the major ones, but that is more difficult to decide. Maybe this is something I could do with the API, but I'd still need those dates and some way to query the API for all repositories.

**Comment by AMDmi3** [comment]
What you require is too vague in regard to what distro may be considered _major_  or _current_. I am not going to decide that. A generic tool for showing a list of repositories matching a list of (optionally versioned) packages is planned (#481, #510) though. A variation of that (e.g. given a list of repositories and packages, show the highest common versions) should probably fit your needs.

**Comment by joto** [comment]
What do you think about adding release date and "expire date" for repositories? I saw that some repositories already have a `valid_till`. If there was an API call to get all repositories with their details and those dates are in there, I could probably implement something outside repology itself that could do the kind of filtering I want. I'd be willing to dig through some web sites to actually fill those values, but that only makes sense if they are exposed in an API somewhere.

**Comment by AMDmi3** [comment]
No, I don't think I want to maintain that. Also the whole idea of limiting development with outdated dependencies is flawed.
