### ISSUE TITLE
FreeBSD's pymol is displayed separately from other pymol packages

### ISSUE THREAD

**Issue by yurivict** [repology/repology#698]
See here https://repology.org/metapackages/?search=pymol

FreeBSD's one is shown as ```python:pymol```. It is the same package, it is python-based everywhere.

Note that Arch's AUR package is named ```pymol2``` which is a mistake, they should have just updated their main port, so their's ```pymol2``` should be separate, as shown.

**Comment by AMDmi3** [comment]
Note that rule issues go to https://github.com/repology/repology-rules/issues
