### ISSUE TITLE
Unrelated packages in different categories - Gentoo-based distributions.

### ISSUE THREAD

**Issue by XVilka** [repology/repology#704]
In Gentoo-based distributions, if the package has the same name in different category it still shown.
For example "ocaml" in Gentoo and Funtoo - it is in "dev-lang/ocaml" and "app-xemacs/ocaml". So it shows them both: https://repology.org/metapackage/ocaml/versions

**Comment by AMDmi3** [comment]
Yes it does, but there's nothing specific to Gentoo. This is solved by the ruleset.
