### ISSUE TITLE
adding EasyBuild

### ISSUE THREAD

**Issue by Foadsf** [repology/repology#705]
Following this [Tweet](https://twitter.com/fsfarimani/status/1044160211001528321), and the email discussion I had with @AMDmi3 I would appreciate if we could add [EasyBuild](https://github.com/easybuilders/easybuild). A list of packages can be found [here](https://easybuild.readthedocs.io/en/latest/version-specific/Supported_software.html). However Dmitry said:

> However parsable (preferrably JSON) dumps of package information
are required, and I have doubts for EasyBuilds bacause I see no
apparent way to distinguish perl/python/r modules from other packages.

Maybe @boegel can help with this?

**Comment by boegel** [comment]
I'm definitely willing to help out here (but I doubt I can do it in the short term...).

@AMDmi3 Can you clarify what you need exactly? What package information is required? In what sense do you need to be able to distinguish between Perl/Python/R modules & other tools/apps?

**Comment by AMDmi3** [comment]
Here's an elaborate documentation of what Repology expects: https://repology.org/addrepo.
Closing this issue, as there's nothing to do on Repology side until engaged parties publish data in suitable format.

**Comment by boegel** [comment]
@AMDmi3 EasyBuild already has support for dumping an overview of all supported software, but not yet in JSON format.

We use `eb --list-software=detailed --output-format=rst` to generate the page shown at https://easybuild.readthedocs.io/en/latest/version-specific/Supported_software.html, so what you're asking for wouldn't be terribly difficult.

The prefixes like `python-*` & co would require a bit of extra logic, but we could handle that on the EasyBuild side, by adding support for `eb --list-software=detailed --output-format=repology` (which would produce the info a bit pre-processed and in JSON format).

What type of sources do you expect though, is an `eb` command that produces this sufficient for you, or do you expect a page that serves the up-to-date info in JSON format?
That would be a bit harder (not impossible, just more work)...

**Comment by AMDmi3** [comment]
> `--output-format=repology`

As mentioned https://repology.org/addrepo, I'm against any repology-specific upstream changes, so I'd prefer just a consumer agnostic detailed format which provides sufficient data, named accordingly.

> is an eb command that produces this sufficient for you, or do you expect a page that serves the up-to-date info in JSON format?

I'm not running any third party utilities, so I expect the latter.
