### ISSUE TITLE
Adding Spack

### ISSUE THREAD

**Issue by Foadsf** [repology/repology#706]
Following this [Tweet](https://twitter.com/fsfarimani/status/1044160211001528321), and the email discussion I had with @AMDmi3 I would appreciate if we could add [Spack](https://spack.io/). A list of packages can be found [here](https://spack.readthedocs.io/en/latest/package_list.html)

**Comment by AMDmi3** [comment]
This needs JSON dump too.

**Comment by AMDmi3** [comment]
@tgamblin @adamjstewart hi, I think it makes sense to invite Spack developers.

In short, [Repology](https://repology.org) is a service which compares package versions in a lot of package repositories, helps maintainers discover new versions sooner. @Foadsf suggested to add Spack (which I wasn't aware of) support, for which a JSON dump of package information would be useful.

**Comment by adamjstewart** [comment]
Hi!

This wouldn't be hard to support. There is already a `spack list --format` option that supports RST and HTML. Shouldn't be hard to add JSON. What format are you expecting?

**Comment by Foadsf** [comment]
@adamjstewart  [this](https://github.com/repology/repology/issues/705#issuecomment-425489539) might help

**Comment by AMDmi3** [comment]
Here's an elaborate documentation of what Repology expects: https://repology.org/addrepo.
Closing this issue, as there's nothing to do on Repology side until engaged parties publish data in suitable format.
