### ISSUE TITLE
Repology doesn't detect maintainers at Ravenports

### ISSUE THREAD

**Issue by mazocomp** [repology/repology#707]
Hi!

I've become a contributor to Ravenports and I already maintain few ports and I'd like to use Repology to notify myself about outdated ports.

However, instead of my e-mail I see "fallback-mnt-ravenports@repology", is there any quick fix which can be done to it?

**Comment by mazocomp** [comment]
Ok.

**Comment by jrmarino** [comment]
Okay, report has been updated to add contacts:
https://raw.githubusercontent.com/jrmarino/Ravenports/master/Mk/Misc/repology.json

items to note:

1. If port has no designated maintainer, there is no "contacts" field
2. For ports with at least one designated maintainer, an array of objects is defined, e.g.
```
  ,{
     "bucket": "01"
    ,"namebase": "fltk"
    ,"version": "1.3.4-2"
    ,"homepage": "http://www.fltk.org/"
    ,"FPC": "x11-toolkits/fltk"
    ,"keywords": [ "x11_toolkits" ]
    ,"distfile": [ "http://fltk.org/pub/fltk/1.3.4/fltk-1.3.4-2-source.tar.gz" ]
    ,"contacts": [ { "name": "Michael Reim", "email": "kraileth@elderlinux.org" } ]
    ,"variants":
     [
      {
        "label": "standard"
       ,"sdesc": "Light-weight cross-platform C++ GUI toolkit"
       ,"spkgs": [ "complete", "primary", "examples" ]
      }
     ]
   }
```
3. Multiple maintainers are supported.  There are no current cases where 2 or more maintainers are defined, but it's permitted.  If repology only allows one, then take the first one.
4. Names and email are permitted.
