### ISSUE TITLE
Arch package deal-ii isn't found

### ISSUE THREAD

**Issue by yurivict** [repology/repology#709]
Arch has ```deal-ii``` package: https://aur.archlinux.org/packages/deal-ii/
But searching for it in repology only returns ```p4est-deal-ii``` which is a different package.

**Comment by AMDmi3** [comment]
https://repology.org/metapackage/deal.ii/versions

**Comment by yurivict** [comment]
What this means is that users familiar with repology who read docs and understands its concepts would be able to find it.

For the average user ```deal-ii``` is just not found.

**Comment by AMDmi3** [comment]
Why would an "average user" search the software by a different name? It's named deal.II, see the web site.

**Comment by yurivict** [comment]
When somebody searches by the name of one of the packages in a metapackage, the best outcome would be if you would also show the link to the metapackage: ```Also see the metapackage deal.ii```. This is better than not showing this item at all and hoping that users would figure this out themselves.
