### ISSUE TITLE
Adding support for Collective Knowledge packages

### ISSUE THREAD

**Issue by gfursin** [repology/repology#714]
As discussed with @AMDmi3, we plan to add support for Collective Knowledge packages (http://cKnowledge.org/shared-packages.html). These are mostly scientific packages for AI, ML and quantum computing connected with portable research workflows though we have a growing number of users from other domains (http://cKnowledge.org/partners.html). 

See example of a public meta information of a CK package for TensorFlow (building TF from sources with CUDA support): https://github.com/ctuning/ck-tensorflow/blob/master/package/lib-tensorflow-1.10.1-src-cuda/.cm/meta.json

We will just need to add extra meta-information required by repology and generate a big JSON file with info about all packages.

CC @psyhtest , @ens-lg4 .

**Comment by AMDmi3** [comment]
Here's an elaborate documentation of what Repology expects: https://repology.org/addrepo.
Closing this issue, as there's nothing to do on Repology side until engaged parties publish data in suitable format.
