### ISSUE TITLE
Use "legacy" version class on "released" distributions

### ISSUE THREAD

**Issue by FedericoCeratto** [repology/repology#719]
Hi and thanks for repology.
The "legacy" version class should be applied on all packages found in distributions that ship stable releases.
Examples: Debian Stable, Raspbian Stable in https://repology.org/metapackage/nim/badges

**Comment by AMDmi3** [comment]
Of course not. Regardless of distribution status, outdated is outdated.

**Comment by FedericoCeratto** [comment]
This is an example of a different color coding: https://en.wikipedia.org/wiki/Template:Version
Release that live in a stable distribution should not be flagged in red because it is misleading: they are receiving security updates from the distribution and are **recommended** for production. They should be green.
A version in a distribution **currently** in LTS they could be yellow/orange to signify that they are still usable and trusted but old.
A version in an unmaintained distribution (aka that is not receiving security updates) should be red to signify the risk.

**Comment by FedericoCeratto** [comment]
Marginally related to https://github.com/repology/repology-updater/issues/11
