### ISSUE TITLE
Fedora Rawhide gcc version

### ISSUE THREAD

**Issue by dg0yt** [repology/repology#734]
The [gcc versions page](https://repology.org/metapackage/gcc/versions) reports gcc 8.2.1 for Fedora Rawhide plus a number of `compat-gcc-x.y.z` with version 3.4.6 and lower.

## Actual behaviour

The Fedora Rawhide gcc version badge shows 3.4.6.

## Expected behaviour.

The Fedora Rawhide gcc version badges shows 8.2.1.

---

Note that other versions of Fedora do not seem to be affected, despite the presence of `gcc-compat-...` packages: https://repology.org/metapackage/gcc/badges
[![Fedora Rawhide package](https://repology.org/badge/version-for-repo/fedora_rawhide/gcc.svg)](https://repology.org/metapackage/gcc/versions)
[![Fedora 28 package](https://repology.org/badge/version-for-repo/fedora_28/gcc.svg)](https://repology.org/metapackage/gcc/versions)

**Comment by AMDmi3** [comment]
gcc version 8.2.1 does not exist (see https://gcc.gnu.org/releases.html, ftp://ftp.gnu.org/gnu/gcc/), so we ignore it. Badges show latest non-ignored version available.
