### ISSUE TITLE
false dead message for weeks

### ISSUE THREAD

**Issue by jrmarino** [repology/repology#739]
On norm package, RP is seeing error "https://www.nrl.navy.mil/itd/ncs/products/norm" is dead, but the site has always been active since the "problem" first appeared.

I expected it to go away after a week, but 18 days later it's still present.
Perhaps there's some check failing?  The site is reachable and has been continuously as far as I can tell.

**Comment by AMDmi3** [comment]
It is down from all Russian locations I have access to.

**Comment by jrmarino** [comment]
i don't understand.  So you're considering my report invalid?

**Comment by AMDmi3** [comment]
Yes.

**Comment by jrmarino** [comment]
The problem is the report is completely valid.  Anybody (except Russians apparently) can reach this site.  Thus repology is willfully providing false information (willful at the put you know its false, yet keep publishing it).

If this is something like "all *.mil sites are blocked in russian" then your problem scanner should skip validity checks on *.mil.

right?
Surely you can't disagree with my logic here.

**Comment by AMDmi3** [comment]
I surely can. If the website is not available worldwide, it's broken. Broken links should be reported and fixed.

**Comment by jrmarino** [comment]
wow.
I bet more than half the sites are not available in China.  So you're going to disable them all, right?
You can't seriously believe that, especially when your country very well could be the source of the blockage.  

Maybe it's worth putting a disclaimer that Russia is the center of the internet now, and if it's not available there the rest of the world is broken?  Why not, if you really believe that.

**Comment by AMDmi3** [comment]
>  So you're going to disable them all

I'm not "disabling" anything, I'm reporting website status.

> Maybe it's worth putting a disclaimer that Russia is the center of the internet now

It has nothing to do with Russia. If the link checker was hosted in another location, it would obviously report broken sites for that location. If I could host it in multiple locations, it would report a website as broken if it could not be reached from any of them. If it wasn't hosted in Russia though it wouldn't discover this problem. So be glad.

I'm surprised with your attitude. It looks like you care more for greenish indicator status than for making a high quality product.

**Comment by jrmarino** [comment]
do you want me to post a snapshot of https://www.nrl.navy.mil/itd/ncs/products/norm ?
It's the US Navy.  The site works.  Hop on a VPN and check it out.
The US Navy writes norm.  It's the upstream official site.  What is more high-quality than the truth?

Right now repology is reporting this is a dead site and nothing is further from the truth.  If you mechanism is incapable of determining the truth based on its location, then, again, I suggest you filter out US military sites so it doesn't show as a false positive.

**Comment by jrmarino** [comment]
I think there are other issues.
e.g http://mama.indstate.edu/users/ice/tree/
works fine.
yet:
```
Homepage link "http://mama.indstate.edu/users/ice/tree" is dead (connect timeout) for more than a month.
--

makes you wonder if there's a systematic issue causing these false positives.


```

**Comment by AMDmi3** [comment]
> do you want me to post a snapshot of https://www.nrl.navy.mil/itd/ncs/products/norm ?

I don't want anything from you, god forbid. _You_ probably want to provide a link which works for everyone. I'd just provide archive.org as an alternative link and write upstream about the problem.

> http://mama.indstate.edu/users/ice/tree/

Dead the similar way. https://www.uptrends.com reports it's not available from other location as well.

> these false positives

These are not false positives, period.
