### ISSUE TITLE
Arch Linux packages are listed by their last packager, not maintainer

### ISSUE THREAD

**Issue by ArchangeGabriel** [repology/repology#741]
Since you parse the DB, you only get who built the package last. This can be a different person than the actual maintainer of the package, an information that is only available on the website I fear…

**Comment by AMDmi3** [comment]
If this information is not published in an usable way, there's nothing can be done on Repology side. I can only make this problem visible on the site when #696 is implemented.

**Comment by ArchangeGabriel** [comment]
Well they are tools that allow to get this by parsing the website easily. aurphan (which uses expac for this AFAICT) has mode to look for a given maintainer packages.

**Comment by AMDmi3** [comment]
Using external tools is not an option.

**Comment by ArchangeGabriel** [comment]
[aurphan](http://kmkeen.com/aurphan/aurphan.tar.gz) is at most 300~ lines of bash code (including lots of useless things for this case), you might be able to reimplement that in you python parser instead. ;)

**Comment by AMDmi3** [comment]
Sorry, I'm not going to spend any time on this. Publishing complete metadata is repositories' responsibility (and actually any of repository contributors can do it, even if owners do not care), and doing it on Repology side would be a waste of resources.

**Comment by FFY00** [comment]
You can just get the maintainer from our json interface.

https://www.archlinux.org/packages/community/x86_64/cockatrice/json

**Comment by AMDmi3** [comment]
We're not going to do a HTTP request per every package.

**Comment by antonio-rojas** [comment]
Please remove displaying maintainers for arch packages until a solution is found for this. I'm really tired of getting emailed about packages I don't maintain just because I happen to do many rebuilds.

**Comment by eli-schwartz** [comment]
It's possible to get the results for multiple packages in one HTTP request: https://www.archlinux.org/packages/search/json/?q=foo

Actually, you can also iterate over each valid maintainer, and use:

https://www.archlinux.org/packages/search/json/?maintainer=eschwartz

For especially active maintainers you may need to iterate over a number of `&page=` as it is capped at 250 packages per request.

I'd encourage using this instead. If you need anything more than this, then suggestions and/or pull requests at https://github.com/archlinux/archweb/ would be valued.

**Comment by AMDmi3** [comment]
> Actually, you can also iterate over each valid maintainer, and use

To iterate over maintainers, I'd need a list of maintainers first.

**Comment by eli-schwartz** [comment]
You can get a current list of valid maintainers by performing a single HTTP request to the search form itself at https://www.archlinux.org/packages/ and then iterating over the valid options in:

```
<select name="maintainer" id="id_maintainer">
      <option value="" selected>All</option>
      <option value="searchname" selected>Friendly Name</option>
```

The list also changes infrequently (once a month? once every few months? it depends on how often new applications are submitted on the aur-general mailing list), so you could cache it at least daily -- I think repology runs every couple of hours?

I would even say you could derive it from this yaml list tracked in git: https://git.archlinux.org/infrastructure.git/tree/group_vars/all/archusers.yml

But I don't think the actual shell accounts are guaranteed to map to the web logins. OTOH the yml does track when new maintainers join up.

**Comment by AMDmi3** [comment]
Parsing HTML, cool. Well, no - I'm not going to introduce and maintain overcomplicated and unreliable fetcher, which has to parse HTML, spend time doing a lot of requests and return inconsistend data due to non-atomicity. It's a nice chance for arch community to think of providing a proper dump.
