### ISSUE TITLE
Edgecase: when a repository mistypes the version number and affects the badge displaying version numbers 

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#744]
[![Packaging status](https://repology.org/badge/vertical-allrepos/freecad.svg)](https://repology.org/metapackage/freecad/versions)

Specifically: 
[![freshcode.club package](https://repology.org/badge/version-for-repo/freshcode/freecad.svg)](https://repology.org/metapackage/freecad/versions)

The freshcode repo wasn't updated correctly, the revision number was mistyped. It should have been 0.17.13541 

This was corrected on the freshcode side see http://freshcode.club/projects/freecad
![image](https://user-images.githubusercontent.com/4140247/48201806-3eb8c800-e331-11e8-8662-c6db93456d63.png)

But the badge doesn't reflect that change. The consequence is that the colors of the correct stable version on the badge show that they are outdated.

**Comment by AMDmi3** [comment]
0.17.15341 was not removed from the feed (http://freshcode.club/feed/xfer.json) which Repology parses. Well, as per your screenshot, website still shows it as well. Repology takes the greatest version.

**Comment by luzpaz** [comment]
I guess I need to talk to the fresh code devs then

**Comment by luzpaz** [comment]
Opened a downstream issue https://fossil.include-once.org/freshcode/tktview/846217f054897f182334ab039ab5e4fca600dbc2

**Comment by AMDmi3** [comment]
Seems to be fixed
