### ISSUE TITLE
Add copr for fedora

### ISSUE THREAD

**Issue by bgstack15** [repology/repology#745]
Please consider adding the Community Projects for the Fedora/Red Hat/CentOS communities: https://copr.fedorainfracloud.org/

This is similar to the AUR in that it is user-contributed builds available to Fedora users by the main package manager by simply enabling the copr repository.

**Comment by AMDmi3** [comment]
I need a package listing or repository metadata URL.

**Comment by bgstack15** [comment]
Unfortunately copr is broken up into a number of projects, and each project contains a yum repository definition. I understand if this is too complex to ask for in just an issue, without me presenting a pull request for it.
A basic curl interaction with the [Copr api](https://copr-rest-api.readthedocs.io/en/latest/Resources/project.html#list-projects):
```
curl --data-urlencode 'offset=300' --data-urlencode 'limit=50' -X GET https://copr.fedoraproject.org/api_2/projects
```

Then, iterate over all the project IDs.
```
curl --data-urlencode 'show_builds=true' -X GET https://copr.fedoraproject.org/api_2/projects/$ID | python -m json.tool
````

The matrix of project owner, name and chroot combine to make a repo file, e.g., https://copr.fedorainfracloud.org/coprs/bgstack15/palemoon/repo/fedora-28/bgstack15-palemoon-fedora-28.repo, but I don't have the skills yet to write all that out as a PR.

**Comment by AMDmi3** [comment]
So it's basically unmoderated personal package repositories, somewhat similar to Ubuntu PPAs?
We don't and won't support these. See also #388.

**Comment by bb010g** [comment]
> So it's basically unmoderated personal package repositories, somewhat similar to Ubuntu PPAs?
> We don't and won't support these.

How does this differ from the AUR?

**Comment by AMDmi3** [comment]
AUR is not a private repository.
