### ISSUE TITLE
Feature: Ability to query the database, API, or webgui with a list of packages and get an output of their support on a specific distro/package-manager 

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#751]
Lets say I have a list of packages:
```
calculix
elmerfem
fenics
openfoam
gmsh
z88
```
I'd like to see if there are all supported on say Homebrew (and what version is currently supported) in all one fell swoop.

**Comment by AMDmi3** [comment]
You can query them in 6 requests from https://repology.org/api.
