### ISSUE TITLE
Linuxbrew not updating ?

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#756]
The [Linuxbrew gmsh formula](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/gmsh.rb) was updated 7 days ago right after the [Homebrew gmsh formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmsh.rb). Yet it still hasn't shown up correctly in the badge.

[![Homebrew package](https://repology.org/badge/version-for-repo/homebrew/gmsh.svg)](https://repology.org/metapackage/gmsh/versions)

[![Linuxbrew package](https://repology.org/badge/version-for-repo/linuxbrew/gmsh.svg)](https://repology.org/metapackage/gmsh/versions)

**Comment by AMDmi3** [comment]
No idea. https://travis-ci.org/repology/homebrew-json-gen-travis works fine and that's what it produces.

**Comment by AMDmi3** [comment]
As I understand, Linuxbrew is suited for operation from user's home directory, so you can just create a dedicated user (for safety & isolation) and run linuxbrew under it. Commands are roughly as listed in https://github.com/repology/homebrew-json-gen-travis/blob/master/.travis.yml#L17-L21, but read linuxbrew docs as well.

Though, I'd rather them make a formula dump available like homebrew [did](https://formulae.brew.sh/api/formula.json).

**Comment by luzpaz** [comment]
Look at that.. the linuxbrew port synced up and it's now up to date. 
@AMDmi3 thanks for the explanation.

**Comment by AMDmi3** [comment]
I'd prefer to not pile up issues which do not assume concrete actions.
