### ISSUE TITLE
Badge: Add a color agnostic badge ?

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#757]
Recently I posted https://github.com/matplotlib/matplotlib/issues/12910#issuecomment-444688976

The dev there wrote:
> Also personally, I don't quite like the coloring. The strong red gives the false impression that there are serious issues. But most of the distros do not try to be cutting edge, so it's perfectly fine for debian stable to be on 2.0.0.

It's a valid point.  

An [example](https://forum.freecadweb.org/viewtopic.php?f=4&t=19903&p=272675#p272675), I used the miniversion url modifier and still it's not clear in the badge that 0.17 (not 0.17.13541) is considered stable.

**Comment by AMDmi3** [comment]
Any concrete suggestions?

**Comment by luzpaz** [comment]
Perhaps make them all gray (or some neutral color that isn't already assigned in the current repology legend)?

**Comment by AMDmi3** [comment]
That defies the whole purpose of the badge.

**Comment by luzpaz** [comment]
sort of, but no. You see, it's an in between usecase of showing how many repos the package (tinybadge) is in and also showing their versions (vertical color badge).

**Comment by AMDmi3** [comment]
This does not justify the existence of such badge. I don't see a use for alternative version of existing badge which is less informative and less readable, with no apparent benefits.
