### ISSUE TITLE
Badge: Add a Legend Section (with ability to disable)

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#758]
Inspired by #757 

![image](https://user-images.githubusercontent.com/4140247/49582624-a576d480-f923-11e8-993b-81d5ca882c59.png)
could be minimized and tacked on to the side of a badge.

**Comment by AMDmi3** [comment]
Badges are supposed to be compact, this would be an overkill. Also, color scheme for badges is simplified to just 3 colors which is supposed to be pretty much self descriptive.
