### ISSUE TITLE
Search for 'googletest' doesn't return the 'googletest' package

### ISSUE THREAD

**Issue by yurivict** [repology/repology#763]
It returns these 2 items:
* android-googletest
* vim:googletest-syntax

FreeBSD has the package ```googletest``` from the port ```devel/googletest```, and it isn't returned.

**Comment by luzpaz** [comment]
If you click on the asterix after android-googletest it gives you a list of related packages. 

So..looks like it's gtest https://repology.org/metapackage/gtest/versions
Therefore we need repology to merge all gtest in to googletest

**Comment by yurivict** [comment]
Yes, and the search for both terms should produce the same results.

**Comment by luzpaz** [comment]
@yurivict that's what the `Report` page is for:
https://repology.org/metapackage/gtest/report

**Comment by yurivict** [comment]
Sure.

**Comment by AMDmi3** [comment]
@luzpaz please do not mislead other contributors.

First, do not replace issues with reports. The latter are just a marginal way of reporting an obvious problem. Second, the report is invalid as we do not _create package names_.

The `gtest` name was chosen for this metapackage as (much) more widely used, and it will not be changed for the sake of any repository. Changing it won't solve the problem anyway, as other people won't be able to find `gtest` after the change.

The real issue is that we need a search for package names and I thought we already have an issue for that.

**Comment by luzpaz** [comment]
Apologies, my intention was to be mindful about not cluttering up the issue queue. Though I'm now confused about what the reports tab is useful for. 

It may be known better as `gtest` but the logic needs to be able to show that it's interchangeable with `googletest` which is what I imagine a far greater number of people would use as a search string.

It wasn't creating a package name as the package name does already exist in the ecosystem.

**Comment by AMDmi3** [comment]
> Apologies, my intention was to be mindful about not cluttering up the issue queue

There's no such thing as "cluttering up the issue queue". Issues are meant to be reported. Duplicating stuff and moving it between places does introduce cluttering though.

> Though I'm now confused about what the reports tab is useful for.

As already said, they are simpler marginal alternative to issues to make trivial reports more accessible. Issues are always preferred as they allow discussion, store information about author, history and are better formatted.

> It may be known better as gtest but the logic needs to be able to show that it's interchangeable with googletest which is what I imagine a far greater number of people would use as a search string.

There's no logic in the statement "A is known better but more people would use B".

> It wasn't creating a package name as the package name does already exist in the ecosystem.

Repology aggregates and normalizes all the garbage which "exists in the ecosystem" to make it useful. To search the discrepancies, different kind of search is needed. Not that introducing it is a problem, but I still haven't came up with a way to mix different searches together (see also #351).
