### ISSUE TITLE
Main page can break

### ISSUE THREAD

**Issue by Chocimier** [repology/repology#766]
When package selected to be shown on main page is not available in database, main page does not display at all. Filtering similar to
`metapackagedata = {k: v for k,v in metapackagedata.items() if k in metapackages}` after https://github.com/repology/repology/blob/master/repologyapp/views/index.py#L185 can solve problem.

**Comment by AMDmi3** [comment]
How can this situation be reproduced? I've tried removing `effname=awesome` from both `metapackages` and `packages` and it works fine.

**Comment by Chocimier** [comment]
Seems to be fixed since last time I checked this, sorry.
