### ISSUE TITLE
Whats the difference between dports and FreeBSD ?

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#767]
I ask because they both seem to be mirroring the same repo. But sometimes they aren't in sync. 
Example: 
https://repology.org/metapackage/libredwg/versions

[![DPorts package](https://repology.org/badge/version-for-repo/dports/libredwg.svg)](https://repology.org/metapackage/libredwg/versions)

[![FreeBSD port](https://repology.org/badge/version-for-repo/freebsd/libredwg.svg)](https://repology.org/metapackage/libredwg/versions)

Reminds me of #756 (but yet quite different)

**Comment by AMDmi3** [comment]
Dports is FreeBSD ports adaptation for DragonFlyBSD. It contains a subset of ports and lags behind.

**Comment by luzpaz** [comment]
just wondering what the lag time is ?

**Comment by AMDmi3** [comment]
Varying. AFAIK the ports tree is built for dragonfly manually once a few weeks.
