### ISSUE TITLE
Merge rstudio

### ISSUE THREAD

**Issue by pat-s** [repology/repology#775]
Main name: "rstudio"

### AUR
stable: `rstudio-desktop` or `rstudio-desktop-bin`
beta: `rstudio-desktop-preview-bin`
dev: `rstudio-desktop-git`

Also I am unsure how you handle the case of `rstudio-server` which is version wise the same as `rstudio` but its own pkg as it is dedicated to servers.

I opened #142 but unsure if everything is correct. Great initiative!

**Comment by AMDmi3** [comment]
Fixed
