### ISSUE TITLE
Proposal: In Badge move 'AUR' directly under/after 'Arch' 

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#777]
Currently the AUR is several rungs lower in the badge because of alphabetical sorting, AFAICT. 

I propose that it be moved to be directly listed after the Arch disto. In so doing it makes it a little bit more efficient for those who are familiar with Arch Linux and its derivative to know that just because a package is outdated in Arch doesn't mean it's not available and/or up to date in the Arch User Repository (and vice-versa).  
![repology-arch-aur](https://user-images.githubusercontent.com/4140247/51113422-e4743180-17cf-11e9-82af-d75b15aef3d0.png)

Possible solutions: explicitly rename to:   
`Arch(AUR)`  
`Arch User Repository`  
`Arch User Repository(AUR)`

**Comment by AMDmi3** [comment]
Luckily, we have full control over repository list sorting, so it's easy and we don't even need to rename it. Great idea!
