### ISSUE TITLE
Proposal: In Badge move 'dports' directly under/after 'FreeBSD ports'

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#782]
Similar logic to #777 or perhaps rename it `DragonFlyBSD DPorts ?`

**Comment by AMDmi3** [comment]
I don't think it makes sense in this case. Arch/AUR were essentially parts of the whole, close enough in the list and of interest to the same people. Neither of these apply to FreeBSD/dports or other related repositories like arch/manjaro/parabola or debian/pardus/parrot/pureos/raspbian/trisquel and it's not worth breaking the alphabetical order.
