### ISSUE TITLE
Tiny core linux

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#784]
There's a list of .tcz packages for a given release/arch, e.g. http://www.tinycorelinux.net/10.x/x86_64/tcz/.
We can add .info extension to each package and get text descriptions like

```
Title:          bash.tcz
Description:    bash for tinycore
Version:        4.4.18
Author:         Chet Ramey
Original-site:  www.gnu.org/software/bash/
Copying-policy: GPL
Size:		388KB
Extension_by:   Jason W
Tags:	    	bash
Comments:       Bash is a shell for Linux
		This extension is PPI compatible
                ----------
Change-log:     2008/07/23 First version
	        2008/09/09 Removed the symlink /bin/sh -> /bin/bash.
		/bin/sh needs to remain pointing to busybox ash. 
	        2008/11/27 Recompiled for 486 and size optimization.
                2009/02/02 Made PPI compatible.
		2009/04/05 Added basic bashrc
		2009/09/19 Upgraded to version 4.0.
		2010/02/21 Corrected startup script to not overwrite existing /usr/local/etc/bashrc.
		2011/05/24 Copying .bashrc to /etc/skel/
                2013/06/12 compiled for TC-5.0 (3.8.10 Kernel) patched 1-45 & updated by coreplayer2
                2014/09/18 updated 4.2 -> 4.3 patches 0-25 (juanito)
                2015/07/29 updated 4.3 -> 4.3.30 patches -> 39 (juanito)
                2015/09/27 adjusted startup script (juanito)
                2016/10/20 updated 4.3.30 -> 4.4 (juanito)
                2017/12/09 updated 4.4 -> 4.4.12 (juanito)
                2018/03/16 recompiled against updated readline (juanito)
                2018/04/05 added missing startup script back (juanito)
Current:	2018/11/11 updated 4.4.12 -> 4.4.18 (juanito)
```
From which we can parse version, www (sometimes contains "see list of sites below" reference instead of real data), summary (useless in most cases), license, and maintainer. Package name equals to package file name minus extension. The data looks trashy, but potentially usable. The main problem is inconvenience of downloading several thousands files.

**Comment by Chocimier** [comment]
Files are available through rsync://distro.ibiblio.org/tinycorelinux/10.x/x86/tcz/

**Comment by AMDmi3** [comment]
Oh, nice, thanks! Gotta check.

**Comment by AMDmi3** [comment]
Parser ready, but the data is garbage: there are suffixes which cant be normalized and garbage in versions (`Kernel=4.19.10-tinycore64 - module=git-zip-20190117`, `1.4 (Debian patches)`, `4.19.10-tinycore64`, `gitzip 2018/01/22`). This won't be supported.
