### ISSUE TITLE
Lunar linux

### ISSUE THREAD

**Issue by Chocimier** [repology/repology#785]
Quite up-to-date source distro. Possible data sources are bash recipes in tarball http://www.lunar-linux.org/lunar/moonbase.tar.bz2 or pkgname and version only list http://www.lunar-linux.org/lunar/distrowatch.txt . Or, since they host data especially for distrowatch ranking, maybe can be encouraged to host more complete data for repology?

**Comment by AMDmi3** [comment]
@Florin65 @Ratler JFYI.

[Repology](https://repology.org) is a service which track and compares package versions in 200+ repositories, which is mostly useful to maintainers to track new upstream releases. There was an idea of adding Lunar linux support too, but there's no data in suitable format, see above. We could cooperate if you're interested.

**Comment by Ratler** [comment]
@AMDmi3 we would be happy to help getting lunar package status in to Repology. Let us know what format you would like the file to be in and we will generate one that updates as soon as our package database (moonbase) changes.

**Comment by AMDmi3** [comment]
I've finally written an elaborate document: https://repology.org/addrepo, requirements and desired data format is there. In particular, JSON dump containing `module`, `version`, `source`, `source_url`, `web_site`, `type` and `short` values and path under "moonbase" (e.g. `other/perl/File-BaseDir`) for all the DETAILS files would be great, and some comments regarding how python/perl modules could be distinguished. I assume this can be done by checking for `other/perl`, `other/python` in paths and also stripping existing `python-`, `python2-` prefixes.

**Comment by AMDmi3** [comment]
Closing thins as there's nothing to do until upstream publishes usable data.

**Comment by Chocimier** [comment]
@Ratler, any progress?
