### ISSUE TITLE
OpenMandriva Cooker not reporting correct version

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#786]
[![OpenMandriva Cooker package](https://repology.org/badge/version-for-repo/openmandriva_cooker/blender.svg)](https://repology.org/metapackage/blender/versions)

and yet
https://github.com/OpenMandrivaAssociation/blender/blob/master/blender.spec#L12 reports `2.79b`

**Comment by AMDmi3** [comment]
http://abf-downloads.openmandriva.org/cooker/repository/SRPMS/main/release not our problem
