### ISSUE TITLE
freshcode.club not reporting correct version

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#787]
[![freshcode.club package](https://repology.org/badge/version-for-repo/freshcode/cmake.svg)](https://repology.org/metapackage/cmake/versions)

where the page is [showing v3.13.3](http://freshcode.club/projects/cmake)

**Comment by AMDmi3** [comment]
That's what their feed contains.
```
% curl --silent 'http://freshcode.club/feed/xfer.json?num=15000' | sed -ne '/"name": "cmake"/,/"version": /p' | grep '"version":'
            "version": "3.7.0",
            "version": "3.1.2",
            "version": "3.1.0",
            "version": "3.0.1",
            "version": "3.0.0",
```
