### ISSUE TITLE
Number of popular packages missing

### ISSUE THREAD

**Issue by davidak** [repology/repology#789]
I want to get the number of popular packages that are missing in nixpkgs unstable.

https://repology.org/metapackages/?search=&maintainer=&category=&inrepo=&notinrepo=nix_unstable&repos=&families=5-&repos_newest=&families_newest=

Here is a list, but a number is missing.

Can you add the total number to that view?

**Comment by AMDmi3** [comment]
That is not technically possible, see #665. However you can iterate through API and count them.

**Comment by davidak** [comment]
I understand, thanks.
