### ISSUE TITLE
Add januslinux support

### ISSUE THREAD

**Issue by nee-san** [repology/repology#792]
https://github.com/JanusLinux/janus/tree/master/packages

just PKGBUILD files

**Comment by AMDmi3** [comment]
We can't parse PKGBUILDs

**Comment by nee-san** [comment]
Oh, that's sad

**Comment by AMDmi3** [comment]
See https://repology.org/addrepo for datails on what's needed to add support for a repository

**Comment by nee-san** [comment]
@AMDmi3 januslinux uses crux's pkgbuilds so can u add it now? ;3

Link: https://github.com/JanusLinux/janus/tree/master

NOTE: include "bsp" and "packages" repos

**Comment by AMDmi3** [comment]
Like I've said, we can't parse any kind of shell scripts.

**Comment by nee-san** [comment]
But how did you parse Pkgfile (CRUX ports)? I use them

**Comment by AMDmi3** [comment]
It's a legacy crippled parser which rests on the hope that it won't encounter any variables, unusual quotes or other shell constructs. This is already not true for crux, so crux parsing is incorrect, not mentioning that it is not able to parse all the fields. It won't be used for any new repositories.
