### ISSUE TITLE
Index Homebrew tap Brewsci/bio [feature request]

### ISSUE THREAD

**Issue by sjackman** [repology/repology#796]
Could you please index the Homebrew tap [Brewsci/bio](https://github.com/Brewsci/homebrew-bio)?

**Comment by AMDmi3** [comment]
As long as there's metadata dump similar to https://formulae.brew.sh/api/formula.json

**Comment by sjackman** [comment]
Ah, got it. No, that information does not yet exist. I'll look into it.

**Comment by sjackman** [comment]
If there were an API for Homebrew taps like `https://formulae.brew.sh/api/tap/brewsci/homebrew-bio/formula.json`, could you index that tap?

**Comment by AMDmi3** [comment]
If there's JSON similar to one I've given link to and there are no problems with data (such as too many name conflicts between unrelated projects, or too many fake versions, see https://repology.org/addrepo for details on data requrements) - sure.

**Comment by sjackman** [comment]
Thanks. I'm working on it. The URL would likely be something like https://brewsci.github.io/api/bio/formula.json

**Comment by AMDmi3** [comment]
If there's a way to generate JSON for the tap right now by hand, that would be useful to check the data compatibility before doing more work.

**Comment by sjackman** [comment]
Here's an example of the data: https://gist.githubusercontent.com/sjackman/07f06dcff8a531350b3c2ecb077ff836/raw/cec3e90d8dd4cecb170cb559838ea5f9768139bb/brewsci-bio.json

**Comment by sjackman** [comment]
Do you have a preference whether the `json` file includes the outer bracket? That is…
```json
{…}
{…}
{…}
```
vs
```
[
{…},
{…},
{…}
]
```
?

The gist above is in the former format.
https://formulae.brew.sh/api/formula.json is in the latter format.

**Comment by sjackman** [comment]
I figured out `jq -s .` converts the former into the latter, so I'll generate the latter.

**Comment by AMDmi3** [comment]
The latter if course. The former is not valid JSON.

**Comment by AMDmi3** [comment]
Checked, looks good.

![bio](https://user-images.githubusercontent.com/474217/52507137-b97bd280-2c01-11e9-8229-274d8ceca2e9.png)

I've prepared a bunch of rules, so these numbers will improve a bit.

**Comment by sjackman** [comment]
Here's the API for the data: https://brewsci.github.io/homebrew-bio/api/formula.json
It's being generated using GitHub Actions!
https://github.com/brewsci/homebrew-bio/actions

**Comment by sjackman** [comment]
Let me know when this data is live on https://repology.org. I'm very excited to see it! I want to use it to keep the packages up-to-date in Brewsci/bio.

**Comment by sjackman** [comment]
I want to see whether I can automate getting the data from Repology and opening the pull requests to bump the formula versions (using Homebrew's `brew bump-formula-pr` command).

**Comment by zbeekman** [comment]
Should probably still spot-check review them, but this would be cool for
core too.

**Comment by AMDmi3** [comment]
It's [live](https://repology.org/repository/homebrew), enjoy.

Regarding the automation, there's an [API](https://repology.org/api), you can use to basically get all the data for [outdated in brewsci/bio](https://repology.org/metapackages/?search=&maintainer=&category=&inrepo=homebrew_tap_brewsci_bio&notinrepo=&repos=&families=&repos_newest=&families_newest=&outdated=on) view as [json](https://repology.org/api/v1/metapackages/?search=&maintainer=&category=&inrepo=homebrew_tap_brewsci_bio&notinrepo=&repos=&families=&repos_newest=&families_newest=&outdated=on). It's not the most convenient though, you'll need to filter your packages by repository id to match them back to the formulae. You can use packages from other repos go get the latest versions too.

**Comment by sjackman** [comment]
Amazing! The page of outdated packages in Brewsci/bio is super useful to me!
https://repology.org/metapackages/?inrepo=homebrew_tap_brewsci_bio&outdated=on

Thank you, Dmitry!

**Comment by AMDmi3** [comment]
You're welcome!
