### ISSUE TITLE
Is Funtoo being parsed correctly?

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#799]
pcl-pointcloud package shows it's up to date on Funtoo https://github.com/funtoo/science-kit/blob/master/sci-libs/pcl/pcl-1.9.1.ebuild
but not on the badge

[![Funtoo 1.3 package](https://repology.org/badge/version-for-repo/funtoo_1.3/pcl-pointclouds.svg)](https://repology.org/metapackage/pcl-pointclouds/versions)

**Comment by AMDmi3** [comment]
It doesn't use master branch
