### ISSUE TITLE
KDE neon lists old packages

### ISSUE THREAD

**Issue by jriddell** [repology/repology#805]
We have Qt 5.12 in KDE neon but repology still lists us as having Qt 5.11

**Comment by AMDmi3** [comment]
```
% curl --silent http://archive.neon.kde.org/dev/unstable/dists/xenial/main/source/Sources | grep -A2 'Package: qtbase-opensource-src' | grep ^Version
Version: 5.11.1+dfsg-2+16.04+xenial+build57
```

**Comment by AMDmi3** [comment]
Oh, it's `bionic` now, I get it. Is it worth leaving support for `xenial`?

Btw you could help by keeping your metadata up to date:

https://github.com/repology/repology/blob/master/repos.d/deb/kde_neon.yaml

**Comment by jriddell** [comment]
yeah drop xenial
https://github.com/repology/repology/pull/806

**Comment by AMDmi3** [comment]
It's now live.
