### ISSUE TITLE
Add pkgsrc-wip

### ISSUE THREAD

**Issue by ng-0** [repology/repology#810]
pkgsrc has a wip repository:

http://pkgsrc.org/wip/
git source: `git clone git://wip.pkgsrc.org/pkgsrc-wip.git wip`

I wonder if you could add it, given that Archlinux AUR and others are also in repology.

**Comment by luzpaz** [comment]
Very cool. Did not know that.

**Comment by AMDmi3** [comment]
I'd be happy to add it, but I need a parsable source of ports data. For pkgsrc we use INDEX, but I don't see anything like that for wip. Honestly, INDEX could be replaced with much more useful format too, see https://repology.org/addrepo for details.

**Comment by ng-0** [comment]
Okay. I did look at the missing piece between pkgsrc and pkgsrc-wip, too often just doing other work there.

**Comment by AMDmi3** [comment]
Nothing to do here unless someone sets up an export of pkgsrc data.
