### ISSUE TITLE
Repollogy shows 'tinker' versions wrong

### ISSUE THREAD

**Issue by yurivict** [repology/repology#823]
https://repology.org/project/tinker/versions shows the older ```8.2.1``` version in green, and FereBSD's ```8.5.3``` in black for some reason, when FreeBSD's version is in fact newer.

**Comment by AMDmi3** [comment]
The reason is that we don't trust newest versions from ports maintained by you, because you overuse 

```make
DISTVERSION=        <ver>-<rev>
DISTVERSIONSUFFIX=  -g<commit>
```

pattern which lead to fake versions.

https://repology.org/projects/?search=&maintainer=yuri%40freebsd.org&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=&problematic=on

**Comment by yurivict** [comment]
The right solution is to detect that ```DISTVERSIONSUFFIX``` is used and not pick up such versions because they are made-up, intermediate revisions that need to be used in cases of some ports. You scan the ports tree for repology, and see all those things. The latter part of the revision can signify an intermediate part, which is easy to see and ignore for the purposes of version comparison.

> The reason is that we don't trust newest versions from ports maintained by you, because you overuse

Blaming people for using legitimate features in legitimate ways can't ever be a good thing.

**Comment by AMDmi3** [comment]
I don't scan ports tree, I use INDEX which doesn't contain needed info. Which is worse, port and package users also have no way to know these versions are fake, so there's no way this would be tolerated. And this is not a legitimate feature, it's just a convenient hack.

**Comment by yurivict** [comment]
> I don't scan ports tree

Scan them then.

> And this is not a legitimate feature, it's just a convenient hack.

I disagree. This feature is defined by ```portmgr@```, and it also supports the important practical need. Say, some release is broken, or some important bugs were fixed in subsequent, unreleased revisions, or the project just doesn't make releases any more. Users need these fixes, and the version must be different, and this can't be ```PORTREVISION``` because this isn't just a port revision, but a project's sub-revision. So this feature supports the practically important situation. It's not just a whim, or that I just like doing this weird thing.

**Comment by AMDmi3** [comment]
> Scan them then.

Are you volunteering to write the code?

Actually, Repology will never ever do this, as executing third party code (which is required to properly extract information from ports tree) is slow and fragile, requires huge amount of work to implement and maintain and hinders Repology portability.

However for a long time I've had an idea of writing a web service similar to Freshports, targeted more on port developers, which would publish a proper detailed dump of ports metadata as a side product, which Repology could use. But right now I have more important tasks to do.

Fake versions would still be marked incorrect, however it would be possible to automate their detection and avoid collateral damage.

> So this feature supports the practically important situation.

None if this justifies lying to users by showing non-existing versions to them. I would have no objection to a more explicit schema, which would make it apparent to users which version part is upstream and which is local addendum denoting a snapshot, and would be as well parsable by Repology. For instance, FreeBSD have used `<upstream>.r<date>` long before github, and it was clean and straightforward. See https://github.com/repology/repology/issues/345 for more thoughts on this.

**Comment by yurivict** [comment]
The suggested solution: https://reviews.freebsd.org/D19664
