### ISSUE TITLE
[Question] understanding the 'respositories' box value

### ISSUE THREAD

**Issue by SRGOM** [repology/repology#833]
This is very helpful work, thank you. 

My question is- in the projects search page, eg here-

https://repology.org/projects/p/?inrepo=nix_stable&notinrepo=arch&repos=40

What does the repositories text box do? It's not particularly clear, sorry. A project- say powershell, which I'd present in nix_stable and not in arch should show up here, but it doesn't. What should I enter in the repositories no to make it show up?

**Comment by AMDmi3** [comment]
It's filter on number of repositories a project is present in. `40` means that only projects packaged in exactly 40 repositories are returned. Usually it's more useful to use range (e.g. `40-` which means "40 or more"), and to use `families` instead (which is displayed in the table as `Spread`, and is more representative as different versions and variations of the same package set are only counted once), while repositories is only useful in specific cases.

> It's not particularly clear, sorry

It's my bad, I fully understand that repology UX could be improved. Suggestions are welcome.

**Comment by SRGOM** [comment]
I think what you've said makes it perfectly clear. Maybe naming the text box something descriptive like 'Number of repositories containing' and changing the range inside to `1, 1-, 1-22` would reduce confusion (I assumed 1, 2, and 3-5 had special meanings, don't know why I ever typed 40 in there)
