### ISSUE TITLE
Is repology suitable for image repositories

### ISSUE THREAD

**Issue by CMCDragonkai** [repology/repology#839]
Dockerhub and related repositores also store packages, but their packages are OCI images. Would repology be suited to tracking these kinds of things as well?

**Comment by AMDmi3** [comment]
Sorry, I have no idea what these are and what data on software versions is published for them.

**Comment by CMCDragonkai** [comment]
These are docker containers or container images. Container images are usually compressed tar archives that get uncompressed into an overlay filesystem. The container registries also publish versions as tags.

**Comment by AMDmi3** [comment]
Any links?
