### ISSUE TITLE
Heads up: Scientific Linux 6/7 Will Remain Supported But The Distribution Is Ending

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#846]
https://listserv.fnal.gov/scripts/wa.exe?A2=SCIENTIFIC-LINUX-ANNOUNCE;11d6001.1904

**Comment by luzpaz** [comment]
Fermilab and other parties involved will continue supporting Scientific Linux 6 and Scientific Linux 7 based on RHEL6 and RHEL7, respectively, but moving forward they themselves are switching over to CentOS.

**Comment by AMDmi3** [comment]
Not our concern.
