### ISSUE TITLE
Add support for Red Star OS

### ISSUE THREAD

**Issue by XVilka** [repology/repology#856]
Red Star OS (Hangul: 붉은별; MR: Pulgŭnbyŏl) is a North Korean Linux distribution, with development first starting in 1998 at the Korea Computer Center (KCC).

Version 3.0 was released in the summer of 2013, but as of 2014, version 1.0 continues to be more widely used. It is offered only in a Korean language edition, localized with North Korean terminology and spelling.

https://en.wikipedia.org/wiki/Red_Star_OS

**Comment by AMDmi3** [comment]
Repository urls please

**Comment by AMDmi3** [comment]
This is closed OS.
