### ISSUE TITLE
Add NUR

### ISSUE THREAD

**Issue by HeikoStamer** [repology/repology#872]
Please add [NUR](https://github.com/nix-community/nur-combined), i.e. the Nix User Repository.

**Comment by AMDmi3** [comment]
Where can I find `packages.json` for it?

**Comment by HeikoStamer** [comment]
Unfortunately, AFAIK there is only a [json file](https://github.com/nix-community/NUR/blob/master/repos.json) for the user repositories and not for the packages. I am wondering how it was solved for `nix_stable` and `nix_unstable`, where such json files are provided.

**Comment by AMDmi3** [comment]
Timeout. Besides, this looks like a collection of private repositories, we don't honor these in Repology.

**Comment by oxzi** [comment]
Would it be possible to reopen this issue?

The Nix User Repositories (NUR) are indeed a collection of repositories where users can maintain their own packages. The NUR itself is just an index which automatically includes all packages within those repositories. It is an addition to the nixpkgs repository. In concept the NUR is very similar to the AUR, where also users can just create their own packages.

Furthermore, there is a JSON which includes all packages. It is available in the [nur-search](https://github.com/nix-community/nur-search) repository which is automatically updated ([latest JSON file](https://raw.githubusercontent.com/nix-community/nur-search/master/data/packages.json)).

In my opinion, the NUR should be as well included as the AUR. Would you consider reopening the issue? Thanks.
