### ISSUE TITLE
'version-for-repo' badges don't return link to source repo package file

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#874]
Is there a way when retrieving a 'version-for-repo' badge (of an individual package) to actually get the specific location of said package formula/config/build file ?

Example:
I've noticed that kali_rolling repositories aren't linking to their correct corresponding package builds and I wanted to quickly check this in a script.
Example of broken links that are generated on the each of these packages repology pages:

http://git.kali.org/gitweb/?p=packages/gimp.git  
http://git.kali.org/gitweb/?p=packages/inkscape.git  
http://git.kali.org/gitweb/?p=packages/rawtherapee.git
  
Here are their badge pages for convenience:  
[![Kali Linux Rolling package](https://repology.org/badge/version-for-repo/kali_rolling/gimp.svg)](https://repology.org/project/gimp/versions)  
[![Kali Linux Rolling package](https://repology.org/badge/version-for-repo/kali_rolling/inkscape.svg)](https://repology.org/project/inkscape/versions)  
[![Kali Linux Rolling package](https://repology.org/badge/version-for-repo/kali_rolling/rawtherapee.svg)](https://repology.org/project/rawtherapee/versions)

**Comment by AMDmi3** [comment]
There's no way, you can specify whatever link you want yourself.

**Comment by luzpaz** [comment]
Ok, thanks.
