### ISSUE TITLE
strange <li> tags in project information page

### ISSUE THREAD

**Issue by peutch** [repology/repology#879]
Hi,

After looking at the template https://github.com/repology/repology/blob/master/repologyapp/templates/project-information.html

I do not understand why I observe strange HTML tags (<li "="">) like in the following: https://repology.org/project/lighttpd/information

` 		<section id="Repositories">
			<h2>Repositories</h2>
			<ul>
				<li "=""><a href="https://repology.org/repository/adelie_current">Adélie Linux current</a></li>
				<li "=""><a href="https://repology.org/repository/alpine_edge">Alpine Linux Edge</a></li>
				<li "=""><a href="https://repology.org/repository/altsisyphus">ALT Sisyphus</a></li>
				<li "=""><a href="https://repology.org/repository/aosc">AOSC</a></li>
				<li "=""><a href="https://repology.org/repository/arch">Arch</a></li>`

Thanks!

**Comment by AMDmi3** [comment]
Fixed. An artifact of live patching.
