### ISSUE TITLE
MSYS2 package index

### ISSUE THREAD

**Issue by z3ntu** [repology/repology#887]
Hi, I was the person opening a report on the hidapi package on the website with the description:

> Hi, "MSYS2 mingw" has v0.9.0 in their repositories for about a month now, but it still shows up as outdated here. 
> 
> See https://github.com/msys2/MINGW-packages/commit/e94a88eaaeb59b58c7c4794027fe4370bcdc8252 . The package name isn't mingw-w64-i686-hidapi but mingw-w64-hidapi now, so that might be why it wasn't detected. 

The response was that http://repo.msys2.org/mingw/sources/mingw32.db.tar.gz doesn't contain this version.

Looking at the index at http://repo.msys2.org/mingw/sources/ shows that the mingw32.db.tar.gz file was last updated `01-Feb-2017 19:49` so it's really outdated.

From what I can see in that directory, files with the naming pattern `mingw-w64-$pkgname` get updated, but files with `mingw-w64-i686-$pkgname` and `mingw-w64-x86_64-$pkgname` are stale since 2015.

So for the package index, `/mingw/x86_64/mingw64.db.tar.gz` or `/mingw/i686/mingw32.db.tar.gz` should be used (it seems).

And yes, I'm also confused how mingw/msys are connected but it seems that the mingw-w64 project provides a "complete runtime environment for gcc" and msys2 is "based on modern Cygwin (POSIX compatibility layer) and MinGW-w64", so I'm guessing the "MSYS2-packages" repo is being built with Cygwin and the "MINGW-packages" repo is built with mingw-w64?

**Comment by AMDmi3** [comment]
Thanks for clarification, I've switched to actual indexes.
