### ISSUE TITLE
Which Python packages are packed for distributives

### ISSUE THREAD

**Issue by abitrolly** [repology/repology#893]
Can repology help answer the question - which Python packages (from `requirements.txt`) are already packaged by a given distribution?

https://discussion.fedoraproject.org/t/check-requirements-txt-against-existing-packages/2173

**Comment by AMDmi3** [comment]
Depends on what you mean by answering the question. There's no ready to use API endpoint or a badge, but if your question allows writing some client code, you could issue a request to `https://repology.org/api/v1/project/python:<package name>` for each item in `requirements.txt`, which would return basically everything Repology knows about a given module - among this info you could look for entries belonging to your repository of interest and check that the entry exists and/or if its version matches version requirement in `requirements.txt`.

**Comment by abitrolly** [comment]
Thanks. That helps.

**Comment by abitrolly** [comment]
I created Jupyter Notebook to experiment with API. These are dependencies for `anitya` project powering https://release-monitoring.org among which two PyPI packages are packaged, but not detected by Repology.

pypi | fedora_30 | debug
-- | -- | --
alembic | python-alembic |  
arrow | python-arrow |  
blinker | python-blinker |  
defusedxml | python-defusedxml |  
fedora_messaging |   | no such PyPI package
flask-login | python-flask-login |  
flask-restful | python-flask-restful |  
flask-wtf | python-flask-wtf |  
jinja2 | python-jinja2 |  
ordered-set | python-ordered-set |  
pyasn1 | python-pyasn1 |  
python-dateutil |   | no fedora_30 package in Repology
psycopg2 | python-psycopg2 |  
pytoml | python-pytoml |  
semver | python-semver |  
social-auth-app-flask | python-social-auth-app-flask |  
social-auth-app-flask-sqlalchemy | python-social-auth-app-flask-sqlalchemy |  
sseclient | python-sseclient |  
straight.plugin |   | no fedora_30 package in Repology
sqlalchemy | python-sqlalchemy |  
wtforms | python-wtforms |  

https://colab.research.google.com/drive/1AGzKal4EFdtZidCT23ANvYKk-fkO83Ft
