### ISSUE TITLE
Add KISS

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#899]
Home: https://getkiss.org/
Packaging info: https://getkiss.org/pages/package-system/
Repository: https://github.com/kisslinux/repo

Seems to be extremely easy to parse, `version` file in package directory contains version+revision, and `sources` file contains sources per line (but local files should be filtered).

CC @dylanaraps

**Comment by dylanaraps** [comment]
:+1:

NOTE: The distinction between local and remote files in `sources` is the presence of `://`.

**Comment by AMDmi3** [comment]
> NOTE: The distinction between local and remote files in `sources` is the presence of `://`

Nice suggestion, it simplifies the filter (my solution was to just filter out `files/`, `patches/` and `./` prefixes).

Any suggestions on how to handle `testing` repository? Include/exclude/add as separate repository?

**Comment by dylanaraps** [comment]
I would leave it out altogether. 

We'll be using it for `gcc`, `firefox` and other large/substantial packages (`rust`, `llvm` etc). I don't think the `testing` repository would be of much use to `repology` as it'll only contain 1-2 packages at a time and in infrequent intervals.

**Comment by dylanaraps** [comment]
Thanks for adding support! This is awesome.

A quick query; a few of our distribution packages (unique to KISS) also exist in other repositories however they're unrelated to ours. The duplicate packages have newer versions than the ones in KISS and display as being out of date in KISS.

See: https://repology.org/projects/?inrepo=kiss&outdated=1

Specifically `baselayout` (our base directories/files) and `kiss` (our package manager). I'm not sure if you have a system in place for naming conflicts like these. Just a heads up!

**Comment by AMDmi3** [comment]
Sure, I will address these.
