### ISSUE TITLE
Add API for project info

### ISSUE THREAD

**Issue by abitrolly** [repology/repology#906]
Is it possible to get contents of https://repology.org/project/python:social-auth-app-flask/information as JSON data? 

https://repology.org/api/v1/project/python:social-auth-app-flask/information or
https://repology.org/api/v1/project/python:social-auth-app-flask/info

That could be be used for data analysis, such as finding better matches for packages.

**Comment by AMDmi3** [comment]
There is https://repology.org/api/v1/project/python:social-auth-app-flask which contains all the info `information` page is constructed from, in form of raw package data. You can aggregate and process it any way you want.

**Comment by abitrolly** [comment]
Does that mean that https://pypi.org package data is not used at all - #278?

**Comment by AMDmi3** [comment]
Thus issue has nothing to do with PyPI, but yes, it's currently not supported.

**Comment by abitrolly** [comment]
If you're interested how it is done for Fedora, take a look at https://mdapi.fedoraproject.org/
