### ISSUE TITLE
KISS Linux - community repository split.

### ISSUE THREAD

**Issue by dylanaraps** [repology/repology#907]
I have split the `public` repository (now `community`) away from the main repositories.  

- https://github.com/kisslinux/community

I did this for the following reasons:

- Make it clear that the KISS developers are not responsible for community packages.
- Keep the core repositories clean (size will stay small and clones will stay fast).

I foresee our community repository growing and growing. It's better to have made this change now than in the future when the package count is large and KISS is widely used. 

I apologize for adding more work to your day, I really appreciate `repology` and the fact that KISS is supported by it. If you require any more information, don't hesitate to ask!

**Comment by dylanaraps** [comment]
I will also add that this repository is now **disabled** by default, I'm not sure if repology wants to track this or not.

**Comment by dylanaraps** [comment]
Ah. It looks like `repology` parsed KISS without error! I'm not sure if you want `repology` to track KISS' `community` repository. It is separated kinda like Arch's AUR is. It might be better to split it like so. :+1:

**Comment by AMDmi3** [comment]
> It looks like repology parsed KISS without error!

You were lucky, it would break if 9 more packages were removed as there's safeguard agains too many packages removed at once. Anyway, it's probably the mest to add community as separate repo.
