### ISSUE TITLE
Wikidata: updated package version not registering in badge

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#910]
Example (from the wings3d package):

[![Wikidata entry](https://repology.org/badge/version-for-repo/wikidata/wings3d.svg)](https://repology.org/project/wings3d/versions)

But there is an entry for the latest stable 2.2.4 on the wikidata page: https://www.wikidata.org/wiki/Q617006

![image](https://user-images.githubusercontent.com/4140247/63876173-f4bdd300-c992-11e9-90a7-9762ebe1863b.png)

Any idea why the most up to date stable version info is not getting passed correctly to repology ?

**Comment by AMDmi3** [comment]
Because it was added minutes ago.
