### ISSUE TITLE
Wikidata: support "download link" property for versions

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#915]
https://www.wikidata.org/wiki/Property:P4945 may be specified for versions, use it to fill `downloads`

**Comment by davidhicks** [comment]
The problem with using https://www.wikidata.org/wiki/Property:P4945 as a qualifier is that it is not clear whether it points to the source code or a binary distribution of an open source package.

A better long term fix may be to create a new Wikidata item for each version/release of software. This would allow other properties to be used better too--for example, software dependencies could be defined per software version as dependencies change from one software version to another.

**Comment by davidhicks** [comment]
To clarify, if one Wikidata item existed per software release/version, https://www.wikidata.org/wiki/Property:P4945 could be added to the item with multiple URIs. A qualifier could then be used to distinguish between a binary package and source package URI.

**Comment by AMDmi3** [comment]
> is that it is not clear whether it points to the source code or a binary distribution of an open source package

Repology currently does not differentiate, so it is OK.

**Comment by davidhicks** [comment]
I understand now--you were just wanting to extract download URIs from Wikidata, and don't need to distinguish between binaries, patches and source packages.

**Comment by AMDmi3** [comment]
Precisely
