### ISSUE TITLE
chocolatey: are pre-releases being shown in repology?

### ISSUE THREAD

**Issue by luzpaz** [repology/repology#922]
Usecase: [dust3d](https://chocolatey.org/packages/dust3d)  

But it's not in the badge. The package should of been parsed by repology already (based on https://repology.org/repositories/updates)  
 
[![Packaging status](https://repology.org/badge/vertical-allrepos/dust3d.svg)](https://repology.org/project/dust3d/versions)

JFYI, chocolatey has been redesigned: https://chocolatey.org/blog/chocolatey-website-redesign

**Comment by AMDmi3** [comment]
Repology uses `https://chocolatey.org/api/v2/Packages()?$filter=IsLatestVersion`. Since the package is not there, then obviously pre-releases are not returned by the API.
