### ISSUE TITLE
Add CentOS 8 and CentOS Stream repositories

### ISSUE THREAD

**Issue by fingolfin** [repology/repology#924]
CentOS 8 was just released, see <https://lists.centos.org/pipermail/centos-announce/2019-September/023449.html>. They also have a new product, "CentOS Stream", a " rolling-release Linux".

It would be super awesome if both could be added to repology.

Thank you for running this very useful project!

**Comment by AMDmi3** [comment]
I'm aware of the releases, and I'm waiting for source package repositories to become available. For instance, directory hierarchy under http://vault.centos.org/centos/8/ was created just today, but there are no files yet.

**Comment by AMDmi3** [comment]
Btw I could use a hint on how to better handle new repository structure.

http://vault.centos.org/centos/7/ contains the following repos

* atomic
* centosplus
* cloud
* configmanagement
* cr
* dotnet
* extras
* fasttrack
* nfv
* opstools
* os
* paas
* rt
* sclo
* storage
* updates
* virt

Of which Repology uses `os`, `updates` and `extras` (which itself may be incorrect or incomplete).

http://vault.centos.org/centos/8/ has different structure:
* AppStream
* BaseOS
* centosplus
* extras

and I'm not sure yet which of these should be included as 'CentOS 8'.

**Comment by AMDmi3** [comment]
I think I have a recipe to discover a relevant list of repositories (though it's just a hunch).
- Get CentOS iso.
- Extract (unsquashfs `install.img`, then mount `rootfs.img`)
- Check `etc/anaconda.repos.d`
  - Look for enabled repositories
  - Map them onto source ones from `CentOS-Sources.repo`

For CentOS 8:
```
etc/anaconda.repos.d # grep -R enabled=1 .
./CentOS-AppStream.repo:enabled=1
./CentOS-Base.repo:enabled=1
./CentOS-Extras.repo:enabled=1
```

So, we probably want AppStream, BaseOS and Extras as CentOS8 and maybe centosplus as additional repository.

**Comment by fingolfin** [comment]
Yes, I think that's right. Here's some background info: <https://www.linuxsysadmins.com/using-appstream-with-yum-in-red-hat-enterprise-linux-8/>. To quote:
> In older Red Hat releases and their media (ISO) content will be in a single directory which holds all the packages. Presently in RHEL 8 release, the Application Stream and yum are divided into two as “BaseOS” and “AppStream”.
>
> The “BaseOS” repository will have few packages which required for setting up a minimal Operating system. All other packages can be found under “AppStream” repository.

**Comment by fingolfin** [comment]
But http://vault.centos.org/centos/8/ seems to be still empty, i.e. the dirs are there but not the files. Indeed, based on the creation dates, it's just a few hours old. So may have to wait a bit?

Also: Thank you for working on this!

**Comment by AMDmi3** [comment]
`8-stream` is still empty, but I'm watching it.
