### ISSUE TITLE
Please enable compression of badges

### ISSUE THREAD

**Issue by Self-Perfection** [repology/repology#927]
Compression easily reduces size of allrepos badges ~10 times.

I see you use nginx as frontend. It compresses just text/html responses by default. To enable comression of other MIME types one should to set [gzip_types](https://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types), for SVG this would be:
`gzip_types image/svg+xml;`

**Comment by AMDmi3** [comment]
Done, thanks for suggestion!
